### ISSUE TITLE
RFE: Ansible scripts to include deployment of Cloudforms

### ISSUE THREAD

**Issue by alberttwong** [openshift/openshift-ansible-contrib#1029]
RFE since Cloudforms is the management console for OCP.

**Comment by cwilkers** [comment]
The reference architectures--new this week!--have a section on integrating with an existing CloudForms appliance, but I don't believe this is the right place to create a fully automated deployment of CloudForms.

[OCP on RHV reference architecture, chapter 3.3 ](https://access.redhat.com/documentation/en-us/reference_architectures/2018/html/deploying_and_managing_openshift_3.9_on_red_hat_virtualization_4/deploying_red_hat_openshift_container_platform#cloudforms_integration_optional)

**Comment by alberttwong** [comment]
Well.... ideally I'd also love to see Cloudforms deployed net new as another vm or tech preview container.
