### ISSUE TITLE
Deprecation  warnings when running OCP on RHV reference architecture

### ISSUE THREAD

**Issue by sradco** [openshift/openshift-ansible-contrib#1031]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one): Bug Report

# BUG REPORT INFO

### Environment

Red Hat Virtualization 4.2
Red Hat Enterprise Linux 7.5

**Command used to invoke ansible**:  
cd ~/git/openshift-ansible-contrib && ansible-playbook playbooks/deploy-host.yaml -e provider=rhv

**Output of ansible run**:  
TASK [deploy-host : Enable oVirt repository] *************************************************************************************************************************************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|exists` instead use `result is exists`. This feature will be removed in version 2.9. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Consider using the yum module rather than running yum.  If you need to use command because yum is insufficient you can add warn=False to this command task or set
command_warnings=False in ansible.cfg to get rid of this message.

.
.
.
TASK [deploy-host : Enable specified repositories not already enabled] ***********************************************************************************************************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|succeeded` instead use `result is succeeded`. This feature will be removed in version 2.9. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by cwilkers** [comment]
FYI, we are unsure of the future of this bit of code. It may make its way into openshift-ansible, or it may be deprecated in favor of providing the commands in documentation instead.

@dav1x would you like to comment?

**Comment by dav1x** [comment]
@cwilkers I believe it has been deprecated as we are moving away from this repo. There is an effort to get the official openshift ansible repo updated with some of these roles.
