### ISSUE TITLE
Missing return value description for ec2_vol_facts

### ISSUE THREAD

**Issue by ribeaud** [openshift/openshift-ansible-contrib#1033]
Hi,

Return value description should be part of [ec2_vol_facts](http://docs.ansible.com/ansible/latest/modules/ec2_vol_facts_module.html) documentation page.
I could update the documentation page but I do NOT know how to do it on that **GitHub** [page](https://github.com/ansible/ansible/edit/devel/lib/ansible/modules/cloud/amazon/ec2_vol_facts.py).
Thanks and cheers,

christian

**Comment by cooktheryan** [comment]
@ribeaud which version of OpenShift are you attempting to install.

**Comment by ribeaud** [comment]
Hi @cooktheryan. I am talking about the documentation page.
