### ISSUE TITLE
Missing OpenShift playbook - playbooks/openshift-node/network_manager.yml for OCP on rhv

### ISSUE THREAD

**Issue by sradco** [openshift/openshift-ansible-contrib#1034]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one): *BUG REPORT

 - As part of the all-in-one oVirt metrics store installation 
https://www.ovirt.org/develop/release-management/features/metrics/setting-up-viaq-logging/
we also run the following OpenShift playbook:
playbooks/openshift-node/network_manager.yml

I believe it might be missing in the OCP on rhv documentation steps.

@cwilkers

**Comment by cwilkers** [comment]
I'm not sure this is required.

According to the [OpenShift 3.9 Prerequisites Documentation](https://docs.openshift.com/container-platform/3.9/install_config/install/prerequisites.html#prereq-network-access), NetworkManager is ON by default, and is only disabled if you go in to the ifcfg-`interface` file and set it to OFF.

I just checked on a node in my environment, and the ifcfg file has no NetworkManager line at all, implying it is left to default ON.

I'm redeploying to be sure that the dnsmasq script creates its files as expected.

**Comment by cooktheryan** [comment]
Let me know how this goes

**Comment by richm** [comment]
https://github.com/ViaQ/Main/blob/master/README-install.md#running-ansible
You have to run _3_ separate playbooks, in order, to do an all-in-one install of OpenShift + logging for the ovirt metrics store.  Not sure when this changed - I think they added prerequisites.yml and network_manager.yml in 3.9

**Comment by sradco** [comment]
@richm Is it relevant only in the case on all-in-one?

**Comment by richm** [comment]
> @richm Is it relevant only in the case on all-in-one?

No.  It is relevant to all cases.

**Comment by cwilkers** [comment]
Looking at https://github.com/openshift/openshift-ansible/blob/master/playbooks/openshift-node/private/network_manager.yml This playbook makes one change over the default setup on the nodes, and that is to add the `NM_CONTROLLED` and `USE_PEERDNS` flags to the Ansible default ipv4 interface.

With the RHEL 7.5 KVM Guest image, NetworkManager is installed and running by default, and after running prerequisites.yml and deploy_cluster.yml in turn, DNS appears to be set up appropriately.
```
# cat /etc/resolv.conf
search cluster.local example.com
nameserver 192.168.155.151
```
