### ISSUE TITLE
AWS Ref arch question around ditching cfn

### ISSUE THREAD

**Issue by DanyC97** [openshift/openshift-ansible-contrib#1044]
@cooktheryan @mazzystr with the AWS OCP 3.9 red arch i see from [this](https://github.com/openshift/openshift-ansible-contrib/commit/6e1257863b0399517e80ce757daf7920d826e573) commit that  cfn was dropped in favour of ansible modules.

Could you please share the rational behind this action ?  I'm only asking because i'm curious, not because i disagree with ;)

Also should i understand that [this](https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible) code is going to be deprecated in favor of the new 3.9 code added recently ?

**Comment by cooktheryan** [comment]
@DanyC97 I believe its just the start to migrating where we are going in the future in regards to the deployment of AWS resources. Both mechanisms are good cfn and ansible. Ansible deployment has matured from previous iterations where there was potential for items to not deploy or not deploy correctly. 

You are correct in the deprecation.

**Comment by DanyC97** [comment]
@cooktheryan thanks a bunch for quick response.
So am i right to say that the new 3.9 aws code which doesn't rely cfn will also make it/ become the main code vs the aws code currently in openshift-ansible git repo ?

**Comment by cooktheryan** [comment]
I believe this code in the repository is a stop gap until the aws code in
openshift ansible is ready for GA

**Comment by DanyC97** [comment]
i see.

@michaelgugino @sdodson @cooktheryan any chance you can share what is it missing from the openshift-ansbile aws code to make it GA ? 

I'm asking because i'd like to understand where should i focus helping out: ( i have some internal bespoke solution and would love ditchign that in favour of the upstream solution assuming i'm going to ride the ride horse)

is it going to be the work @cooktheryan done (even if that is a stop gap and is completely different  - ie no ASG today, no AMI build - but is dead simple to get your head around) or not
-

**Comment by DanyC97** [comment]
most of the questions were asked, closing, thank you!
