### ISSUE TITLE
jq required but not found

### ISSUE THREAD

**Issue by chenqifeng28** [openshift/openshift-ansible-contrib#1049]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):
FEATURE REQUEST

$ mkdir ~/git
$ cd ~/git
$ git clone https://github.com/openshift/openshift-ansible-contrib.git
$ cd openshift-ansible-contrib/reference-architecture/day2ops/scripts
$ ./project_export.sh logging

[root@master scripts]# ./project_export.sh logging
jq required but not found

What is the jq? 
How can i resove it ,thx.

[root@master ~]# oc version
oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.com:8443
openshift v3.6.173.0.5
kubernetes v1.6.1+5115d708d7

[root@master ~]# ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

**Comment by l3andro** [comment]
Need install jq package on Linux.
