### ISSUE TITLE
AWS 3.9 sample inventory file

### ISSUE THREAD

**Issue by DanyC97** [openshift/openshift-ansible-contrib#1052]
@cooktheryan @mazzystr quick q: how is your sample inv looking when you trying to deploy 3.9 aws code ? 

Looking [here](https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/3.9/playbooks/vars/main.yaml) i see only a slim down version however i suspect you have more for r53 etc

**Comment by mazzystr** [comment]
@DanyC97 The file that you link out to is an extra vars file for aws infrastructure deployment.  That is not an example inventory file.  

The example inventory file is located within the reference architecture [document](https://access.redhat.com/documentation/en-us/reference_architectures/2018/html-single/deploying_and_managing_openshift_3.9_on_amazon_web_services/#openshift_ansible_installer_inventory).

**Comment by DanyC97** [comment]
oh i see, thx for the doc @mazzystr  !
