### ISSUE TITLE
Change project name when importing resources. Support export/import and the same cluster.

### ISSUE THREAD

**Issue by pugetc** [openshift/openshift-ansible-contrib#1056]
**FEATURE REQUEST**

# FEATURE REQUEST INFO
Ability to duplicate a project using export/import on the same cluster.
Change project name when importing resources.

## Problem Description
It would be nice to be able to export/import a project on the same cluster by changing the target project name. Today it is no possible, the source and target project names must be the same.

Is there any workaround?

**Comment by vrutkovs** [comment]
That sounds like an RFE in https://github.com/openshift/origin

What's your use case for this during openshift cluster install / lifecycle ?

**Comment by e-minguez** [comment]
Those scripts are no longer updated and are not supported. Closing this. Thanks
