### ISSUE TITLE
OpenShift Origin HA Installation on AWS

### ISSUE THREAD

**Issue by fszilinski** [openshift/openshift-ansible-contrib#1065]
**FEATURE REQUEST**:  
Step-by-step HowTo for OpenShift Origin HA Installation on AWS

The docs [here](https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible) says, it's deprecated. It links to [this](https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/3.9/playbooks) documentation. Is there anywhere a valid and working tutorial how OpenShift Origin 3.9 can be installed on AWS with high-availability features?

**Comment by mazzystr** [comment]
Sorry for the confusion.  Red Hat is in process of adding official support for AWS infrastructure deployment within openshift-ansible itself.  It's talking some time.

In the meantime please refer to the current release of Red Hat OCP 3.9 on AWS reference architecture.  Link is [here](https://access.redhat.com/documentation/en-us/reference_architectures/2018/html/deploying_and_managing_openshift_3.9_on_amazon_web_services/).

**Comment by fszilinski** [comment]
Ok, thanks for the information. In my view, the main reason for OpenShift Origin is the ability to provide a platform for development or testing (including high availability) without thinking about subscriptions or yes, opens source projects. I am aware that it is a stupid question, but is there an approximate estimate of when the Origin 3.9 Ansible scripts should work again?

**Comment by mazzystr** [comment]
Origin is the upstream for OpenShift Container Platform.  Origin is most definitely an Open Source project as is OpenShift Container Platform.  There is no subscription model for Origin.

re HA ... The control plane can most definitely be configured for HA in both Origin and OCP.  

The example inventory in the reference architectures should deploy both openshift-enterprise and origin just flip the value for openshift_deployment_type in the inventory.  Please file another issue if you find a specific problem with deploying either.
