### ISSUE TITLE
Backup export and import v3.10 with day2ops scripts

### ISSUE THREAD

**Issue by dzerhusen** [openshift/openshift-ansible-contrib#1080]
Hello,

got some issues with the project_export.sh and project_import.sh.

1) The project_export.sh  creates an ns.json which contains all namespaces. In my opinion it should just contain the namespace of the backup-project.

2) As i try to import the project it fails, cause the variable PROJECT is not set right: 

```
{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "annotations": {
          "openshift.io/description": "",
          "openshift.io/display-name": "",
          "openshift.io/requester": "system:admin",
          "openshift.io/sa.scc.mcs": "s0:c15,c0",
          "openshift.io/sa.scc.supplemental-groups": "1000210000/10000",
          "openshift.io/sa.scc.uid-range": "1000210000/10000"
        },
        "name": "bsh-infra",
        "namespace": "bsh-infra"
      },
.....
```

The command `jq -r .metadata.name ${PROJECTPATH}/ns.json)` doesnt find a string. 
 It should better look like  `jq -r .items[].metadata.name ${PROJECTPATH}/ns.json)`.
Also it seems the value "name" seems to be empty in v3.10 environment ( i just filled the field in this case)

Greetings,
Daniel

**Comment by e-minguez** [comment]
I think #1079 fixed it. Do you mind to try with the updated version? Thanks
