### ISSUE TITLE
Apps redirected to openshift-master.rcook-aws.sysdeseng.com for some reason

### ISSUE THREAD

**Issue by jaryn** [openshift/openshift-ansible-contrib#127]
Hi. Even though I have set the ``--public-hosted-zone`` parameter, accessing the console (for example ``https://openshift-master.MYDOMAIN.TLD/console/`` redirects me to 

``https://openshift-master.rcook-aws.sysdeseng.com/oauth2callback/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&...``

**Comment by cooktheryan** [comment]
Did you change the values in openshift-setup to reflect your github oauth values?

**Comment by jaryn** [comment]
No I didn't and after change it got fixed, but I think this should be configurable from the CLI, shouldn't it?

**Comment by ikke-t** [comment]
I was wondering the same. I got the installation successfull, but the first thing to get from opening the browser, I got the complaint: "This site can’t be reached openshift-master.rcook-aws.sysdeseng.com’s server DNS address could not be found."

I fail to see any option for it in the installer. That's actually a quite bad default setting, as it won't give any hint for the user why the browser starts to redirect to that foreign address. Without this issue I wouldn't have guessed it's looking for auth. Cluster just seems like broken from browser point of view.

**Comment by ikke-t** [comment]
Now that I got through the two issues that I hit, I must say this works really nice! Please add some mentioning to prerequisites that you need to create github org oauth, and and modify the yaml to get the settings right from the beginning. Or some option to installer. Thanks a lot!
