### ISSUE TITLE
fails with: 'dict object' has no attribute 'openshift'

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-ansible-contrib#128]
I tried containerized setup with this tool in amazon ireland:

`./ose-on-aws.py --keypair=$AWS_KEY --rhsm-user=$RHUSER --rhsm-password=$RHPWD --public-hosted-zone=konttikoulu.fi --rhsm-pool=$RHPOOL --region eu-west-1 --ami ami-02ace471 --master-instance-type t2.medium --node-instance-type t2.large --app-instance-type t2.medium --containerized true --app-dns-prefix=iken`

which leads to failure in:

```
TASK [set_fact] ****************************************************************
fatal: [ose-master01.konttikoulu.fi]: FAILED! => {
    "failed": true
}

MSG:

the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'openshift'

The error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/initialize_facts.yml': line 12, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        hostname: "{{ openshift_hostname | default(None) }}"
  - set_fact:
    ^ here


fatal: [ose-infra-node02.konttikoulu.fi]: FAILED! => {
    "failed": true
}

```

My clone of this tool is of version:
commit f5a7778950b5a3bf39feaea8f62c56ef382590b7
Merge: dd87087 df0f724
Author: Jason DeTiberus <detiber@gmail.com>
Date:   Mon Nov 21 12:10:41 2016 -0500

and I'm running this from rhel 7 latest from rhel container on my laptop.
openshift-ansible-playbooks-3.3.54-1.git.0.61a1dee.el7.noarch

**Comment by ikke-t** [comment]
It seems that the default setting for "--deployment-type" doesn't work. It's supposed to be openshift-enterprise, but this error is avoided by forcing it to that. Somehow that default value is lost during the process.

**Comment by cooktheryan** [comment]
@ikke-t are you using the RPM based playbooks or cloning openshift-ansible for the deployment?

**Comment by ikke-t** [comment]
@cooktheryan I use rpm version mentioned on last line of the issue. Only this repo (openshift/openshift-ansible-contrib) is from github.

**Comment by detiber** [comment]
@ikke-t which version of ansible are you using? openshift-ansible now requires Ansible 2.2

**Comment by ikke-t** [comment]
# rpm -q ansible
ansible-2.2.0.0-3.el7.noarch

**Comment by cooktheryan** [comment]
@ikke-t do you know if this is still an issue for you?

**Comment by ikke-t** [comment]
I haven't tried since, I have used the parameter each time now. I can test the next time I run it.

**Comment by cooktheryan** [comment]
Ok sounds good. Feel free to update us next time you do run it

**Comment by cooktheryan** [comment]
@ikke-t im going to close this. Feel free to re-open if you hit the issue again
