### ISSUE TITLE
Do not use master-http-proxy in GCE reference arch

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible-contrib#130]
```
      ExecStart=/usr/bin/kubectl proxy -p 8080 --address=0.0.0.0 --accept-hosts=^*$ --config=/etc/origin/master/admin.kubeconfig
```

This exposes a world readable cluster admin port on the internet.  We should not be doing this.

**Comment by smarterclayton** [comment]
@pschiffe

**Comment by pschiffe** [comment]
@smarterclayton hm, we are not doing this anymore https://github.com/openshift/openshift-ansible-contrib/issues/37

Where do you have that line from?
