### ISSUE TITLE
ERROR: (gcloud.compute.images.create)

### ISSUE THREAD

**Issue by Nick-Harvey** [openshift/openshift-ansible-contrib#137]
Error message " - The tar archive is not a valid image." when running ./gcloud script on mac.

**Comment by Nick-Harvey** [comment]
Looks like it has to do with how Mac compresses the disk.raw and Googles requirements to import disks:

see doc: https://cloud.google.com/compute/docs/images/import-existing-image#before-you-begin

**Comment by Nick-Harvey** [comment]
changing to gtar as per google doc, did not resolve the issue. Switching to a fedora VM

**Comment by cooktheryan** [comment]
You should have success with Fedora as I tried it on 25 last week

**Comment by Nick-Harvey** [comment]
I'm starting to suspect it has something to due with the qcow image. I got the same result on Fedora 25

**Comment by Nick-Harvey** [comment]
Nevermind, it's working in fedora. I had to go to my storage bucket and clear out the bad image.

**Comment by Nick-Harvey** [comment]
I spoke too soon. Same error, I'll rebuild the image myself and see if that does it

**Comment by Nick-Harvey** [comment]
rebuilding the image gets me to the point where it builds the first host. But for some reason it just sits there saying "waiting for <host> to come up". This just loops forever even though the machine is fully up and available (according to the serial console anyways)

**Comment by Nick-Harvey** [comment]
updated qemu to the latest on my fedora machine and this seems to have resolved the issue.

**Comment by cooktheryan** [comment]
@Nick-Harvey could you supply the version number it would be really helpful to have a known good version of qemu documented.
