### ISSUE TITLE
Message rotation on /var/log/messages

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible-contrib#151]
I don't see rotation of /var/log/messages happening in the GCE ref arch, and we have a *very* high debug level configured.  First, do we have this already and I missed it?  Second, if not, do we have it in OpenShift Ansible?  Third, if not, we should probably add it to the ref-arch, since this is a very likely cause of node failure on GCE.

@pschiffe

**Comment by smarterclayton** [comment]
I added https://github.com/openshift/origin-gce/commit/4b792d4d8e0c22a9967baa7b3461a8f973580437 for this - it's resulted in several nodes dying painful deaths.

**Comment by cooktheryan** [comment]
@smarterclayton @pschiffe any thoughts on lowering this debug level? If thats not an option we can add in the the rotate but this arch currently has the highest debug level

**Comment by cooktheryan** [comment]
I'm going to close this as we have not seen issues with other providers and debug 2
