### ISSUE TITLE
cloudformation template 

### ISSUE THREAD

**Issue by priyanka5** [openshift/openshift-ansible-contrib#157]
Hi, Where is the cloudformation template located for this HA architecture? 

I am looking to make some modifications in cloud formation template and then deploy the stack.

Any help?

Thanks in advance

**Comment by cooktheryan** [comment]
https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible/playbooks/roles/cloudformation-infra/files
