### ISSUE TITLE
Destination /etc/origin/cloudprovider/aws.conf does not exist 

### ISSUE THREAD

**Issue by unisisdev** [openshift/openshift-ansible-contrib#162]
Hi, first of all congratulations for your good work!

I'm trying to install Openshift Origin on AWS on the us-east-1 region.

The ose-on-aws.py command is executed almost successfully. However, I get the following error (on the 3 masters):

```
TASK [openshift_cloud_provider : Create cloud config] **************************
fatal: [ose-master01.foxtek.net]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "rc": 257
}

MSG: Destination /etc/origin/cloudprovider/aws.conf does not exist !
```

So, the "play recap" shows the following summary:

```
PLAY RECAP *********************************************************************
localhost                  : ok=19   changed=13   unreachable=0    failed=0   
ose-app-node01.foxtek.net  : ok=52   changed=8    unreachable=0    failed=0   
ose-app-node02.foxtek.net  : ok=52   changed=8    unreachable=0    failed=0   
ose-infra-node01.foxtek.net : ok=52   changed=8    unreachable=0    failed=0   
ose-infra-node02.foxtek.net : ok=52   changed=8    unreachable=0    failed=0   
ose-master01.foxtek.net    : ok=218  changed=65   unreachable=0    failed=1   
ose-master02.foxtek.net    : ok=195  changed=64   unreachable=0    failed=1   
ose-master03.foxtek.net    : ok=195  changed=64   unreachable=0    failed=1   
```

Do you have any ideas regarding why the /etc/origin/cloudprovider/aws.conf file was not created on any of the master nodes?

I have connected to the master nodes ("ssh ec2-user@ose-master01.foxtek.net") and the directory /etc/origin/cloudprovider exists but is totally empty (no files inside). Any ideas?

Thank you very much in advance!

Best Regards

**Comment by cooktheryan** [comment]
Do you have the most recent pull or openshift ansible git repo (
https://github.com/openshift/openshift-ansible) or the openshift-ansible
rpm playbooks?

**Comment by unisisdev** [comment]
Hi Ryan, thanks for your quick feedback!

I have locally cloned the https://github.com/openshift/openshift-ansible repo. 

Hope this helps. I f you need any other information, please let me know!

Thank you very much!

**Comment by unisisdev** [comment]
So, I'm using the latest commit of https://github.com/openshift/openshift-ansible.

Just in case it helps, this is the ose-on-aws.py command I'm using:

```
./ose-on-aws.py \
        --stack-name=$CLUSTER_NAME \
        --public-hosted-zone=$DOMAIN_NAME \
        --deployment-type=origin \
        --region=$AWS_REGION \
        --keypair=$CLUSTER_NAME \
        --create-key=yes \
        --key-path=/home/alex/.ssh/id_rsa.pub \
        --create-vpc=yes \
        --ami=$AWS_AMI \
        --github-organization=$GITHUB_ORGANIZATION \
        --github-client-id=$GITHUB_CLIENT_ID \
        --github-client-secret=$GITHUB_CLIENT_SECRET \
        --s3-bucket-name=$CLUSTER_NAME \
        --s3-username=$CLUSTER_NAME \
        --byo-bastion=no \
        --console-port=443 \
        --containerized=false \
        --app-dns-prefix=apps \
        --master-instance-type=m4.large \
        --node-instance-type=t2.medium \
        --app-instance-type=t2.medium \
        --bastion-instance-type=t2.micro
```
Of course, each $VARIABLE was previously assigned with their value.

Some of the AWS related variables were configured in this way:

```
AWS_REGION=us-east-1
AWS_AMI=ami-6d1c2007
```

Hope this helps!

Thanks in advance!

**Comment by cooktheryan** [comment]
The best place to open the bug in regards to /etc/origin/cloudprovider/aws.conf would be openshift-ansible git repo but I have provided a work around below. As something similar had happened in the past.

Add the following to the aws-ansible/playbooks/roles/prerequisite/tasks/main.yaml
```
- name: bug workaround
  file:
    path: /etc/origin/cloudproviders/aws.conf
    state: touch
    mode: 0644
```

**Comment by unisisdev** [comment]
@cooktheryan Great, thank you so much for your workaround! That was fast! :)

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, thanks again for your help.

I have applied your solution on my fork at https://github.com/unisis/openshift-ansible-contrib/commit/9a8ef5cb133eca57c730776e1d49bf640646024f.

But now I got this error:

```
MSG:

MODULE FAILURE

fatal: [ose-master03.foxtek.net]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to ose-master03.foxtek.net closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_SsLZIj/ansible_module_file.py\", line 450, in <module>\r\n    main()\r\n  File \"/tmp/ansible_SsLZIj/ansible_module_file.py\", line 421, in main\r\n    open(b_path, 'wb').close()\r\nIOError: [Errno 2] No such file or directory: '/etc/origin/cloudproviders/aws.conf'\r\n"
}
```

Also, I have noted that now the directory /etc/origin doesn't exists on the master nodes.

Maybe I have placed the workaround on the wrong place?

Thank you very much in advance!

**Comment by unisisdev** [comment]
Oh, I think that the right path is /etc/origin/cloudprovider/aws.conf, not /etc/origin/cloudproviders/aws.conf (cloudproviderS). I have ammended my commit and I will test it.

Thank you very much again for your help!

**Comment by unisisdev** [comment]
Ok, just FYI, even using the new path I still got this error:

```
TASK [prerequisite : Bug Workaround] *******************************************
fatal: [ose-master01.foxtek.net]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to ose-master01.foxtek.net closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_w7Yetq/ansible_module_file.py\", line 450, in <module>\r\n    main()\r\n  File \"/tmp/ansible_w7Yetq/ansible_module_file.py\", line 421, in main\r\n    open(b_path, 'wb').close()\r\nIOError: [Errno 2] No such file or directory: '/etc/origin/cloudprovider/aws.conf'\r\n"
}

MSG:

MODULE FAILURE
```

What do you think?

Thank you very much in advance!

**Comment by cooktheryan** [comment]
I believe we must create the cloudprovider directory first then create the file. That was my mistake.

```
- name: Create origin config dir
  file:
    path: "/etc/origin"
    state: directory
- name: Create cloudprovider config dir
  file:
    path: "/etc/origin/cloudprovider"
    state: directory
```

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, I will add and test such config today, thank you very much!

By the way, congratulations for your work on https://access.redhat.com/sites/default/files/attachments/ocp-on-aws-7.pdf, it's a great reference!

**Comment by unisisdev** [comment]
@cooktheryan By the way, if I want use a purchased SSL/TLS certificate for my domain (signed by a CA authority, instead of use the self-signed certificate created during the deployment), how can I do that? Thank you very much!

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, it worked! I have added the latest lines mentioned by you and this time I was able to create the cluster successfully! Thank you so much. So, the final amended commit is: https://github.com/unisis/openshift-ansible-contrib/commit/691a3ade375c712bc78c7fe8055c15783927d0b7.

**Comment by unisisdev** [comment]
@cooktheryan By the way, regarding my question about use CA-signed SSL certificates, I will open a new Issue (question) if it's ok for you, since it's totally unrelated to this issue and I think that it can be also useful for other persons in the future. I will close this issue. Thank you very much!!
