### ISSUE TITLE
How use CA-signed SSL/TLS certificates? (instead of self-signed)

### ISSUE THREAD

**Issue by unisisdev** [openshift/openshift-ansible-contrib#164]
Hi! First of all, congratulations for this great contribution to the community.

I was able to install a new cluster using Openshift Origin on AWS (thanks for your help Ryan!)

I can open the Openshift console on the browser and -as it was described on the documentation- I can navigate the console after accept 3 times the self-signed SSL/TLS certificate.

However, it could be really nice use instead a SSL/TLS certificate purchased to a CA authority.

How can I change the SSL/TLS certificate used by the "Reference Architecture" deployment on AWS? 

I'm only interested on use that certificate on the public urls like https://openshift-master.domain.com (not on any private communication performed by internal Kubernetes services)

Thank you very much in advance!

**Comment by cooktheryan** [comment]
@unisisdev I haven't forgotten about you. Will get you some information soon

**Comment by leandrok** [comment]
@cooktheryan Hi Ryan, great! Thank you very much in advance! :+1: 

By the way, I have a fully functional Openshift Origin cluster on AWS thanks to your help, thank you. 

So, if you could indicate on which place(s) -before or after deploy the cluster- I should replace the self-signed SSL cert(s) with CA-signed certs (only for the public urls used on browsers), that will be great! 

Take your time. Thank you very much in advance!

**Comment by cooktheryan** [comment]
Check out 

https://docs.openshift.com/container-platform/3.3/install_config/install/advanced_install.html#advanced-install-custom-certificates

If you add the entries relating to your environment to aws-ansible/playbooks/openshift-setup.yaml it should deploy the certificates that you define

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, thank you very much for your info! 

I will create a new Openshift Origin cluster using my wildcard CA-signed certificate. 

After have success I will close this Issue, thank you! 

So, just to check, after read these references, I think that I must do the following:

1) Edit openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/openshift-setup.yaml

2) At the end of the file add the following lines (documentation use json, but that file is yaml):
          openshift_master_named_certificates:
          - certfile: /path/to/cert.crt
            keyfile: /path/to/cert.key

Ok, I will try and I will post my results. Thank you very much!

**Comment by cooktheryan** [comment]
Yep that should work. I have not had the time to validate it yet.  Once you
fill in those values just launch ose-on-aws as you normally would.

**Comment by unisisdev** [comment]
@cooktheryan Great, thank you very much! I will test it today and I will report the results to you. Thanks!

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, it worked like a charm! I'm using my CA-signed/purchased wildcard SSL cert now. Thank you so much!!

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, thanks again. 

Sorry for bother you again, but now I have a side effect after start using the CA-signed/purchased SSL cert, and maybe you can help me. Thanks in advance.

As I said, It works like a charm on the web browser when I navigate to https://openshift-master.domain.com.

Now, I have connected via SSH to the master to grant me admin permissions:

```
oadm policy add-cluster-role-to-user cluster-admin unisisdev
```

I have executed this command several times before use the CA-signed/purchased SSL cert and it always worked. But now, after use the CA cert, I got this:

```
error: Get https://internal-openshift-master.domain.com/api: x509: certificate signed by unknown authority
See 'oadm policy add-cluster-role-to-user -h' for help and examples.
```

(On the above message, I have replaced the real domain name with "domain.com")

The purchased cert is a wildcard cert so it should work on any *.domain.com host, even internal-openshift-master.domain.com

Maybe you know how fix this problem?

Thank you very much in advance!

**Comment by cooktheryan** [comment]
@unisisdev that would most likely be a question for the openshift-ansible repo as that repository does more work on the productization and running of openshift.

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, thanks for your reply. Good idea, I will follow your suggestion. Thanks again for the help already provided. Regards.
