### ISSUE TITLE
How deploy Fabric8 on top of Openshift Origin on AWS?

### ISSUE THREAD

**Issue by unisisdev** [openshift/openshift-ansible-contrib#169]
Hi, thanks again for your good work, I think that this is my last question :)

First of all, I apologize because this question is maybe a bit off-of-topic (related mainly to Fabric8). But I'm doing this question because I was able to install Fabric8 on other Kubernetes setups but -since I'm new using Openshift and this deployment system- I have some questions, thanks in advance!

So, I have installed successfully Openshift Origin on AWS using the reference implementation (using the ose-on-aws.py script)

I have used Fabric8 before and I want deploy Fabric8 on the reference implementation deployment. I'm using the following command:

```
gofabric8 deploy --domain=apps.domain.com
```

Of course, I'm using my real domain instead of "domain.com". I'm prepending the preffix "apps" because on ose-on-aws.py the --app-dns-prefix parameter is "apps". Is the --domain parameter ok? Or should I use just "domain.com"? Or, since apps is used by Openshift apps, should I use a different subdomain like "f8.domain.com"?

On the other hand, "gofabric8 deploy" also supports the parameter "--loadbalancer=true" to use the cloud's load balancer. Since I'm using AWS, is mandatory provide that parameter and use ELB? (I don't want use ELB, since Fabric8 use their own loadbalancer, I just want to know if it's mandatory use ELB on this setup)

Finally, I want mention that using "gofabric8 deploy --domain=apps.domain.com" I can open the Fabric8 console at "http://fabric8.default.apps.domain.com/workspaces?q=". I accept the self-signed certs (again) and almost immediately Fabric8 try to authenticate with OAuth on GitHub (for "OpenShift-3.2-Reference-Arch". Even accepting, the browser enters on a loop of redirections until GitHub shows an error (operation is too longer due the loop). Maybe it's some misconfiguration when I have executed "gofabric8 deploy"? Or maybe I must create a new OAuth Application on GitHub for Fabric8? Or maybe there are some "oc oauthclient" that I must execute?

Thank you very much in advance! Your feedback will be very useful for me, thanks!

**Comment by unisisdev** [comment]
Hi, during the past days I made a good progress and Fabric8 is almost deployed on top of the Reference Implementation (Openshift on AWS). I say "almost" because although gogs, nexus, jenkins works like a charm, when I try to login into the Fabric8 console, I enter on the oauth "loop" related to GitHub (described above). So, I will close this ticket and I will create a new ticket (much more specific) to get some feedback about what could be wrong on the oauth side. Thanks in advance!

**Comment by cooktheryan** [comment]
Would love to see your Fabric8 notes if you end up recording them

**Comment by unisisdev** [comment]
@cooktheryan Hi Ryan, sure! I will paste my notes below.

First of all, I have installed the Reference Architecture on AWS (usine ose-on-aws.py command) using Atomic Host. The values provided to ose-on-aws.py were:

```
Configured values:
	stack_name: openshift-domain
	ami: ami-cfeca0d8
	region: us-east-1
	master_instance_type: m4.large
	node_instance_type: t2.medium
	app_instance_type: t2.medium
	bastion_instance_type: t2.micro
	keypair: openshift-domain
	create_key: yes
	key_path: /home/user/.ssh/id_rsa.pub
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: origin
	public_hosted_zone: domain.com
	app_dns_prefix: apps
	apps_dns: apps.domain.com
	rhsm_user: None
	rhsm_password: *******
	rhsm_pool: None
	containerized: true
	s3_bucket_name: openshift-domain
	s3_username: openshift-domain
	github_client_id: xxxxxxxxxxxxxxxxxxxxx
	github_client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	github_organization: <name>
```

Then, after deploy the Openshift Origin cluster I have downloaded the gofabric8 binary from https://github.com/fabric8io/gofabric8/releases.

Finally, I have executed the Fabric8 installation using the following command:

```
gofabric8 deploy --pv=false \
       --namespace="default" \
       --domain=apps.$DOMAIN_NAME \
       --api-server=openshift-master.$DOMAIN_NAME:443 \
       --version=2.2.18
```

I'm using the 2.2.18 version of gofabric8 because it seems like there are a bug related to oauth on version 2.2.19, according to https://www.bountysource.com/issues/39515971-fabric8-console-latest-doesn-t-seem-to-work-with-openshift-oauth-any-more.

And that's all, after some minutes I can access Gogs at http://gogs.default.apps.domain.com and same for Nexus, etc. As I said, although I can access the Fabric8 console at http://fabric8.default.apps.foxtek.net, the console immediately enters on an endless loop to authenticate via oauth against GitHub. I don't how solve this issue yet and I have provided more info at https://github.com/openshift/openshift-ansible-contrib/issues/196. Hope this helps!
