### ISSUE TITLE
vagrant up fails on Ansible deployment: master1 and node1/2 unreachable

### ISSUE THREAD

**Issue by metmajer** [openshift/openshift-ansible-contrib#172]
Hi, I've just tried to create OpenShift using Vagrant, but failed early in the deployment:

```
TASK [setup] *******************************************************************
ok: [admin1]
fatal: [master1]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
fatal: [node1]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
fatal: [node2]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
```

**Comment by chekolyn** [comment]
I think I'm hitting this one too (libvirt). From what I've gathered it looks like eth1 doesn't get an ip from Vagrant until you **ifdown eth1 && ifup eth1**. Thus the master1 is not reachable via the 192.168.50.0/24 subnet.

You can try to add an inline script and see how it goes: https://www.vagrantup.com/docs/provisioning/shell.html

**Comment by mikonoid** [comment]
Same issue. I've tried to add in Vagrant file:
```
config.vm.define "node2" do |node2|
    node2.vm.network :private_network, ip: "#{NETWORK_BASE}.#{INTEGRATION_START_SEGMENT + 2}"
    node2.vm.hostname = "node2.example.com"
    node2.vm.provision "shell",
       inline: "ifdown eth1 && ifup eth1"
    node2.hostmanager.aliases = %w(node2)
  end
```
But it was not help.

**Comment by chekolyn** [comment]
@mikonoid 
I think I did a commit to fix this issue. Please check out this pull request: https://github.com/openshift/openshift-ansible-contrib/pull/245
That commit does what I suggested above but only when it doesn't detect and IP in eth1.

Can you confirm that you are hitting the same issue when eth1 doesn't have an IP?

**Comment by mikonoid** [comment]
@chekolyn  hey! I just rebooted my laptop and remove .vagrant dir. For now, everything is working! Thanks!
