### ISSUE TITLE
[refarch/ocp-cli] cloud-config sudo !requiretty filename must have `.conf` extenstion

### ISSUE THREAD

**Issue by markllama** [openshift/openshift-ansible-contrib#174]
In the ocp-cli scripts, when creating the cloud-config for a host the sudo config file must have the `.conf` extension:

ch4.5.1_user_data.sh

https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/osp-cli/ch4.5.1_user_data.sh#L20

**Comment by markllama** [comment]
No, in fact, it doesn't.  It works in later exactly as is.

**Comment by markllama** [comment]
PR pending: https://github.com/openshift/openshift-ansible-contrib/pull/189

**Comment by cooktheryan** [comment]
@markllama merged
