### ISSUE TITLE
Registration Broken

### ISSUE THREAD

**Issue by mrobson** [openshift/openshift-ansible-contrib#18]
It looks like a 'Subscription Name' update leads to the pool RegEx[1] matching nothing.

Subscription Name:   Red Hat OpenShift Container Platform, Premium, 2-Core
Subscription Name:   Red Hat OpenShift Container Platform, Standard, 2-Core
Subscription Name:   Red Hat OpenShift Container Platform Broker/Master Infrastructure

[1] https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/aws-ansible/playbooks/roles/rhsm-subscription/tasks/main.yaml#L7

**Comment by cooktheryan** [comment]
This should be resolved in merge #20
