### ISSUE TITLE
hide github organization secrets from confirmation

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-ansible-contrib#197]
I added github organization details which are now an option, but noticed the confirmation prints out the secrets. I think it should hide them with asterix, as it hides the password:

`./ose-on-aws.py .... --github-client-id $GH_CID --github-client-secret $GH_CSEC \
  --github-organization $GH_ORG`

which leads to printout:

```
	github_client_id: dda44......
	github_client_secret: 5583113e......
	github_organization: myorgname
```

which should be instead:
```
	github_client_id: *********
	github_client_secret: *********
	github_organization: myorgname

```

My clone of this tool is of version:
commit 94896b3704c2afa3b90525e36ee94a520a63449e
Merge: ae30a4e 06e6cea
Author: Davis Phillips <davis.phillips@gmail.com>
Date:   Tue Jan 17 15:28:34 2017 -0600

and I'm running this from rhel 7 latest from rhel container on my laptop.

**Comment by ikke-t** [comment]
I created PR: https://github.com/openshift/openshift-ansible-contrib/pull/198

**Comment by cooktheryan** [comment]
Really good idea! Merged the PR. Thank you for submitting
