### ISSUE TITLE
AZ lookup errors in us-east-2 and Canada region

### ISSUE THREAD

**Issue by cooktheryan** [openshift/openshift-ansible-contrib#208]
Errors have been discovered when using the AZ look up script.

**Comment by gihad** [comment]
Hi, does this mean that currently aws-ansible will not be able to deploy the reference architecture in us-east-2 and Canada regions?

Thanks,
Gihad

**Comment by cooktheryan** [comment]
I caught the PR #212 up so you may be able to use it as a work around

**Comment by cooktheryan** [comment]
Resolved with #315
