### ISSUE TITLE
AWS: validate deployment fails on TASK [validate-app : Wait for build to complete]

### ISSUE THREAD

**Issue by mcedica** [openshift/openshift-ansible-contrib#226]
This is not an issue, is more a question, looking for ideas on how to investigate:

Finally I was able to finish the deployment, but on the PLAY RECAP, the app nodes are marked as failing:
ose-app-node01.io.nuxeo.com : ok=3    changed=1    unreachable=0    failed=1   
ose-app-node02.io.nuxeo.com : ok=3    changed=1    unreachable=0    failed=1   

However the only failed task on these is TASK [rhsm-repos : disable unneeded repos] , only because of:

```
fatal: [ose-app-node02.io.nuxeo.com]: FAILED! => {"changed": true, "cmd": ["subscription-manager", "repos", "--disable=*"], "delta": "0:00:03.081649", "end": "2017-01-21 18:14:48.087315", "failed": true, "rc": 1, "start": "2017-01-21 18:14:45.005666", "stderr": "", "stdout": "Error: '*' does not match a valid repository ID. Use \"subscription-manager repos --list\" to see valid repositories.", "stdout_lines": ["Error: '*' does not match a valid repository ID. Use \"subscription-manager repos --list\" to see valid repositories."], "warnings": []}
```

When trying to validate this deployment by running:
ansible-playbook -i inventory/aws/hosts/ -e 'public_hosted_zone=io.nuxeo.com  wildcard_zone=apps.io.nuxeo.com console_port=443 stack_name=openshift-infra' playbooks/validation.yaml

I fail on:
```TASK [validate-app : Create Hello world app] ***********************************
changed: [ose-master01.io.nuxeo.com]

TASK [validate-app : Wait for build to complete] *******************************
FAILED - RETRYING: TASK: validate-app : Wait for build to complete (30 retries left).
--
FAILED - RETRYING: TASK: validate-app : Wait for build to complete (1 retries left).
fatal: [ose-master01.io.nuxeo.com]: FAILED! => {"attempts": 30, "changed": true, "cmd": "oc get pod | grep -v deploy | awk '/cakephp-ex-1-build/{ print $3 }'", "delta": "0:00:00.160929", "end": "2017-01-24 14:39:56.519672", "failed": true, "rc": 0, "start": "2017-01-24 14:39:56.358743", "stderr": "", "stdout": "Pending", "stdout_lines": ["Pending"], "warnings": []}
```

I also tried to create a new app and a new-build and also seems to fail on the same step:
Error from server: Timeout: timed out waiting for build nuxeo-oo-image-builder-1 to start after 10s.
Looking for ideas on how to investigate. ( running oadm diagnostics on first master failed with https://bugzilla.redhat.com/show_bug.cgi?id=1378883 )

**Comment by cooktheryan** [comment]
can you login to the master and return the following oc get nodes
--show-labels

**Comment by mcedica** [comment]
[ec2-user@ip-10-20-4-68 ~]$ oc get nodes --show-labels
NAME                                        STATUS                     AGE       LABELS
ip-10-20-4-68.us-west-2.compute.internal    Ready,SchedulingDisabled   21h       KubernetesCluster=openshift-infra,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2a,kubernetes.io/hostname=ip-10-20-4-68.us-west-2.compute.internal,role=master
ip-10-20-4-87.us-west-2.compute.internal    Ready                      21h       KubernetesCluster=openshift-infra,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2a,kubernetes.io/hostname=ip-10-20-4-87.us-west-2.compute.internal,role=infra
ip-10-20-5-15.us-west-2.compute.internal    Ready                      21h       KubernetesCluster=openshift-infra,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,kubernetes.io/hostname=ip-10-20-5-15.us-west-2.compute.internal,role=infra
ip-10-20-5-175.us-west-2.compute.internal   Ready,SchedulingDisabled   21h       KubernetesCluster=openshift-infra,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,kubernetes.io/hostname=ip-10-20-5-175.us-west-2.compute.internal,role=master
ip-10-20-6-106.us-west-2.compute.internal   Ready,SchedulingDisabled   21h       KubernetesCluster=openshift-infra,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2b,kubernetes.io/hostname=ip-10-20-6-106.us-west-2.compute.internal,role=master

**Comment by cooktheryan** [comment]
It appears your app nodes did not get installed and configured

**Comment by mcedica** [comment]
thx. This is what I was suspecting since they were marked as failing on PLAY RECAP. Tried several times in a row and the only failing tasks were rhsm-repos : disable unneeded repos. I guess I could try to follow the documentation to add new nodes to an existing cluster

**Comment by mcedica** [comment]
Is is normal that one these app nodes I get 
"This system has no repositories available through subscriptions"? thx

**Comment by cooktheryan** [comment]
that shouldn't be correct. On your app nodes lets try to manually subscribe them. 

subscription-manager unregister && subscription-manager register from there we can manually add the pool

**Comment by mcedica** [comment]
yes, I have been trying to manually add them:
subscription-manager unregister && subscription-manager register & sudo subscription-manager list --available --all => lists the same subscription as on the infra nodes "OpenShift Business Partner Supported NFR"

sudo subscription-manager repos --list
This system has no repositories available through subscriptions.
OR
```
[ec2-user@ip-10-20-4-204 ~]$ sudo subscription-manager attach --pool=8a85f98159c9b19a0159ca9b636750f0
No subscriptions are available from the pool with ID '8a85f98159c9b19a0159ca9b636750f0'.
[ec2-user@ip-10-20-4-204 ~]$ sudo subscription-manager repos --list
This system has no repositories available through subscriptions.
```

**Comment by cooktheryan** [comment]
Can you tell me how many entitlements "OpenShift Business Partner Supported NFR" has?

**Comment by mcedica** [comment]
I actually don't understand the question. But It turnes out that I have 2 subscriptions 'OpenShift Business Partner Supported NFR'. I tried attaching the poolId of the second one and now I get the list of repositories. Thx

**Comment by mcedica** [comment]
I confirmed that all of the above were because my 2 app nodes were not registered with the right subscription ( probably due to running the scripts with different subscriptions).
After manually connecting on the 2 nodes and registering with the right pool, all nodes are OK in the PLAY RECAP.

My validation phase still fails with one error on the phase:
TASK [validate-app : check the status of the page]

Status code was not [200]: HTTP Error 503: Service Unavailable", "pragma": "no-cache", "redirected": false, "status": 503, "url": "http://cakephp-ex-validate.apps.io.nuxeo.com"}

**Comment by cooktheryan** [comment]
Let's check the health of pods in the default project.

oc project default
oc get pods

**Comment by mcedica** [comment]
Marianas-MacBook-Pro:nuxeo-s2i mariana$ oc project default
Now using project "default" on server "https://openshift-master.io.nuxeo.com:443".
Marianas-MacBook-Pro:nuxeo-s2i mariana$ oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-2-f2jts    1/1       Running   0          1d
docker-registry-2-h0m19    1/1       Running   0          1d
registry-console-1-r8wa0   1/1       Running   0          1d
router-1-qt89d             1/1       Running   0          1d
router-1-vt5up             1/1       Running   0          1d

**Comment by cooktheryan** [comment]
Let's ignore the validate playbook for now. Can you login to the gui,
create, a project and launch an example app? Most of coding languages have
examples already to defined to test.

Ryan

**Comment by mcedica** [comment]
Thx Ryan.

For example on both " cakephp-mysql-example " and "nodejs-mongodb-example "
I get similar errors related to Cannot create secret, Cannot create deployment config and Cannot create deployment config "database":

```
Cannot create secret "nodejs-mongodb-example". Secret "nodejs-mongodb-example" is invalid: [data[databasePassword]: Invalid value: "databasePassword": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*, data[databaseUser]: Invalid value: "databaseUser": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*, data[databaseAdminPassword]: Invalid value: "databaseAdminPassword": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*].

Cannot create deployment config "nodejs-mongodb-example". DeploymentConfig "nodejs-mongodb-example" is invalid: [spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.key: Invalid value: "databaseUser": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*, spec.template.spec.containers[0].env[2].valueFrom.secretKeyRef.key: Invalid value: "databasePassword": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*, spec.template.spec.containers[0].env[4].valueFrom.secretKeyRef.key: Invalid value: "databaseAdminPassword": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*].
```

However, I was just trying to run them on the spot, so probably I did not configure them corectly

**Comment by cooktheryan** [comment]
Try to launch this in a new project. This is from the ref arch doc

```
oc new-app --docker-image registry.access.redhat.com/openshift3/mysql-55-rhel7 --name=db -e 'MYSQL_USER=dba' -e 'MYSQL_PASSWORD=d0nth@x' -e 'MYSQL_DATABASE=persistent'
```

**Comment by mcedica** [comment]
Sry, I actually decided to start all over and turned out to be a very bad idea.
Somehow I ended up with:
[ec2-user@ip-10-20-6-232 ~]$ sudo subscription-manager list

+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+
Product Name:   Red Hat Enterprise Linux Server
Product ID:     69
Version:        7.3
Arch:           x86_64
Status:         Not Subscribed
Status Details: Not supported by a valid subscription.
on all the nodes.
Thx for your help, I will close the issue.

**Comment by mcedica** [comment]
@cooktheryan for info, on the new stack I get the same errors as before on validating the stack and 
starting 'nodejs-mongodb-example', but  mysql ( from openshift3/mysql-55-rhel7) runs OK

**Comment by mcedica** [comment]
OK, thx!
one last question.  Is the validate cake suppose to answer on 'http://cakephp-ex-validate.apps.io.nuxeo.com/' ? our of the box or I have to configure something?

**Comment by cooktheryan** [comment]
It should just work. Here is the output from the Pull request CI job

https://aos-ci.s3.amazonaws.com/openshift/openshift-ansible-contrib/jenkins-e2e-openshift-on-aws-pr-2-test-matrix-nodes=openshift-ose-aws-slave-12/6e87f3889ab0d7aef8b07c13a12b3f48c2018af2.txt

Browse towards the bottom

**Comment by mcedica** [comment]
ok. Thx. I have a general problem with the routing as on none of my tests projects I managed to access them

**Comment by cooktheryan** [comment]
Hmm yea I would investigate the router for sure. Can you verify the
subdomain is correct in your /etc/origin/master/master-config.yaml

**Comment by mcedica** [comment]
It's: subdomain:  ""

**Comment by cooktheryan** [comment]
AHHH thats it!

OK we lets manually add in apps.io.nuxeo.com to all masters and restart the
atomic-openshift-master-api

**Comment by mcedica** [comment]
worked like a charm :) Thx a lot for your help!
