### ISSUE TITLE
GCE use of hostnames is not correct for persistent disks

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible-contrib#248]
OpenShift requires nodeName == instanceName for attaching PDs to instances.  We fixed openshift-ansible to always set that, but the ref-arch was bypassing that with https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/gce-ansible/playbooks/openshift-setup.yaml#L8.   Those settings should be removed and replaced with:

```
openshift_cloudprovider_kind: gce
```

However, for all of this to work we need https://github.com/openshift/openshift-ansible/pull/3229 merged in both sets of playbooks, and an opt in value to use this pattern (since it would break old clusters).

**Comment by smarterclayton** [comment]
@cooktheryan fyi

**Comment by cooktheryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document Dynamic Provisioning with OCP [3.4-OCP-SUP]](https://trello.com/c/5jqQQQZc/557-document-dynamic-provisioning-with-ocp-3-4-ocp-sup)

**Comment by cooktheryan** [comment]
Added changes suggested by @smarterclayton and @detiber waiting for nodeName playbook to ship

**Comment by smarterclayton** [comment]
Fixed
