### ISSUE TITLE
fail on Template  for greenfield 

### ISSUE THREAD

**Issue by Mangirdaz** [openshift/openshift-ansible-contrib#25]
Fail with file not found:

````
TASK [ssh-key : OSE ec2 key] ***************************************************
task path: /home/mangis/workspace/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/roles/ssh-key/tasks/main.yaml:2
skipping: [localhost] => (item=)  => {"changed": false, "item": "", "skip_reason": "Conditional check failed", "skipped": true}

TASK [cloudformation-infra : Create Greenfield Infrastructure] *****************
task path: /home/mangis/workspace/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/roles/cloudformation-infra/tasks/main.yaml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mangis
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475326149.27-207773419727810 `" && echo ansible-tmp-1475326149.27-207773419727810="` echo $HOME/.ansible/tmp/ansible-tmp-1475326149.27-207773419727810 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpTaGfYL TO /home/mangis/.ansible/tmp/ansible-tmp-1475326149.27-207773419727810/cloudformation
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 /home/mangis/.ansible/tmp/ansible-tmp-1475326149.27-207773419727810/cloudformation; rm -rf "/home/mangis/.ansible/tmp/ansible-tmp-1475326149.27-207773419727810/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_R4Ze5y/ansible_module_cloudformation.py", line 401, in <module>
    main()
  File "/tmp/ansible_R4Ze5y/ansible_module_cloudformation.py", line 269, in main
    template_body = open(module.params['template'], 'r').read()
IOError: [Errno 2] No such file or directory: 'roles/cloudformation-infra/files/greenfield.json'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "cloudformation"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_R4Ze5y/ansible_module_cloudformation.py\", line 401, in <module>\n    main()\n  File \"/tmp/ansible_R4Ze5y/ansible_module_cloudformation.py\", line 269, in main\n    template_body = open(module.params['template'], 'r').read()\nIOError: [Errno 2] No such file or directory: 'roles/cloudformation-infra/files/greenfield.json'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

Testing this with slight modified version as I dont have subscription, but this should not impact this place. Looks like template is not being resolved.

**Comment by Mangirdaz** [comment]
Looks like template parameter required full path.	
`The local path of the cloudformation template. This parameter is mutually exclusive with 'template_url'. Either one of them is required if "state" parameter is "present" Must give full path to the file, relative to the working directory. If using roles this may look like "roles/cloudformation/files/cloudformation-example.json"`

Checking if this may be my ansible version bug.

**Comment by cooktheryan** [comment]
@Mangirdaz definitely an ansible versioning issue. We are using ansible-2.2.0-0.5.prerelease.el7.noarch from the ose-3.2 repo. This does bring up a good point though an Ansible version check should run to try to catch this before its too late.

If you have a RH login checkout https://access.redhat.com/articles/2623521

**Comment by Mangirdaz** [comment]
Confirmed. 

https://github.com/openshift/openshift-ansible-contrib/pull/26

This is the one I was reading. Just was playing with deploying Origin as no subscription at home :)
So managed now to deploy infra with centos, now infra left. 

P.S. are you fine to extend this to support origin or should I fork and start separate Branch? Having in mind how complex main Openshift playbook became. 


[mangis@mj Downloads]$ ansible --version
ansible 2.1.1.0

**Comment by cooktheryan** [comment]
Looking to be able to use the same script for origin as well.  Prepping for the 3.3 release I got pulled away in extended the origin support but shouldn't be too crazy as I had a prototype with ocp and origin on 3.2.

**Comment by cooktheryan** [comment]
@Mangirdaz I should be able to review that PR tomorrow. BTW it's definitely appreciated

**Comment by cooktheryan** [comment]
Merged
