### ISSUE TITLE
RepresenterError: cannot represent an object: claim

### ISSUE THREAD

**Issue by sensiblemedia** [openshift/openshift-ansible-contrib#255]
Hi Folks,
Having trouble installing openshift-enterprise reference on aws.
The first stage completes which deploys infrastructure the issue appears to be related to second stage openshift install.

Could really do with some help please!

**Playbook Command that is kicked off by ./ose-on-aws.py:**
ansible-playbook -i inventory/aws/hosts -e 'region=us-east-1     stack_name=dev     ami=ami-b63769a1     keypair=OSE-key     create_key=yes     add_node=no     key_path=/dev/null     create_vpc=yes     vpc_id=None     private_subnet_id1=None     private_subnet_id2=None     private_subnet_id3=None     public_subnet_id1=None     public_subnet_id2=None     public_subnet_id3=None     byo_bastion=no     bastion_sg=/dev/null     master_instance_type=m4.large     node_instance_type=t2.medium     app_instance_type=t2.medium     bastion_instance_type=t2.micro     public_hosted_zone=mydomain.net     wildcard_zone=apps.mydomain.net     console_port=443     deployment_type=openshift-enterprise     rhsm_user=******     rhsm_password=*******     rhsm_pool="60 Day Supported OpenShift Enterprise, 2 Cores Evaluation"     containerized=False     s3_bucket_name=dev-ocp-registry-mydomain     s3_username=dev-s3-openshift-user     github_client_id=c9f2xxxxxxx     github_client_secret=812xxxxx3     github_organization=["my-openshift"]' playbooks/openshift-install.yaml -v

**Ansible Version:**
[ec2-user@ip-172-31-57-251 aws-ansible]$ ansible --version
ansible 2.2.1.0
  config file = /home/ec2-user/git/openshift-ansible-contrib/reference-architecture/aws-ansible/ansible.cfg
  configured module search path = Default w/o overrides

**FAILS HERE:**
TASK [openshift_master : set_fact] *********************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_master/tasks/main.yml:151
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 443, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 427, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 383, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 583, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/usr/share/ansible_plugins/filter_plugins/openshift_master.py", line 500, in translate_idps
    return yaml.safe_dump([idp.to_dict() for idp in idp_list], default_flow_style=False)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: claim

Thanks
SRG

**Comment by sensiblemedia** [comment]
Apologies but does anyone have any ideas how to resolve the above so to enable Openshift to complete install?

Really stumped as to whats causing this.

**Comment by cooktheryan** [comment]
Are you using the rpm of openshift-ansible playbooks or cloning of the openshift-ansible git repo?

**Comment by sensiblemedia** [comment]
Thank you for replying.
I am following the Redhat doc for AWS reference deployment.
https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture
https://access.redhat.com/articles/2623521

It states to install the following of which successfully installed:
_$ rpm -q python-2.7
$ subscription-manager repos --enable rhel-7-server-optional-rpms
$ subscription-manager repos --enable rhel-7-server-ose-3.4-rpms
$ rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
$ yum -y install atomic-openshift-utils \
  python2-boto \
  python2-boto3 \
  pyOpenSSL \
  git \
  ansible \
  python-netaddr \
  python-click \
  python-httplib2_

The AWS reference deployment stand-ups the infrastructure it installs docker and openshift but the script fails with the below when executing the second stage of the ose-on-aws.py script.

_./ose-on-aws.py --stack-name=dev --create-key=yes --rhsm-user=****** --rhsm-password=****** --public-hosted-zone=mydomain.net --keypair=OSE-key --github-client-secret=8******3   --github-organization=mo-openshift --github-client-id=c9*****72d --rhsm-pool="60 Day Supported OpenShift Enterprise, 2 Cores Evaluation" --ami=ami-b63769a1_

The following is the ansible script found at bottom of previous mentioned document which allows one to execute openshift install on an already provisioned infrastructure both return the same error.
 
_ansible-playbook -i inventory/aws/hosts -e 'region=us-east-1 stack_name=dev keypair=OSE-key public_hosted_zone=****.net wildcard_zone=apps.****.net console_port=443 deployment_type=openshift-enterprise rhsm_user=**** rhsm_password=***** rhsm_pool="60 Day Supported OpenShift Enterprise, 2 Cores Evaluation" github_client_id=c****e github_client_secret=821*******73 github_organization=["mo-openshift"]'  playbooks/openshift-install.yaml_

**Error displayed without debugging (my first post contains the same error but with python debugging and verbose):**
TASK [openshift_master : Create session secrets file] **************************
changed: [ose-master03.mydomain.net]
changed: [ose-master02.mydomain.net]
changed: [ose-master01.mydomain.net]

TASK [openshift_master : set_fact] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: claim
fatal: [ose-master03.mydomain.net]: FAILED! => {
    "failed": true
}

MSG:

Unexpected failure during module execution.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: claim
fatal: [ose-master01.mydomain.net]: FAILED! => {
    "failed": true
}

MSG:

Unexpected failure during module execution.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: claim
fatal: [ose-master02.mydomain.net]: FAILED! => {
    "failed": true
}

MSG:

Unexpected failure during module execution.


NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=17   changed=4    unreachable=0    failed=0
ose-app-node01.mydomain.net : ok=56   changed=8    unreachable=0    failed=0
ose-app-node02.mydomain.net : ok=56   changed=8    unreachable=0    failed=0
ose-infra-node01.mydomain.net : ok=56   changed=8    unreachable=0    failed=0
ose-infra-node02.mydomain.net : ok=56   changed=8    unreachable=0    failed=0
ose-infra-node03.mydomain.net : ok=56   changed=8    unreachable=0    failed=0
ose-master01.mydomain.net : ok=228  changed=68   unreachable=0    failed=1
ose-master02.mydomain.net : ok=228  changed=68   unreachable=0    failed=1
ose-master03.mydomain.net : ok=250  changed=72   unreachable=0    failed=1

Thanks,
SRG

**Comment by sensiblemedia** [comment]
Forgot to mention that I cloned the openshift-ansible-contrib repro as per instructions in previous mentioned Redhat document:
 git clone https://github.com/openshift/openshift-ansible-contrib.git
-SRG

**Comment by cooktheryan** [comment]
Yes that's correct.

Can you provide the following from the host performing the deployment?

rpm -qa | grep openshift

**Comment by sensiblemedia** [comment]
Here is the output of rpm cooktheryan,

# rpm -qa | grep openshift
atomic-openshift-clients-3.4.1.2-1.git.0.d760092.el7.x86_64
atomic-openshift-master-3.4.1.2-1.git.0.d760092.el7.x86_64
atomic-openshift-3.4.1.2-1.git.0.d760092.el7.x86_64

BTW I just noticed that the github org oauth settings may have been incorrect it appears that I set up the application under my primary account as opposed to under the new org account.
I have just set up the application under this new org account and am re-running the ansible script as we speak. Could this issue be related to oauth?

Thanks,
SRG

**Comment by cooktheryan** [comment]
Shouldn't be but you are one step ahead of me with running the script
again.  The rpms you listed they are the newest available from yum correct?

**Comment by sensiblemedia** [comment]
As far as I am aware the latest openshift is 3.4 so they look to be latest.

BTW install just failed again with same issue.
'The error was: RepresenterError: cannot represent an object: claim'

**Comment by cooktheryan** [comment]
One option could be in the system running ose-on-aws could be to downgrade the playbooks and roles. @detiber any thoughts?

**Comment by sensiblemedia** [comment]
@cooktheryan 
Sorry I just realised I was logged on to one of the master nodes when I executed the rpm -qa openshift command.

Here is the output from the server the build is being driven from:
$ rpm -qa | grep openshift
openshift-ansible-docs-3.4.56-1.git.0.7ba9968.el7.noarch
openshift-ansible-playbooks-3.4.56-1.git.0.7ba9968.el7.noarch
openshift-ansible-3.4.56-1.git.0.7ba9968.el7.noarch
openshift-ansible-callback-plugins-3.4.56-1.git.0.7ba9968.el7.noarch
openshift-ansible-roles-3.4.56-1.git.0.7ba9968.el7.noarch
atomic-openshift-utils-3.4.56-1.git.0.7ba9968.el7.noarch
openshift-ansible-lookup-plugins-3.4.56-1.git.0.7ba9968.el7.noarch
openshift-ansible-filter-plugins-3.4.56-1.git.0.7ba9968.el7.noarch

**Comment by cooktheryan** [comment]
If the installation is failing I would suggest downgrading the rpms above
and then run ose-on-aws.

This will be my last opportunity to reply today as im boarding a flight.

**Comment by sensiblemedia** [comment]
Thanks for your help today and have a safe journey.

This issue also occurred with Openshift v3.3, I upgraded to 3.4 when I noticed the latest Redhat Install doc earlier today but same issue persists.

SRG

**Comment by cooktheryan** [comment]
Very strange might be worth opening an issue in the openshift-ansible git
repo as its what the rpms are based off of.

**Comment by sensiblemedia** [comment]
FYI, Found the following reference to 'claim' which is related to oauth and github, wonder if it is indeed related to github?
git/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/openshift-setup.yaml

      _openshift_master_identity_providers:
    - name: github
      kind: GitHubIdentityProvider
      login: true
      challenge: false
      mapping_method: claim
      clientID: "{{ github_client_id }}"
      clientSecret: "{{ github_client_secret }}"
      organizations: "{{ github_organization }}"_

**Comment by detiber** [comment]
@sensiblemedia what version of Ansible are you using? We've been running into issues with version 2.2.1. I'd suggest downgrading to 2.2.0 if so.

On a side note, we are working on pushing out a 2.2.1 release with the fix in the OpenShift repos and Ansible is working on the 2.2.2 release that also includes the fix.

**Comment by sensiblemedia** [comment]
Thanks for the info @detiber 

The version I am running is indeed ansible 2.2.1.0 will try as you suggest a downgrade to 2.2.0.

Thanks
SRG

**Comment by sensiblemedia** [comment]
@detiber 

'reference-architecture/aws-ansible/playbooks/node-setup.yaml' appears to be hardcoded is this intentional or a mistake?

```
    openshift_master_identity_providers:
    - name: github
      kind: GitHubIdentityProvider
      login: true
      challenge: false
      mapping_method: claim
      clientID: e76865557b0417387b35
      clientSecret: 72b36e28221c1b93089ecf72f1a19963a8532b06
      organizations:
      - openshift
```

Should this actually hold vars?
```
clientID: "{{ github_client_id }}"
clientSecret: "{{ github_client_secret }}"
organizations: "{{ github_organization }}"
```

**Comment by detiber** [comment]
@sensiblemedia that variable shouldn't be needed for that playbook, it's used for adding additional nodes to a cluster and shouldn't be changing the auth config.  openshift_setup.yaml is the playbook invoked during the install of the cluster

**Comment by sensiblemedia** [comment]
@detiber Thanks for clarifying.

**Comment by sensiblemedia** [comment]
Thanks again for your help.

@detiber you were right on the money.

**Solution:**
Uninstalled Ansible 2.2.1 and installed Ansible 2.2.0, Openshift deployment succeeded without a hitch.

Redhat really need to improve the quality of their docs the one provided at https://access.redhat.com/sites/default/files/attachments/ocp-on-aws-8.pdf has a number of errors one such error is on the last page the last ansible command is missing the playbook.
It looks as though it never made it from ocp-on-aws-7.pdf which does have the correct command.

**Comment by detiber** [comment]
@cooktheryan ^ see the note above about the docs.

@sensiblemedia Thanks for the feedback and apologies about the issues with Ansible 2.2.1. We are working on improving our testing/response to issues like that so that we can avoid it happening again in the future.

**Comment by goern** [comment]
@sensiblemedia  where did you get ansible 2.2.0.0 ? in EPEL7 I just see a 2.2.1.0 rpm...

**Comment by cooktheryan** [comment]
If you arent on a rhel system where you can use the one provided by the
openshift repos. You could always install with pip

**Comment by cooktheryan** [comment]
@sensiblemedia feel free to reach out to me at rcook@redhat.com I would love to work with you on implementing any feedback.

**Comment by cooktheryan** [comment]
@sensiblemedia the document is in the process of being updated and the add node playbooks have been updated. Feel free to re-open if you hit the issue again or if you run into anything else
