### ISSUE TITLE
Directory generated_certs missing from 2 of 3 masters

### ISSUE THREAD

**Issue by tahonen** [openshift/openshift-ansible-contrib#257]
Trying to install OCP on AWS with ansible 2.2.0 and installation stopped on following error on all masters
```
fatal: [ose-master03.xxxxxx -> ose-master01.xxxxx]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to ose-master01.xxxxxx closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_X6JQjb/ansible_module_delegated_serial_command.py\", line 274, in <module>\r\n    main()\r\n  File \"/tmp/ansible_X6JQjb/ansible_module_delegated_serial_command.py\", line 204, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/etc/etcd/generated_certs/etcd-ip-xx-xx-x-xxeu-west-1.compute.internal'\r\n"
```
Directory /etc/etcd/generated_certs/ was only present on ose-master03 and that directory contained etcd and openshift certs for all hosts.

Same thing for ca.serial.txt file. It was present only in host ose-master03.

Managed to solve issue by manually copying file from 03 to 02 and 01 and restarting installation.

**Comment by detiber** [comment]
@cooktheryan this is a bit odd...  It seems like oo_first_master is being evaluated differently at some point, causing this.

**Comment by cooktheryan** [comment]
Any thoughts on if we removing the designation of primary master in our
instance groups and letting the installer figure it out on its own?

**Comment by detiber** [comment]
@cooktheryan that should work, All the installer should be doing is taking the first host in the masters group and adding it to the oo_first_masters group.

**Comment by cooktheryan** [comment]
Ill pr that once I get back

**Comment by cooktheryan** [comment]
@tahonen an inventory fix has been merged. Let me know if it helps resolve the issue

**Comment by cooktheryan** [comment]
Im going to close this based off the results of the automated testing here 
https://github.com/openshift/openshift-ansible-contrib/pull/259

If you see the issue again @tahonen feel free to re-open
