### ISSUE TITLE
Install failed with ssh error

### ISSUE THREAD

**Issue by Mangirdaz** [openshift/openshift-ansible-contrib#27]
Maybe more question than a issue. 

After provisioning infrastructure I got all infrastructure deployed with security groups, EC2 instances, etc.

 As per reference architecture `bastion` is ONLY ssh entry point to the platform. But we are running ansible from outside AWS, so access to master hosts is not permitted by security group to build openshift itself. 

Action failing: 
```
- hosts: cluster_hosts
  gather_facts: yes 
  become: yes
  serial: 1
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - rhsm-subscription
```

Error simple, no ssh possible. 
```
PLAY [bastion] *****************************************************************

TASK [host-up : check to see if host is available] *****************************
ok: [bastion.bgol.lt] => {"changed": false, "elapsed": 20, "path": null, "port": 22, "search_regex": null, "state": "started"}

PLAY [cluster_hosts] ***********************************************************

TASK [setup] *******************************************************************
fatal: [ose-master01.bgol.lt]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

PLAY RECAP *********************************************************************
bastion.bgol.lt            : ok=1    changed=0    unreachable=0    failed=0   
localhost                  : ok=5    changed=5    unreachable=0    failed=0   
ose-master01.bgol.lt       : ok=0    changed=0    unreachable=1    failed=0   
```

Does this mean we cant build infrastructure using external ansible master? OR i'm missing something?

**Comment by cooktheryan** [comment]
Need to update readme to resolve this. Gist of what you will need to do supplying the location of your ssh key and domain

`Host bastion
     Hostname                 bastion.rcook-aws.sysdeseng.com
     user                       ec2-user 
     StrictHostKeyChecking      no
     ProxyCommand               none
     CheckHostIP                no
     ForwardAgent               yes
     IdentityFile               /home/rcook/.ssh/id_rsa

Host *.rcook-aws.sysdeseng.com
     ProxyCommand               ssh ec2-user@bastion -W %h:%p
     user                       ec2-user
     IdentityFile               /home/rcook/.ssh/id_rsa
`

**Comment by Mangirdaz** [comment]
Dam.... You own me 16$ for my delete,create, delete, create (this is how much AWS charged me :D )  trying to understand what I'm missing :)  Thanks... back to code....

**Comment by cooktheryan** [comment]
@Mangirdaz I checked out the readme the bastion config is there..Its just down in the aws-ansible readme

Threw this together today. Should be a PR to the main repo in a day or two just need to do more testing and a README update https://github.com/cooktheryan/openshift-ansible-contrib/tree/centos
