### ISSUE TITLE
How to specify number of application nodes and types in aws-ansible for the reference architecture?

### ISSUE THREAD

**Issue by gihad** [openshift/openshift-ansible-contrib#276]
Hey,

The default of 2 application nodes is insufficient for my deployment of the reference architecture. Is it possible to specify a different number? Also there doens't seem to be an option to choose the instance types for the masters, infra and application nodes.

I'm looking at this docs: https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible

**Comment by cooktheryan** [comment]
The easiest solution without modifying the cloud formation is to run the
add_node.py once the environment is deployed. The add node playbook will
allow you to add a node at a time.

**Comment by gihad** [comment]
Thanks, for the other part of my question I now see that the instance types are parameters to ose-on-aws.py https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/aws-ansible/ose-on-aws.py#L89
