### ISSUE TITLE
AWS Multiple cluster install fails possibly due to bastion hostname?

### ISSUE THREAD

**Issue by sensiblemedia** [openshift/openshift-ansible-contrib#281]
Hi Folks,

I attempted to execute a multiple cluster Openshift install with the same region on AWS.
The first cluster install works fine, however the second cluster install fails.
The Cloudformation functions as designed and route53 DNS entries are configured however the second part of install and configuration (Openshift) fails when it is necessary to ssh via the bastion host.

The reason for this is that the install employs the short ssh proxy name bastion no matter what the stack name identity used. This name (bastion) matches the host entry in .ssh/config which itself redirect to the first clusters bastion host which then attempts to install on hosts that are not available in its VPC so it fails.

So the work around is to edit the .ssh/config and point Host bastion to the second bastion server. However this is not ideal.

Should we not have an option to provide bastion name or even append the unique stack name so bastion becomes bastion-<stackname> this way we can employ multiple Host entries in .ssh/config?
(ssh ec2-user@bastion we could use ssh ec2-user@bastion-<stackname>)

Could the other option be to not use the abbreviated name at all but rather the bastion's fully qualified name in the Ansible install scripts? 

Having said this please feel free to correct me if I am doing this wrong or there is a more favourable option available. 

Example of .ssh/config employing unique bastions:

`Host bastion
  Hostname bastion.domain.net
  user ec2-user
  StrictHostKeyChecking no
  ProxyCommand none
  CheckHostIP no
  ForwardAgent yes
  IdentityFile /home/ec2-user/.ssh/id_rsa
Host *.domain.net
  ProxyCommand ssh ec2-user@bastion -W %h:%p
  user ec2-user
  IdentityFile /home/ec2-user/.ssh/id_rsa

Host bastion-dev
  Hostname bastion.dev.domain.net
  user ec2-user
  StrictHostKeyChecking no
  ProxyCommand none
  CheckHostIP no
  ForwardAgent yes
  IdentityFile /home/ec2-user/.ssh/id_rsa
Host *.dev.domain.net
  ProxyCommand ssh ec2-user@bastion-dev -W %h:%p
  user ec2-user
  IdentityFile /home/ec2-user/.ssh/id_rsa
`

Thanks,
SRG

**Comment by cooktheryan** [comment]
Did you use greenfield or brownfield?

**Comment by sensiblemedia** [comment]
Hey Ryan,
Both were greenfield, both had unique stack-name and public-hosted-zone.

**Comment by cooktheryan** [comment]
It's an interesting situation. The way we currently handle the bastion host its access is tied directly to security groups. I wonder if the brownfield deployment may be more fitting but it would depend if you would want a vpc per openshift env or not.

**Comment by sensiblemedia** [comment]
@cooktheryan thanks for update Ryan.

FYI, the documentation appears to state that multiple greenfield and brownfield implementations can coexist as long as stack name and public hosted name are unique. the Cloudformation component works as expected after adding a new sub domain to route53 but the Ansible Openshift install fails because it appears that the name 'bastion' is hard-coded this resolves to the previously configured .ssh/config Host directive that points to the first cluster and as such causes Ansible SSH to fail forwarding requests to the correct cluster.

What would be nice would be to have multiple bastion .ssh/config Host directive so that one can employ a single build server.

The alternative's:

- Create a build server for each OSE cluster
- Create a unique user for each OSE cluster on the build server with unique and specific bastion host directive within .ssh/config 
- Edit .ssh/config changing Hostname directive to point to working OSE cluster bastion host. Not ideal for enterprise use, could cause confusion with risk of mistakes or unintended results.   
- Use the original / first bastion server employing --byo-bastion and --bastion-sg to ose-on-aws.py, this however could be prohibitive if OSE cluster isolation is a requirement for the design along with the possibility of complexity when employing multi AWS zone installs.
- Add functionality to OSE Ansible to allow one to either supply a unique bastion name or to auto configure the bastion name to be appended with the unique stack name, for example, bastion-prod, bastion-dev and so on. This I think would be the preferred option, wish my python coding skill were better, I come from a unix and perl background ;-)

**Documentation:** 
https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/aws-ansible/README.md
### **Multiple OpenShift deployments**
The same greenfield and brownfield deployment steps can be used to launch another instance of the reference architecture environment. When launching a new environment ensure that the variable stack-name is changed. If the variable is not changed the currently deployed environment may be changed.

**OpenShift Container Platform**
./ose-on-aws.py --rhsm-user=rh-user --public-hosted-zone=rcook-aws.sysdeseng.com --keypair=OSE-key \
--rhsm-pool="Red Hat OpenShift Container Platform, Standard, 2-Core" --keypair=OSE-key --rhsm-password=password \
--stack-name=prod --github-client-secret=47a0c41f0295b451834675ed78aecfb7876905f9 --github-organization=openshift \
--github-organization=RHSyseng --github-client-id=3a30415d84720ad14abc

**OpenShift Origin**
./ose-on-aws.py --keypair=OSE-key --public-hosted-zone=sysdeseng.com --deployment-type=origin --ami=ami-6d1c2007 \
--stack-name=prod --github-client-secret=47a0c41f0295b451834675ed78aecfb7876905f9 --github-organization=openshift \
--github-organization=RHSyseng --github-client-id=3a30415d84720ad14abc

Kind Regards,
SRG

**Comment by sensiblemedia** [comment]
OK I may have resolved the issues with multiple bastion hosts but along the way have noticed a potential flaw or issue with Openshift Ansible and Route53.

Firstly to enable the name bastion-<stack name> I amended the following in ../aws-ansible/playbooks/roles/instance-groups/tasks/main.yml

**From:**
groups: bastion
**To:**
groups: "bastion-{{ stack_name }}

This allowed me to set multiple Host directives in .ssh/config which appear to resolve to correct bastion hosts. However a potential more alarming issue was experienced with regards to intermittent DNS resolution unrelated to the above changes.

When we initialize a greenfield install there is a requirement to have an AWS hosted zone setup within Route53.
So lets say we have executed a successful initial install with a stack name of prod which employs the Route53 Hosted Zone of domain.com.
domain.com is externally managed (GoDaddy) so we take the four DNS nameservers provided by Route53 and add them to Godaddy.
After some time everything appears to work.

Now we wish to add another OSE cluster lets call this dev and we wish to use a subdomain of domain.com called dev.domain.com. We create a new Route53 Hosted Zone called dev.domain.com note a hosted zone is a prereq of installing Openshift on AWS as it will complain that one does not exist. 
The hosted domain matches --public-hosted-zone provided to ose-on-aws.py.

Here's were this problem starts to show. AWS Route53 creates another four NS servers so we take these newly created NS servers and add them to GoDaddy we know have a total of eight NS servers listed at GoDaddy. Four for the prod stack and four for the dev stack.

Problem experienced is that the dev.domain.com intermittently resolves while other times fails.
I believe this is due to non consistent and mixed AWS NS servers provided to GoDaddy, ie four resolve domain.com while four resolve dev.domain.net and that maybe domain.com NS servers take precedent and return *.dev.domain.com not found. 

Idea for fix:
When configuring Route53, OSE Ansible should use route of domain (domain.com) for Route53 Hosted Zone.

So we would have something like the following in Route53:

domain.com : type NS : nameservers x 4
domian.com : type SOA : ns .... timings
bastion.domain.com : type A : IP
bastion.dev.domain.com : type A : IP
ose-master01.domain.com : type A : IP
ose-master01.dev.domain.com : type A : IP

Then we just need to add four NS servers per domain which will all be consistent in this case to GoDaddy.

Please feel free to correct me if I am going about all this the wrong way or have missed a trick.
Hope this all makes sense as was tight for time when writing.

Cheers,
SRG

**Comment by cooktheryan** [comment]
Let me review this in the morning. Hopefully we can work out a good solution based on your info above.

**Comment by jstuever** [comment]
I have a project where we spawn OpenShift clusters "on demand", and we use a single zone just as you explained. Works well for us.

**Comment by sensiblemedia** [comment]
Sorry for the delay in replying, thanks for the info.
So I have been working on this and this is what I have at this point in time.
I am able to create multiple stacks in the same region that uses root domain (domain.com) under Route53.
So entries for dev.domain.com, prod.domain.com, xyz.domain.com appear under the same route53 hosted zone of domain.com.

@cooktheryan I forked and made changes to your branch after you applied the atomic host fix we discussed in #289 

Now I confess I am not entirely sure of what ramifications these changes may have on other functionality such as BYO bastion etc but it seems to have done the trick for our purposes. 

Part of this change was to add --route53-hosted-rootzone option to ose-on-aws.py if not supplied route53-hosted-rootzone takes on --public-hosted-zone setting.

**Command to set up prod stack**
`
./ose-on-aws.py --stack-name=prod --rhsm-user=user* --rhsm-password=**** --public-hosted-zone=domain.net --keypair=OSE-key --github-client-secret=dd****55  --github-organization=openshift --github-organization=my-openshift --github-client-id=5****6 --rhsm-pool="60 Day Supported OpenShift Enterprise, 2 Cores Evaluation" --ami=ami-dbb45dcd --containerized=true --route53-hosted-rootzone=domain.net`

**Command to set up dev stack:**
`./ose-on-aws.py --stack-name=dev --rhsm-user=user* --rhsm-password=**** --public-hosted-zone=dev.domain.net --keypair=OSE-key --github-client-secret=dd****42  --github-organization=openshift --github-organization=my-openshift --github-client-id=7****1 --rhsm-pool="60 Day Supported OpenShift Enterprise, 2 Cores Evaluation" --ami=ami-dbb45dcd --containerized=true --route53-hosted-rootzone=domain.net`

Added the stack-name to bastion group groups: "bastion.{{ stack_name }}" to allow connectivity employing multiple short Host names in .ssh/config 

**.ssh/config look like this now:**

```
Host bastion-dev
  Hostname bastion.dev.domain.net
  user ec2-user
  StrictHostKeyChecking no
  ProxyCommand none
  CheckHostIP no
  ForwardAgent yes
  IdentityFile /home/ec2-user/.ssh/id_rsa
Host *.dev.wookungfu.net
  ProxyCommand ssh ec2-user@bastion-dev -W %h:%p
  user ec2-user
  IdentityFile /home/ec2-user/.ssh/id_rsa

Host bastion-prod
  Hostname bastion.domain.net
  user ec2-user
  StrictHostKeyChecking no
  ProxyCommand none
  CheckHostIP no
  ForwardAgent yes
  IdentityFile /home/ec2-user/.ssh/id_rsa
Host *.wookungfu.net
  ProxyCommand ssh ec2-user@bastion-prod -W %h:%p
  user ec2-user
  IdentityFile /home/ec2-user/.ssh/id_rsa
```

**Route53 records for domain.net:** 
```
$ aws route53 list-resource-record-sets --hosted-zone-id ****FS | grep RESOURCERECORDSETS

RESOURCERECORDSETS    domain.net.    172800    NS
RESOURCERECORDSETS    domain.net.    900    SOA
RESOURCERECORDSETS    \052.apps.domain.net.        A
RESOURCERECORDSETS    bastion.domain.net.    300    A
RESOURCERECORDSETS    \052.apps.dev.domain.net.        A
RESOURCERECORDSETS    bastion.dev.domain.net.    300    A
RESOURCERECORDSETS    internal-openshift-master.dev.domain.net.        A
RESOURCERECORDSETS    openshift-master.dev.domain.net.        A
RESOURCERECORDSETS    ose-app-node01.dev.domain.net.    300    A
RESOURCERECORDSETS    ose-app-node02.dev.domain.net.    300    A
RESOURCERECORDSETS    ose-infra-node01.dev.domain.net.    300    A
RESOURCERECORDSETS    ose-infra-node02.dev.domain.net.    300    A
RESOURCERECORDSETS    ose-infra-node03.dev.domain.net.    300    A
RESOURCERECORDSETS    ose-master01.dev.domain.net.    300    A
RESOURCERECORDSETS    ose-master02.dev.domain.net.    300    A
RESOURCERECORDSETS    ose-master03.dev.domain.net.    300    A
RESOURCERECORDSETS    internal-openshift-master.domain.net.        A
RESOURCERECORDSETS    openshift-master.domain.net.        A
RESOURCERECORDSETS    ose-app-node01.domain.net.    300    A
RESOURCERECORDSETS    ose-app-node02.domain.net.    300    A
RESOURCERECORDSETS    ose-infra-node01.domain.net.    300    A
RESOURCERECORDSETS    ose-infra-node02.domain.net.    300    A
RESOURCERECORDSETS    ose-infra-node03.domain.net.    300    A
RESOURCERECORDSETS    ose-master01.domain.net.    300    A
RESOURCERECORDSETS    ose-master02.domain.net.    300    A
RESOURCERECORDSETS    ose-master03.domain.net.    300    As
```

Please feel free to advise and comment:
https://github.com/sensiblemedia/openshift-ansible-contrib

**Comment by cooktheryan** [comment]
Does prod and dev deploy to the same vpc?

Just trying to think about all of the cases in which a bastion may want to be used but not being in the same VPC. I think if we ensure that the bastion is in the same VPC we should be good to go.

**Comment by sensiblemedia** [comment]
@cooktheryan This scenario is to satisfy the requirement to manage isolated and sandbox clusters.
In this case prod and dev are in their own unique vpc's
From a security point of view there may be the requirement to have isolated bastion hosts that are associated to their respective isolated clusters and vpc's so that in the event that a single bastion server becomes compromised the risk is limited to its associated cluster only.

Note: The current code changes introduced in my previous post currently breaks add_node.py since I have not introduced changes to this component at this time.
