### ISSUE TITLE
AWS CloudFormation Update does not recreate/update Route53 DNS entries

### ISSUE THREAD

**Issue by sensiblemedia** [openshift/openshift-ansible-contrib#294]
Hi Folks,

Initial deploy was using ami-10f53a06 (Centos Atomic) 
deployment-type=origin 
stack name=prod
Cloudformation completed but the Origin install failed.

Decided to attempt a migration to RH Openshift Container Platform employing Atomic hosts using same AWS stack (prod).
The cloudformation update succeeded, bringing up new instances employing the golden atomic host ami-dbb45dcd and then downing the previous hosts but the Route53 entries do not get updated with the new instance IP's they continue to point to the original now downed instances.

Expected Behaviour would have been to see Route53 update with the newly replaced instance IP addresses.

The outcome of the current install runtime is that once the Cloudformation update has succeeded connectivity to bastion fails since its Route53 entry still points to the old entry. 
The same can be said for all A records for newly created nodes / instances.

Cheers,
SRG

**Comment by sensiblemedia** [comment]
Correction:
This issue appears to relate to the bastion host route53 IP only and not the route53 entries of the newly created cluster instances.

I think the issue I saw on the cluster hosts was due to not clearing the ssh known_hosts entries.

**Comment by cooktheryan** [comment]
hopefully that is all the issue is but definitely a hard thing to resolve automatically

**Comment by sensiblemedia** [comment]
Hopefully Ryan.
I manually changed the Route53 entry for the bastion host and was under the impression that the other node instance A records had not updated but on revisiting they had. Could have been an update delay I will need to clarify when I have a little more time.

**Comment by sensiblemedia** [comment]
I need to revisit this to confirm but suspect this is no longer applicable.
Closing case but will re-open if repeatable.
