### ISSUE TITLE
AWS ELBs idle timeout too short

### ISSUE THREAD

**Issue by zuaresc** [openshift/openshift-ansible-contrib#301]
The CloudFormation infrastructure defaults to 60 seconds for the ELB idle timeout. This causes disconnects when using `oc port-forward` and `oc rsh`. Please consider increasing the default idle timeout to something higher (maximum 3600 seconds) and perhaps include documentation regarding it.

**Comment by cooktheryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OpenShift-Ansible-Contrib issues and PRs](https://trello.com/c/v2PKoPrN/725-openshift-ansible-contrib-issues-and-prs)

**Comment by zuaresc** [comment]
Thanks! However, it looks like a quote is missing on the right of each "IdleTimeout:" key.

**Comment by cooktheryan** [comment]
The change was picked up in later commits. Should be good to go once its merged.
