### ISSUE TITLE
gce-cli: Issue creating DNS Zone

### ISSUE THREAD

**Issue by nicks451** [openshift/openshift-ansible-contrib#308]
I'm getting an issue when running the gcloud.sh script when Ansible is creating the dns zone.

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'Provider' is not defined
> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/87/x4dq4vlx61j1v7zv5pk4tqch0000gn/T/ansible_sBRT8B/ansible_module_gcdns_zone.py\", line 148, in <module>\n    PROVIDER = Provider.GOOGLE\nNameError: name 'Provider' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE"}

**Comment by pschiffe** [comment]
What ansible version are you using? Could you try with -vvvv options?
```
cd openshift-ansible-contrib/reference-architecture/gce-cli/ansible/
ansible-playbook -vvvv -i inventory/inventory playbooks/local.yaml
```

**Comment by nicks451** [comment]
I'm using ansible 2.2.0

The output with -vvv is

> Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/extras/cloud/google/gcdns_zone.py
> <localhost> ESTABLISH LOCAL CONNECTION FOR USER: nick
> <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1491404535.9-61727176037289 `" && echo ansible-tmp-1491404535.9-61727176037289="` echo $HOME/.ansible/tmp/ansible-tmp-1491404535.9-61727176037289 `" ) && sleep 0'
> <localhost> PUT /var/folders/87/x4dq4vlx61j1v7zv5pk4tqch0000gn/T/tmp5gmJqA TO /Users/nick/.ansible/tmp/ansible-tmp-1491404535.9-61727176037289/gcdns_zone.py
> <localhost> EXEC /bin/sh -c 'chmod u+x /Users/nick/.ansible/tmp/ansible-tmp-1491404535.9-61727176037289/ /Users/nick/.ansible/tmp/ansible-tmp-1491404535.9-61727176037289/gcdns_zone.py && sleep 0'
> <localhost> EXEC /bin/sh -c '/usr/bin/python /Users/nick/.ansible/tmp/ansible-tmp-1491404535.9-61727176037289/gcdns_zone.py; rm -rf "/Users/nick/.ansible/tmp/ansible-tmp-1491404535.9-61727176037289/" > /dev/null 2>&1 && sleep 0'
> An exception occurred during task execution. The full traceback is:
> Traceback (most recent call last):
>   File "/var/folders/87/x4dq4vlx61j1v7zv5pk4tqch0000gn/T/ansible_6qvEcS/ansible_module_gcdns_zone.py", line 148, in <module>
>     PROVIDER = Provider.GOOGLE
> NameError: name 'Provider' is not defined
> 
> fatal: [localhost]: FAILED! => {
>     "changed": false,
>     "failed": true,
>     "invocation": {
>         "module_name": "gcdns_zone"
>     },
>     "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/87/x4dq4vlx61j1v7zv5pk4tqch0000gn/T/ansible_6qvEcS/ansible_module_gcdns_zone.py\", line 148, in <module>\n    PROVIDER = Provider.GOOGLE\nNameError: name 'Provider' is not defined\n",
>     "module_stdout": "",
>     "msg": "MODULE FAILURE"
> }

**Comment by edseymour** [comment]
I've replicated this issue on two different servers
1) Fedora 25 which installed ansible via EPEL
2) A subscribed RHEL 7.3, which installed ansible 2.2.1.0 via the rhel-7-server-ose-3.4-rpms repo

**Comment by pschiffe** [comment]
So, I still can reproduce this issue. Could you please update ansible to the latest available version for your OS (`yum upgrade ansible`). For Fedora 25, it's currently `ansible-2.2.2.0-1.fc25.noarch`. Also, please provide the name of the task which is failing, or the complete output of the `ansible -vvvv` (4x `-v` is max verbosity). Thanks.

**Comment by edseymour** [comment]
(Using the 'master' branch)
Fedora25, Ansible Version     : 2.2.2.0, Release     : 1.fc25

The command I used was `ansible-playbook -vvvv -i inventory/inventory playbooks/prereq.yaml` as the `local.yaml` does not exist in the master branch. 

```
TASK [dns-zone : create dns zone] **********************************************
task path: /home/eseymour/code/ocp-on-gcp/openshift-ansible-contrib/reference-architecture/gce-cli/ansible/playbooks/roles/dns-zone/tasks/main.yaml:2
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/cloud/google/gcdns_zone.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: eseymour
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/eseymour/.ansible/tmp/ansible-tmp-1491917315.11-189052557491307 `" && echo ansible-tmp-1491917315.11-189052557491307="` echo /home/eseymour/.ansible/tmp/ansible-tmp-1491917315.11-189052557491307 `" ) && sleep 0'
<localhost> PUT /tmp/tmpzV7Qfj TO /home/eseymour/.ansible/tmp/ansible-tmp-1491917315.11-189052557491307/gcdns_zone.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/eseymour/.ansible/tmp/ansible-tmp-1491917315.11-189052557491307/ /home/eseymour/.ansible/tmp/ansible-tmp-1491917315.11-189052557491307/gcdns_zone.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/eseymour/.ansible/tmp/ansible-tmp-1491917315.11-189052557491307/gcdns_zone.py; rm -rf "/home/eseymour/.ansible/tmp/ansible-tmp-1491917315.11-189052557491307/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_TRz05i/ansible_module_gcdns_zone.py", line 148, in <module>
    PROVIDER = Provider.GOOGLE
NameError: name 'Provider' is not defined

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "gcdns_zone"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TRz05i/ansible_module_gcdns_zone.py\", line 148, in <module>\n    PROVIDER = Provider.GOOGLE\nNameError: name 'Provider' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

**Comment by pschiffe** [comment]
OK, so it seems you are missing the `python-libcloud` package. Could you install it and try again? Also, please update the master branch of this repo, we've just pushed some fixes to the gcp ref. arch. Thanks.

**Comment by edseymour** [comment]
@pschiffe thanks - that was causing the above issue... I do now get an error regarding a secrets file.

Will rebase and check again

`ansible-playbook -vvvv -i inventory/inventory playbooks/prereq.yaml`

```
TASK [dns-zone : create dns zone] **********************************************
task path: /home/eseymour/code/ocp-on-gcp/openshift-ansible-contrib/reference-architecture/gce-cli/ansible/playbooks/roles/dns-zone/tasks/main.yaml:2
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/cloud/google/gcdns_zone.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: eseymour
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/eseymour/.ansible/tmp/ansible-tmp-1491918922.15-200133218822153 `" && echo ansible-tmp-1491918922.15-200133218822153="` echo /home/eseymour/.ansible/tmp/ansible-tmp-1491918922.15-200133218822153 `" ) && sleep 0'
<localhost> PUT /tmp/tmppq_Vc_ TO /home/eseymour/.ansible/tmp/ansible-tmp-1491918922.15-200133218822153/gcdns_zone.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/eseymour/.ansible/tmp/ansible-tmp-1491918922.15-200133218822153/ /home/eseymour/.ansible/tmp/ansible-tmp-1491918922.15-200133218822153/gcdns_zone.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/eseymour/.ansible/tmp/ansible-tmp-1491918922.15-200133218822153/gcdns_zone.py; rm -rf "/home/eseymour/.ansible/tmp/ansible-tmp-1491918922.15-200133218822153/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "credentials_file": null, 
            "description": "openshift.red domain", 
            "pem_file": null, 
            "project_id": null, 
            "service_account_email": null, 
            "state": "present", 
            "zone": "openshift.red"
        }, 
        "module_name": "gcdns_zone"
    }, 
    "msg": "Missing GCE connection parameters in libcloud secrets file."
}
```

**Comment by pschiffe** [comment]
@edseymour check `project.json` and `secrets.py` files in `openshift-ansible-contrib/reference-architecture/gce-cli/ansible/inventory/gce/hosts/`. It's possible that the files are invalid as they were created without the `python-libcloud` package. Just delete them and try again.

**Comment by edseymour** [comment]
@pschiffe yup, that was it - running `./gcloud.sh` sorted that issue, I "just" have to configure the NS servers now - but that's my problem!

**Comment by pschiffe** [comment]
@nicks451 were you able to resolve your issue?

**Comment by pschiffe** [comment]
Closing, feel free to reopen if problem persists.
