### ISSUE TITLE
Split cluster?  Missing nodes when restarting AWS Instances (oc get nodes)

### ISSUE THREAD

**Issue by sensiblemedia** [openshift/openshift-ansible-contrib#327]
Hi,
While testing Openshift Origin deployment on AWS we shutdown cluster at night and restart in the morning so as to save costs etc.

While doing so I have noticed that 'oc get nodes' does not always show all nodes in the cluster.
Restarting instances does bring them back online but it seems a bit hit and miss.

I have created AWS resource groups and tagged nodes as dev-master, dev-infra and dev-app.
I have tried staggering the start up starting with masters -> infra -> app nodes but still oc get nodes does not always display all nodes that belong to cluster.

Q1) How should one startup the cluster?
Q2) How does one stop and start Openshift cluster without restarting AWS instances? (oc cluster command does not function see below)
Q3) What task should be carried out to stop a cluster in preparation for AWS instance shutdowns?

Attempted to use but receive an error that it cannot communicate with Docker:
$ oc cluster down
error: cannot communicate with Docker

Thanks,
SRG

**Comment by sensiblemedia** [comment]
Further info..

Logged on to ose-master01:
$ hostname
ip-10-20-4-17.eu-west-1.compute.internal

```
$ oc get nodes     (only shows 5/8 nodes)
NAME                                        STATUS    AGE
ip-10-20-4-138.eu-west-1.compute.internal   Ready     2h
ip-10-20-5-164.eu-west-1.compute.internal   Ready     2h
ip-10-20-5-91.eu-west-1.compute.internal    Ready     2d
ip-10-20-6-120.eu-west-1.compute.internal   Ready     2d
ip-10-20-6-151.eu-west-1.compute.internal   Ready     2h
```
As can be seen above ose-master01 is not listed along with an infra and app node.

Tried the following but the node does not join the Openshift cluster:
*Started individually restarting openshift services with systemctl
*Restarted docker with `sudo systemctl restart docker.service`
*Rebooted instance.
*Checked Route53 IP mapping details which appears to be correct.

/var/log/messages
```
Apr 24 15:50:18 ip-10-20-4-17 origin-master-api: I0424 15:50:18.412181       1 logs.go:41] http: TLS handshake error from 10.20.5.100:56887: EOF
....
Apr 24 15:53:54 ip-10-20-4-17 origin-node: I0424 15:53:54.477471   20154 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Apr 24 15:53:54 ip-10-20-4-17 journal: I0424 15:53:54.477471   20154 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Apr 24 15:53:54 ip-10-20-4-17 origin-node: E0424 15:53:54.492270   20154 eviction_manager.go:162] eviction manager: unexpected err: failed GetNode: node 'ip-10-20-4-17.eu-west-1.compute.internal' not found
....
Apr 24 15:50:20 ip-10-20-4-17 origin-node: E0424 15:50:20.351727   20154 thin_pool_watcher.go:72] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/mapper/docker_vol-docker--pool_tmeta: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/mapper/docker_vol-docker--pool_tmeta`: exit status 127
....
Apr 24 15:50:20 ip-10-20-4-17 origin-node: E0424 15:50:20.739822   20154 kubelet_node_status.go:324] Error updating node status, will retry: error getting node "ip-10-20-4-17.eu-west-1.compute.internal": nodes "ip-10-20-4-17.eu-west-1.compute.internal" not found
....
Apr 24 15:50:20 ip-10-20-4-17 journal: E0424 15:50:20.744130   20154 kubelet_node_status.go:316] Unable to update node status: update node status exceeds retry count
```

Cheers,
SRG

**Comment by cooktheryan** [comment]
I have safely demo'd the following today. Shutdown all nodes leaving only the masters up. Then shutdown the masters.

```
[ec2-user@ip-10-20-6-87 ~]$ oc get nodes
NAME                          STATUS                     AGE
ip-10-20-4-83.ec2.internal    Ready,SchedulingDisabled   3h
ip-10-20-5-131.ec2.internal   Ready,SchedulingDisabled   3h
ip-10-20-6-87.ec2.internal    Ready,SchedulingDisabled   3h
```

When you need to use the environment again. Start up all the masters first and then the nodes.
```
[ec2-user@ip-10-20-6-87 ~]$ oc get nodes -w
NAME                          STATUS                     AGE
ip-10-20-4-253.ec2.internal   Ready                      32s
ip-10-20-4-51.ec2.internal    Ready                      34s
ip-10-20-4-83.ec2.internal    Ready,SchedulingDisabled   3h
ip-10-20-5-131.ec2.internal   Ready,SchedulingDisabled   3h
ip-10-20-5-243.ec2.internal   Ready                      33s
ip-10-20-5-25.ec2.internal    NotReady                   29s
ip-10-20-6-122.ec2.internal   Ready                      35s
ip-10-20-6-87.ec2.internal    Ready,SchedulingDisabled   3h
NAME                         STATUS    AGE
ip-10-20-5-25.ec2.internal   Ready     30s


```

**Comment by sensiblemedia** [comment]
@cooktheryan 
Starting the cluster as you described did not resolve the issue in this instance.
It turned out the cluster had split into the following:

5 AWS Nodes:
Master02, Master03, infra-node01 infra-node03, app-node02 
and 
3 AWS nodes:
master01, infra-node02, app-node01

The problem appears to be due to miss-match tagging of KubernetesCluster.
Below shows three nodes tagged KubernetesCluster devEND 
AWS stack name = dev

Q) Any idea what could have introduced the END suffix to tag name, I'm pretty sure I did not add it?

```
$ aws ec2 describe-tags --output text | grep -A1 "KubernetesCluster"
TAGS	KubernetesCluster	subnet-6f98a937	subnet	dev
TAGS	Name	subnet-6f98a937	subnet	Private_Subnet_1
--
TAGS	KubernetesCluster	i-0044897ce33ced84a	instance	dev
TAGS	Name	i-0044897ce33ced84a	instance	bastion.motabtest.co.uk
--
TAGS	KubernetesCluster	i-04fac665c51340ec5	instance	dev
TAGS	Name	i-04fac665c51340ec5	instance	ose-master02.motabtest.co.uk
--
TAGS	KubernetesCluster	i-05fdb41ba5979bebd	instance	dev
TAGS	Name	i-05fdb41ba5979bebd	instance	ose-infra-node03.motabtest.co.uk
--
TAGS	KubernetesCluster	i-09e57ce7761b306f8	instance	devEND
TAGS	Name	i-09e57ce7761b306f8	instance	ose-master01.motabtest.co.uk
--
TAGS	KubernetesCluster	i-0aa054063c10e3e72	instance	dev
TAGS	Name	i-0aa054063c10e3e72	instance	ose-master03.motabtest.co.uk
--
TAGS	KubernetesCluster	i-0ba1ece8045955066	instance	devEND
TAGS	Name	i-0ba1ece8045955066	instance	ose-infra-node02.motabtest.co.uk
--
TAGS	KubernetesCluster	i-0c809be7d616bab1b	instance	dev
TAGS	Name	i-0c809be7d616bab1b	instance	ose-app-node02.motabtest.co.uk
--
TAGS	KubernetesCluster	i-0ce09326c7ec81962	instance	devEND
TAGS	Name	i-0ce09326c7ec81962	instance	ose-app-node01.motabtest.co.uk
--
TAGS	KubernetesCluster	i-0d0695319834456f7	instance	dev
TAGS	Name	i-0d0695319834456f7	instance	ose-infra-node01.motabtest.co.uk
--
TAGS	KubernetesCluster	igw-4659c422	internet-gateway	dev
TAGS	aws:cloudformation:logical-id	igw-4659c422	internet-gateway	VpcInternetGateway
--
TAGS	KubernetesCluster	sg-36da504f	security-group	dev
TAGS	Name	sg-36da504f	security-group	ose_infra_node_sg
--
TAGS	KubernetesCluster	vpc-91c72ff6	vpc	dev
TAGS	Name	vpc-91c72ff6	vpc	ose-multi-az-vpc-dev
```

FYI, Thought I would just mention that I am currently involved with a Red Hat Workshop engagement here in London, which is pretty awesome :-)

**Comment by cooktheryan** [comment]
Hmm I wonder if you remove END and restart the nodes if they will rejoin the proper cluster. I would check the node-config.yaml to make sure END is not in there

**Comment by sensiblemedia** [comment]
Unfortunately I had torn down that stack and I only noticed the devEND tag after the instances had terminated. Replaying ansible-contrib deployment and will check KubernetesCluster tags and as a test manually set them to represent my previous post to measure functionality. Still at a loss how the END suffix got introduced though. Will let you know findings.

**Comment by sensiblemedia** [comment]
Managed to reproduce the issue by amending AWS KubernetesCluster tag.
Still unsure how the END prefix become assigned, could it be related to failed update to the cluster Cloudformation process.

**Comment by cooktheryan** [comment]
@sensiblemedia keep me in the loop if you see this again. Glad to hear you are working with RH!  I will keep it open for another week. That should let us know if it happens again

**Comment by jcperezamin** [comment]
I do not have this error and every day I turn the cluster off and turn it on in the morning. Version 1.5.0 Origin.

**Comment by cooktheryan** [comment]
Im going to close this. Feel free to re-open if you hit this again
