### ISSUE TITLE
'dict object' has no attribute 'tag_openshift_role_storage'

### ISSUE THREAD

**Issue by jbrannst** [openshift/openshift-ansible-contrib#335]
Hi, I am running a fresh install on AWS to update to 3.5 from my Mac. 

Cloudformation runs fine, but install OCP fails at 
TASK [instance-groups : Add storage instances to host group] *******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'tag_openshift_role_storage'"}

aws-ansible/$ grep -rnw . -e 'tag_openshift_role_storage'
./playbooks/roles/instance-groups/tasks/main.yaml:58:  with_items: "{{ groups['tag_openshift_role_storage'] }}"
./playbooks/roles/instance-groups/tasks/main.yaml:60:    - hostvars[item]['ec2_tag_KubernetesCluster'] == "{{ stack_name }}" and "{{ groups['tag_openshift_role_storage'] }}" is defined
./playbooks/roles/instance-groups/tasks/main.yaml:82:    - add_node is defined and add_node == "yes" and hostvars[item]['ec2_tag_aws_cloudformation_stack_name'] == "{{ stack_name }}-{{ gluster_stack }}" and "{{ groups['tag_openshift_role_storage'] }}" is defined
./playbooks/roles/inventory-file-creation/tasks/main.yaml:67:  with_items: "{{ groups['tag_openshift_role_storage'] }}"
./playbooks/roles/inventory-file-creation/tasks/main.yaml:69:  - hostvars[item]['ec2_tag_KubernetesCluster'] == "{{ stack_name }}" and "{{ groups['tag_openshift_role_storage'] }}" is defined

This worked a few weeks ago. I am running from Mac. 
Python 2.7.12
boto 2.42.0
ansible 2.2.0.0

latest openshift-ansible at /usr/share/ansible/openshift-ansible
latest openshift-ansible-contrib

I am using Google auth instead of github auth, thus the dummy params. Does not look like a source of the error though. I would assume it's related to the work around storage.

Configured values:
	stack_name: openshift-infra
	ami: ami-8b8c57f8
	region: eu-west-1
	master_instance_type: m4.xlarge
	node_instance_type: t2.large
	app_instance_type: m4.xlarge
	bastion_instance_type: t2.micro
	keypair: OpenShift-Key
	create_key: no
	key_path: /dev/null
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: openshift-enterprise
	openshift_sdn: openshift-ovs-subnet
	public_hosted_zone: ocp.rocks
	app_dns_prefix: apps
	apps_dns: apps.ocp.rocks
	rhsm_user: jbrannst
	rhsm_password: *******
	rhsm_pool: Employee SKU
	containerized: False
	s3_bucket_name: ocp-infra-registry-1234567
	s3_username: ec2-user
	github_client_id: *******
	github_client_secret: *******
	github_organization: z

Continue using these values? [y/N]: y

PLAY [localhost] ***************************************************************

TASK [ssh-key : OSE ec2 key] ***************************************************
skipping: [localhost] => (item=) 

TASK [cfn-outputs : Get cfn stack outputs] *************************************
skipping: [localhost]

TASK [cfn-outputs : Set s3 facts] **********************************************
skipping: [localhost]

TASK [pre-install-check : Get current Ansible version on local host] ***********
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [pre-install-check : Ensure Ansible version is not 2.3] *******************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [cloudformation-infra : Create Greenfield Infrastructure] *****************
ok: [localhost]

TASK [cloudformation-infra : Create Brownfield Infrastructure] *****************
skipping: [localhost]

TASK [cloudformation-infra : Create Brownfield Infrastructure with existing bastion] ***
skipping: [localhost]

TASK [cloudformation-infra : Add App Node] *************************************
skipping: [localhost]

TASK [cloudformation-infra : Add Infra Node] ***********************************
skipping: [localhost]

TASK [cloudformation-infra : Add CNS Gluster Nodes] ****************************
skipping: [localhost]

TASK [cloudformation-infra : Add CRS Gluster Nodes] ****************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [cfn-outputs : Get cfn stack outputs] *************************************
ok: [localhost]

TASK [cfn-outputs : Set s3 facts] **********************************************
ok: [localhost]

TASK [instance-groups : Add bastion to group] **********************************
changed: [localhost]

TASK [instance-groups : Add masters to requisite groups] ***********************
changed: [localhost] => (item=ip-10-20-6-146.eu-west-1.compute.internal)
changed: [localhost] => (item=ip-10-20-4-73.eu-west-1.compute.internal)
changed: [localhost] => (item=ip-10-20-5-69.eu-west-1.compute.internal)

TASK [instance-groups : Add a master to the single master group] ***************
changed: [localhost] => (item=ose-master03.ocp.rocks)

TASK [instance-groups : Add infra instances to host group] *********************
changed: [localhost] => (item=ip-10-20-6-236.eu-west-1.compute.internal)
changed: [localhost] => (item=ip-10-20-5-162.eu-west-1.compute.internal)
changed: [localhost] => (item=ip-10-20-4-240.eu-west-1.compute.internal)

TASK [instance-groups : Add app instances to host group] ***********************
changed: [localhost] => (item=ip-10-20-5-250.eu-west-1.compute.internal)
changed: [localhost] => (item=ip-10-20-4-22.eu-west-1.compute.internal)

TASK [instance-groups : Add storage instances to host group] *******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'tag_openshift_role_storage'"}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=5    unreachable=0    failed=1

**Comment by cooktheryan** [comment]
Do you have the latest pull and what is the ansible version?

Ryan

**Comment by jbrannst** [comment]
$ pip show ansible
---
Metadata-Version: 1.1
Name: ansible
Version: 2.2.0.0

$ git log
commit 3227b92960b7e7b9163db9dd8d8c51af52c2a485
Author: Ryan Cook <rcook@redhat.com>
Date:   Sun Apr 30 12:11:49 2017 -0400

    rollback

-- 
Best regards,

Johannes Brännström
Solution Architect

Red Hat AB
Kista Science Tower
SE-164 51 Kista
SWEDEN

Mobile:         +46 (0)72 510 91 60
Email:          johannes.brannstrom@redhat.com
Web:            www.redhat.com

**Comment by jcperezamin** [comment]
Please, install 2.3.0

**Comment by cooktheryan** [comment]
I would at least suggest bumping up to 2.2.2.0 

Ci just passed on rhel with the ansible-2.2.1.0-2.el7.noarch rpm

Testing on fedora now

**Comment by jbrannst** [comment]
TASK [pre-install-check : Ensure Ansible version is not 2.3] **********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "ansible_version.full | version_compare('2.3', '<')", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "msg": "Downgrade to Ansible version 2.2.0+"
}
 2.3 is not supported. Will try 2.2.2

**Comment by jcperezamin** [comment]
I used 2.3 and it worked out.

**Comment by jbrannst** [comment]
Ok. Then we should update the checks. Using 2.2.2.0 output is printed differently, but similar error:

TASK [instance-groups : Add storage instances to host group] *******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'hostvars[item]['ec2_tag_KubernetesCluster'] == \"{{ stack_name }}\" and \"{{ groups['tag_openshift_role_storage'] }}\" is defined' failed. The error was: error while evaluating conditional (hostvars[item]['ec2_tag_KubernetesCluster'] == \"{{ stack_name }}\" and \"{{ groups['tag_openshift_role_storage'] }}\" is defined): 'dict object' has no attribute 'tag_openshift_role_storage'\n\nThe error appears to have been in '/Users/anyone/code/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/roles/instance-groups/tasks/main.yaml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add storage instances to host group\n  ^ here\n"}

**Comment by jcperezamin** [comment]
cooktheryan:

I modified this on roles/prerequisites

- name: Set Origin fact
  set_fact:
    openshift_release: 1.4.1
  when: deployment_type == "origin"


- name: Set Origin fact
  set_fact:
    openshift_release: 1.5.0
  when: deployment_type == "origin"

I was able to install 1.5.0

OpenShift Master:
v1.5.0+031cbe4
Kubernetes Master:
v1.5.2+43a9be4

**Comment by cooktheryan** [comment]
@jcperezamin would love if you could pr that

**Comment by cooktheryan** [comment]
@jbrannst will code it in once I arrive at summit. Glad its working and thanks @jcperezamin for the suggestion

**Comment by jcperezamin** [comment]
My blog about it: http://easynube.co.uk/build-paas-openshift-origin-1-5-vmware-workstation-route53-home/

**Comment by jbrannst** [comment]
Running ansible 2.3.0 and boto-2.46.1 I get this: 

TASK [cloudformation-infra : Create Greenfield Infrastructure] ********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Parameter validation failed:\nInvalid type for parameter Parameters[1].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[3].ParameterValue, value: 10, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[13].ParameterValue, value: 5, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[15].ParameterValue, value: 50, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[25].ParameterValue, value: 15, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[27].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[37].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[38].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[39].ParameterValue, value: 15, type: <type 'int'>, valid types: <type 'basestring'> Parameter validation failed:\nInvalid type for parameter Parameters[1].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[3].ParameterValue, value: 10, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[13].ParameterValue, value: 5, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[15].ParameterValue, value: 50, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[25].ParameterValue, value: 15, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[27].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[37].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[38].ParameterValue, value: 25, type: <type 'int'>, valid types: <type 'basestring'>\nInvalid type for parameter Parameters[39].ParameterValue, value: 15, type: <type 'int'>, valid types: <type 'basestring'> - <class 'botocore.exceptions.ParamValidationError'>"}

**Comment by jbrannst** [comment]
I ran with boto-2.42.0 before running with boto-2.46.1, same error. And now tried updating boto3 from boto3-1.4.1 to boto3-1.4.4. Same error

**Comment by jcperezamin** [comment]
My version:
python2-boto-2.45.0-3.el7.noarch 
I have got a few installer Vms
My ansible version 2.2.3.0 now (2.3.0 was working out)
I have been with the same installation problems a few weeks ago.

**Comment by cooktheryan** [comment]
@jbrannst @jcperezamin fix for 2.3 is currently in PR

**Comment by cooktheryan** [comment]
still have some fixes around inventory. Wasn't expecting this many issues with 2.3

**Comment by cooktheryan** [comment]
The pr above works for 2.3 now

**Comment by jbrannst** [comment]
Cool! Yes, tried your PR and works great also on my setup
