### ISSUE TITLE
ERROR! the playbook: Hat could not be found

### ISSUE THREAD

**Issue by achyuthk** [openshift/openshift-ansible-contrib#339]
I am struck at the below error while running "gcloud.sh" script, where there are no failures in the "PLAY RECAP" section, but got an error after that saying "ERROR! the playbook: Hat could not be found". 

The intermediate steps that are executed are deprecated and given below: 

[root@docker gce-cli]# ./gcloud.sh
~/openshift-ansible-contrib/reference-architecture/gce-cli/ansible ~/openshift-ansible-contrib/reference-architecture/gce-cli

PLAY [configure ansible connection to the gcp and basic stuff] ****************************************************************************************************

TASK [ansible-gcp : check for service account] ********************************************************************************************************************
ok: [localhost]

.
.
.

TASK [deployment-create : create deployment ocp-network config file] **********************************************************************************************
ok: [localhost]

TASK [deployment-create : check if deployment ocp-network exists] *************************************************************************************************
ok: [localhost]

TASK [deployment-create : create deployment ocp-network] **********************************************************************************************************
skipping: [localhost]

PLAY RECAP ********************************************************************************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=0

ERROR! the playbook: Hat could not be found
[root@docker gce-cli]#

**Comment by achyuthk** [comment]
@pschiffe  Please help  me resolving this..

**Comment by pschiffe** [comment]
Hello @achyuthk , could please try to run `bash -x gcloud.sh` and then paste the output here? But don't forget to strip the passwords from there.

**Comment by achyuthk** [comment]
Sorry I am totally new to google cloud engine...

I didn't get what does stripping passwords mean... 

 I got a new error now for creating dns zone. I was not getting this error before.. 

[root@docker gce-cli]# ./gcloud.sh
~/openshift-ansible-contrib/reference-architecture/gce-cli/ansible ~/openshift-ansible-contrib/reference-architecture/gce-cli

PLAY [configure ansible connection to the gcp and basic stuff] ****************************************************************************************************

TASK [ansible-gcp : check for service account] ********************************************************************************************************************
ok: [localhost]

TASK [ansible-gcp : create new service account] *******************************************************************************************************************
skipping: [localhost]

TASK [ansible-gcp : create service account key] *******************************************************************************************************************
ok: [localhost]

TASK [ansible-gcp : grant service account access to the gcp project] **********************************************************************************************
skipping: [localhost]

TASK [ansible-gcp : create secrets file] **************************************************************************************************************************
ok: [localhost]

TASK [dns-zone : create dns zone] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "[DEPRECATION WARNING]: secrets file found at '/root/openshift-ansible-contrib\n/reference-architecture/gce-cli/ansible/inventory/gce/hosts/secrets.pyc'.  This\n method of specifying credentials is deprecated.  Please use env vars or \nAnsible YAML files instead.\nThis feature will be removed in version 2.5. \nDeprecation warnings can be disabled by setting deprecation_warnings=False in \nansible.cfg.\nTraceback (most recent call last):\n  File \"/tmp/ansible_WzzS8G/ansible_module_gcdns_zone.py\", line 386, in <module>\n    main()\n  File \"/tmp/ansible_WzzS8G/ansible_module_gcdns_zone.py\", line 348, in main\n    zone = _get_zone(gcdns, zone_name)\n  File \"/tmp/ansible_WzzS8G/ansible_module_gcdns_zone.py\", line 277, in _get_zone\n    for zone in available_zones:\n  File \"/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py\", line 311, in _get_more\n    **kwargs)\n  File \"/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py\", line 332, in _get_data\n    params=params,)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 806, in request\n    *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/base.py\", line 571, in request\n    params, headers = self.pre_connect_hook(params, headers)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 788, in pre_connect_hook\n    self.oauth2_credential.access_token)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 666, in access_token\n    self._refresh_token()\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 674, in _refresh_token\n    self.token = self.oauth2_conn.refresh_token(self.token)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 393, in refresh_token\n    return self.get_new_token()\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 537, in get_new_token\n    return self._token_request(request)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 370, in _token_request\n    raise GoogleAuthError('Invalid authorization response, please '\nlibcloud.common.google.GoogleAuthError: 'Invalid authorization response, please check your credentials and time drift.'\n",
    "module_stdout": "",
    "rc": 0
}

MSG:

MODULE FAILURE


PLAY RECAP ********************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1

[root@docker gce-cli]#

**Comment by achyuthk** [comment]
I am using the same "config.sh" file which I used to.. Is it a problem with Client credentials?

**Comment by pschiffe** [comment]
What version of ansible are you using? Unfortunately, currently only 2.2.x is supported, 2.3 and newer won't work, so you might need to downgrade the ansible package.

**Comment by achyuthk** [comment]
Am using "2.3.0.0" version of ansible. 

[root@docker gce-cli]# ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
[root@docker gce-cli]#

**Comment by achyuthk** [comment]
I was not facing this issue before, where the version was the same as now... Wierd.. Let me try by downgrading ansible.

**Comment by achyuthk** [comment]
I am still getting the same error even with 2.2.2.0... 

Commands used: 

# yum downgrade ansible
#cd openshift-ansible-contrib/reference-architecture/gce-cli/
#bash -x gcloud.sh

[root@docker gce-cli]# ansible --version
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[root@docker gce-cli]#

**Comment by pschiffe** [comment]
So what's the output of `bash -x gcloud.sh`? BTW by stripping passwords I just meant to delete them from the output before posting it here.

**Comment by achyuthk** [comment]
The same error as before. 

[root@docker gce-cli]# bash -x gcloud.sh 

. . . 

TASK [dns-zone : create dns zone] **********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: libcloud.common.google.GoogleAuthError: 'Invalid authorization response, please check your credentials and time drift.'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gKjHp5/ansible_module_gcdns_zone.py\", line 381, in <module>\n    main()\n  File \"/tmp/ansible_gKjHp5/ansible_module_gcdns_zone.py\", line 343, in main\n    zone = _get_zone(gcdns, zone_name)\n  File \"/tmp/ansible_gKjHp5/ansible_module_gcdns_zone.py\", line 272, in _get_zone\n    for zone in available_zones:\n  File \"/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py\", line 311, in _get_more\n    **kwargs)\n  File \"/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py\", line 332, in _get_data\n    params=params,)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 806, in request\n    *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/base.py\", line 571, in request\n    params, headers = self.pre_connect_hook(params, headers)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 788, in pre_connect_hook\n    self.oauth2_credential.access_token)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 666, in access_token\n    self._refresh_token()\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 674, in _refresh_token\n    self.token = self.oauth2_conn.refresh_token(self.token)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 393, in refresh_token\n    return self.get_new_token()\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 537, in get_new_token\n    return self._token_request(request)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 370, in _token_request\n    raise GoogleAuthError('Invalid authorization response, please '\nlibcloud.common.google.GoogleAuthError: 'Invalid authorization response, please check your credentials and time drift.'\n",
    "module_stdout": ""
}

MSG:

MODULE FAILURE


PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1

**Comment by achyuthk** [comment]
The problem was with the credentials in the config.sh. Now, we are back at the same error, for which issue was reported... 

[root@docker gce-cli]# bash -x gcloud.sh
. . . 

TASK [deployment-create : create deployment ocp-network config file] ***********
ok: [localhost]

TASK [deployment-create : check if deployment ocp-network exists] **************
ok: [localhost]

TASK [deployment-create : create deployment ocp-network] ***********************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0

+ ansible-playbook -e rhsm_user=achyuth.karanam@coudgensys.com -e rhsm_password=cloudgen@123 -e rhsm_pool=Red Hat OpenShift Container Platform, Standard, 2-Core playbooks/main.yaml
ERROR! the playbook: Hat could not be found
[root@docker gce-cli]#

@pschiffe please assist.

**Comment by pschiffe** [comment]
OK, I think I see the problem, please try to use the pool ID for the `RH_POOL_ID` variable, it looks like hash, e.g. `3de403e3ce9...` and not the pool name. I'll try to fix this issue in a PR later.

**Comment by achyuthk** [comment]
Do you mean the pool id that we get for openshift with the command "subscription-manager list --available --matches '*OpenShift*'" ??

**Comment by pschiffe** [comment]
Yes, it's the `Pool ID:             8a815bef7...` field.

**Comment by achyuthk** [comment]
I have a connectivity issue to the redhat server. I will try with pool id and update.

**Comment by achyuthk** [comment]
@pschiffe Apologies for the delay.. 

I have updated the RH_POOL_ID in config.sh with the actual pool-id and the previous error is resolved. 

But, got a new hurdle as below: 

![image](https://cloud.githubusercontent.com/assets/28394719/25855642/683f0f80-34f1-11e7-8ec9-7ad3f70f5677.png)

Please suggest.

**Comment by pschiffe** [comment]
Thanks for reporting and helping out with the issue! :-)
