### ISSUE TITLE
The conditional check 'master_https_key_file' failed. The error was: template error while templating string: unexpected '/'.

### ISSUE THREAD

**Issue by achyuthk** [openshift/openshift-ansible-contrib#344]
My openshift installation on google cloud instances had a hurdle at the below step, while running "gcloud.sh" script. 

The error is detailed as below: (o/p is depricated)

![image](https://cloud.githubusercontent.com/assets/28394719/25864688/fdca9dfa-350d-11e7-8bac-ed5a435476fa.png)

I believe the issue is with the code at the main.yml file. Or, I may be completely wrong. 

Please suggest on further course of action.

**Comment by achyuthk** [comment]
@pschiffe I see the below error while running syntax-check against the playbook. 

![image](https://cloud.githubusercontent.com/assets/28394719/25898511/096b0de2-35aa-11e7-8303-bb15a92ae607.png)

Please suggest. FYI, the ansible version is 2.2.2.0.

**Comment by pschiffe** [comment]
@achyuthk I think that this is OK, as the `ansible/playbooks/roles/ssl-certificate/tasks/main.yaml` file is not a playbook, but just the role file with tasks. To use `syntax-check`, you need to use playbook file, in this case, `ansible/playbooks/core-infra.yaml`.

I've created PR #346 which should fix your problem, you can try it out before it's merged, if you want to.

**Comment by pschiffe** [comment]
@achyuthk The PR was merged, please update your git repo and try again. Thanks.

**Comment by achyuthk** [comment]
I have updated the repo and tried again. I see that the error that was reported is resolved. But it is failing at the next task. I suspect this is a dependency task (dependent on previous task), which is why I had to update this issue with the new error. 

Please find the error below: 

screen

![image](https://cloud.githubusercontent.com/assets/28394719/25906578/b0a466ea-35c2-11e7-8486-8009f3928920.png)

screen.continued

![image](https://cloud.githubusercontent.com/assets/28394719/25906522/8c1f18e2-35c2-11e7-9b10-e2fc52a17d01.png)

**Comment by pschiffe** [comment]
Does the key file exists? What is the content of the `MASTER_HTTPS_CERT_FILE` and `MASTER_HTTPS_KEY_FILE` variables from `config.sh` file and the output when you try the `ls -lh` command on them?

**Comment by achyuthk** [comment]
I missed out in creating cert files.. Will let you know once done. Thanks a ton.

**Comment by achyuthk** [comment]
@pschiffe Do we have any way to use HTTP instead of HTTPS to avoid the ssl certs procedure?

**Comment by achyuthk** [comment]
I commented out MASTER_HTTPS_CERT_FILE and MASTER_HTTPS_KEY_FILE in config.sh, so that it could create self signed certs and got the below error while creating deployment ocp-core

![image](https://cloud.githubusercontent.com/assets/28394719/25913929/1cbf29e8-35da-11e7-9b29-a2f895040a77.png)

@pschiffe Please suggest.

**Comment by pschiffe** [comment]
@achyuthk the first error is weird, previous tasks should create the gold image. Could you post output of `gcloud compute images list --no-standard-images`

And for the second error.. Are you using the free trial of GCP? This might be the case, otherwise I'm not sure why are you limited to only one static IP address. OCP needs 3 of them. You can check with `gcloud compute addresses list`.
