### ISSUE TITLE
add-node.py creates new AWS stack name and fails with rollback.

### ISSUE THREAD

**Issue by sensiblemedia** [openshift/openshift-ansible-contrib#350]
Hi 
Looking for confirmation of how add-node.py should behave.
When executing the following command a new AWS stack is created consisting of --existing-stack name and --shortname in the case below a new AWS stack called 'dev-ose-app-node03' is created.
The stack then rolls back complaining it is unable to find dev-NodePolicy-2O****F1R.

`$ ./add-node.py --region=eu-west-1 --existing-stack=dev --deployment-type=origin --public-hosted-zone=mydomain.co.uk --keypair=OSE-Dev-key  --node-type=app --iam-role=dev-NodePolicy-2O****F1R  --node-sg=sg-bb****c2 --infra-sg=sg-7a****03 --shortname=ose-app-node03 --subnet-id=subnet-b6****d1 --infra-elb-name=dev-InfraElb-3ZCA****HUQ9 --ami=ami-1daa8c7b --containerized=true`

add-node.py
```
    131   # calculate stack name
    132   new_node_stack="%s-%s" % (existing_stack, shortname)
```

Cheers,
SRG

**Comment by cooktheryan** [comment]
The iam role should be the one that has NodeInstanceProfile in it.

For example:
Instance Profile ARNs
arn:aws:iam::833237141234:instance-profile/openshift-infra-NodeInstanceProfile-1E7B0KQAA5RZP

with openshift-infra-NodeInstanceProfile-1E7B0KQAA5RZP being the IAM role that needs to be defined for the play

**Comment by sensiblemedia** [comment]
@cooktheryan thanks that got me further but the following seems to be broken when applied to origin.
```
TASK [openshift_node_certificates : Generate the node client config] ***********

--expire-days=730
Error: unknown flag: --expire-days
Usage:
  oc adm create-api-client-config [options]

Options:
      --basename='': The base filename to use for the .crt, .key, and .kubeconfig files. Defaults to the username.
      --certificate-authority=[openshift.local.config/master/ca.crt]: Files containing signing authorities to use to verify the API server's serving certificate.
      --client-dir='': The client data directory.
      --groups=[]: The list of groups this user belongs to. Comma delimited list
      --master='https://localhost:8443': The API server's URL.
      --public-master='': The API public facing server's URL (if applicable).
      --signer-cert='openshift.local.config/master/ca.crt': The certificate file.
      --signer-key='openshift.local.config/master/ca.key': The key file.
      --signer-serial='openshift.local.config/master/ca.serial.txt': The serial file that keeps track of how many certs have been signed.
      --user='': The scope qualified username.

Use "oc adm options" for a list of global command-line options (applies to all commands).
```

While I appreciate this is not strictly  part of contrib but rather openshift-ansible
I found the following condition statements in /usr/share/ansible/openshift-ansible/playbooks/aws/openshift-cluster/roles/openshift_node_certificates/tasks/main.yml

```
     69     {% if openshift_version | oo_version_gte_3_5_or_1_5(openshift.common.deployment_type) | bool %}
     70     --expire-days={{ openshift_node_cert_expire_days }}
     71     {% endif %}
....
....
     85     {% if openshift_version | oo_version_gte_3_5_or_1_5(openshift.common.deployment_type) | bool %}
     86     --expire-days={{ openshift_node_cert_expire_days }}
     87     {% endif %}
```
Temporarily deleted the above lines so as to continue and got further until the following truncated error:

`   "stderr":"error: --signer-serial, \"/etc/origin/master/ca.serial.txt\" must be a valid file\nSee 'oc adm create-api-client-config -h' for help and examples.",`

Checking on the ose-master01 this file does not exist! ??

```
$ oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://internal-openshift-master.mydomain.co.uk
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
```

Thanks,
SRG

**Comment by cooktheryan** [comment]
From the ref arch document. I need to reach out to the openshift-ansible team to see if they have resolved this upstream 

== Failure When Adding Node(s)
At the time of writing there is a known bug in the OpenShift installation
routine that may cause a failure when adding nodes either with the `add-cns-storage.py` or `add-node.py` playbooks.
 The failure occurs during the step
“Generate the node client config”. In this case the output of the the installation
routine is similar to the following:

[subs=+quotes]
----
failed: [ose-ocp-cns01-node03.sysdeseng.com -> ose-master03.sysdeseng.com] (item=ose-ocp-cns01-node03.sysdeseng.com) => {
    "changed": true,
    "cmd": [
        "oc",
        "adm",
        "create-api-client-config",
        "--certificate-authority=/etc/origin/master/ca.crt",
        "--client-dir=/etc/origin/generated-configs/node-ip-10-20-6-56.us-west-2.compute.internal",
        "--groups=system:nodes",
        "--master=https://internal-openshift-master.sysdeseng.com",
        "--signer-cert=/etc/origin/master/ca.crt",
        "--signer-key=/etc/origin/master/ca.key",
        "--signer-serial=/etc/origin/master/ca.serial.txt",
        "--user=system:node:ip-10-20-6-56.us-west-2.compute.internal"
    ],
    "delta": "0:00:00.158849",
    "end": "2017-04-17 17:27:29.789575",
    "failed": true,
    "item": "ose-ocp-cns01-node03.sysdeseng.com",
    "rc": 1,
    "start": "2017-04-17 17:27:29.630726",
    "warnings": []
}

STDERR:

error: --signer-serial, "/etc/origin/master/ca.serial.txt" must be a valid file
See 'oc adm create-api-client-config -h' for help and examples.
----

In this case the `Ansible` deployment routine picks the wrong OpenShift master node
to create the client configuration. Only one of the 3 master nodes has the file
`/etc/origin/master/ca.serial.txt` present and in the case above an OpenShift master
was used, that doesn’t have this file.
If this error occurs, find the master node on which this file exists and
copy the file to the all master nodes where this file does not exist in the
`/etc/origin/master` directory. The file should only contain 2 hexadecimal digits
therefore creating the file in `/etc/origin/master` path on the master nodes by
copy/pasting the content is sufficient as well. The file needs to be owned by
the user and group “root” and carries the permission mask 0644. When done, simply
re-run the deployment script again with the same arguments and this error should
not reappear.  Once the node installation is successful remove the `ca.serial.txt`
from the masters that did not initially have the file.

**Comment by sensiblemedia** [comment]
@cooktheryan thanks for this update it worked a treat 👍
