### ISSUE TITLE
Invalid authorization response, please check your credentials and time drift

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/openshift-ansible-contrib#351]
Hi, I am trying to install openshift on google cloud instances. FYI, I am trying with 1year free subscription. 

I followed the documentation at this [URL](https://access.redhat.com/documentation/en-us/reference_architectures/2017/html/deploying_red_hat_openshift_container_platform_3_on_google_cloud_platform/provisioning_infrastructure#preparing_the_environment) 

I am struck at the task of creating DNS zone, which is throwing authorization error. 

![image](https://cloud.githubusercontent.com/assets/25741747/25947711/37b4ecee-366e-11e7-80be-8c15425f0642.png)

Can someone help me in understanding which authorization is this reporting about...

**Comment by pschiffe** [comment]
Hello @naveenkumartangallapally . Is the time on your workstation synchronized with NTP server? What OS are you using? What do you see when you ran `gcloud auth list`? Please obfuscate the email address from that output. Also, when you try to list some resource with the `gcloud` command, does it work? E.g. `gcloud compute instances list`.

**Comment by naveenkumartangallapally** [comment]
Is the time on your workstation synchronized with NTP server?

Yes, I have installed ntp and my system is in sync with default centos ntp servers. 

What OS are you using?

My machine has CentOS. 

What do you see when you ran gcloud auth list? 

![naveen](https://cloud.githubusercontent.com/assets/25741747/25950161/9d5aa440-3677-11e7-8bc6-a7afd95865e2.png)

gcloud command works but there are no instances to list. 

![image](https://cloud.githubusercontent.com/assets/25741747/25950318/25415c50-3678-11e7-94d0-923bbfdcb7ea.png)

**Comment by pschiffe** [comment]
@naveenkumartangallapally correct. Could you look at the files in the `ansible/inventory/gce/hosts/` folder? There should be `project.json` and `secrets.py`, check if they seem correct, maybe post them here, but without any sensitive data (emails, keys, ids..). Also try to run `./ansible/inventory/gce/hosts/gce.py` and see if it prints any error. And please post the output of the `timedatectl` command.

**Comment by naveenkumartangallapally** [comment]
Both project.json and secrets.py are present in "ansible/inventory/gce/hosts/" 

Output of gce.py is as below... 

![image](https://cloud.githubusercontent.com/assets/25741747/25958416/297edb10-368e-11e7-9c8d-05c87e0f54a4.png)

timedatectl is as below: 

![image](https://cloud.githubusercontent.com/assets/25741747/25958507/64a0b09c-368e-11e7-9169-84d6bfc665d7.png)

@pschiffe What should I check for in project.json and secrets.py?

**Comment by pschiffe** [comment]
Example `project.json`:
```
$ cat ansible/inventory/gce/hosts/project.json
{
  "type": "service_account",
  "project_id": "oxxxh",
  "private_key_id": "e4f8exxx92d",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIExxxxskYNn8ieqA\n-----END PRIVATE KEY-----\n",
  "client_email": "oxxxh.iam.gserviceaccount.com",
  "client_id": "10xxxx7",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/oxxxh.iam.gserviceaccount.com"
}
````

Example `secrets.py`:
```
$ cat ansible/inventory/gce/hosts/secrets.py
GCE_PARAMS = ('oxxxh.iam.gserviceaccount.com', '/homexxxxift-ansible-contrib/reference-architecture/gce-cli/ansible/inventory/gce/hosts/project.json')
GCE_KEYWORD_PARAMS = {'project': 'oxxxh', 'datacenter': 'europe-west1'}
```

**Comment by pschiffe** [comment]
@naveenkumartangallapally maybe try to delete the two files from above and then run the `gcloud.sh` command again.

**Comment by naveenkumartangallapally** [comment]
Both the files looks fair enough. 

I tried deleting both the files but facing the same issue :(

**Comment by pschiffe** [comment]
So now, I really have no idea what to try next. Basically, the authentication method we are using is described on this page [1], specifically, the method with secrets.py file [2]. Could you try to follow steps from that page? You need to try to make the dynamic inventory script work [3]. Create some new folder, download there the script from [3], and follow the steps in [1], so when you just run the script with `./gce.py`, it won't fail.

[1] http://docs.ansible.com/ansible/guide_gce.html
[2] http://docs.ansible.com/ansible/guide_gce.html#configuring-modules-with-secrets-py
[3] https://github.com/ansible/ansible/blob/devel/contrib/inventory/gce.py

**Comment by pschiffe** [comment]
@naveenkumartangallapally so, were you able to resolve this? how?

**Comment by naveenkumartangallapally** [comment]
I was not able to resolve this. I have followed other process of installation where I would manually create instances on Google cloud, update the inventory hosts and then use the playbook. I have raised another issue for the 8443 port issue..

**Comment by pschiffe** [comment]
Closing for now, please reopen if you find out additional info.

**Comment by Tedezed** [comment]
@naveenkumartangallapally In my case, I solved it with

Create credentials, and download JSON: http://docs.ansible.com/ansible/guide_gce.html#credentials

```
export GCE_CREDENTIALS_FILE_PATH=/home/xxxx/xxxx.json
```

Activate service account:
`$ gcloud auth activate-service-account --key-file $GCE_CREDENTIALS_FILE_PATH`
```
Activated service account credentials for: [name-credential-xxx-for-ansible@proyxxxxxx.iam.gserviceaccount.com]
```
`$ gcloud auth list`
```
Credentialed Accounts
ACTIVE  ACCOUNT
        xxxx@xxx.com
*       name-credential-xxx-for-ansible@proyxxxxxx.iam.gserviceaccount.com
```

Test: `gcloud compute instances list`

Define email:
```
export GCE_EMAIL=name-credential-xxx-for-ansible@proyxxxxxx.iam.gserviceaccount.com
```

Hope this helps you! =)
