### ISSUE TITLE
[osp-dns] - playbook should accept --key-name or --private-key for ssh to the DNS host.

### ISSUE THREAD

**Issue by markllama** [openshift/openshift-ansible-contrib#355]
when running the playbook with --key-name or --private-key and the file path to the private key file associated with the openstack keypair, ansible fails to log in to the new DNS server.  Allowing ansible to proceed requires placing the private key file in `.ssh/id_rsa` so that ansible's call to SSH uses the default private key.

**Comment by tomassedovic** [comment]
I'm taking a look.
