### ISSUE TITLE
Not able to deploy infra via ose-on-aws.py

### ISSUE THREAD

**Issue by nnachefski** [openshift/openshift-ansible-contrib#358]
I've got a byo bastion host, however, it fails with the same result if i let it create the bastion.  not sure what the deal is, probably user error... but everything appears to look correct.  One thing that i was not clear on, should i pre-create the s3-username and s3-bucket-name ?  Or does the automation create those for me?

Configured values:
	stack_name: test1
	ami: ami-fdcf569d
	region: us-west-2
	master_instance_type: m4.xlarge
	node_instance_type: t2.large
	app_instance_type: t2.large
	bastion_instance_type: t2.micro
	keypair: OSE-key
	create_key: no
	key_path: /dev/null
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: yes
	bastion_sg: sg-c5d5a4be
	console port: 443
	deployment_type: origin
	openshift_sdn: openshift-ovs-subnet
	public_hosted_zone: openshiftdemo.com
	app_dns_prefix: apps
	apps_dns: apps.openshiftdemo.com
	rhsm_user: nnachefs@redhat.com
	rhsm_password: *******
	rhsm_pool: Red Hat OpenShift Container Platform, Standard, 2-Core
	containerized: false
	s3_bucket_name: ocp
	s3_username: nick
	github_client_id: *******
	github_client_secret: *******
	github_organization: ocptt

Continue using these values? [y/N]: y

PLAY [localhost] ***************************************************************

TASK [ssh-key : OSE ec2 key] ***************************************************
skipping: [localhost] => (item=) 

TASK [cfn-outputs : Get cfn stack outputs] *************************************
skipping: [localhost]

TASK [cfn-outputs : Set s3 facts] **********************************************
skipping: [localhost]

TASK [pre-install-check : Get current Ansible version on local host] ***********
ok: [localhost] => {
    "changed": false
}

MSG:

All assertions passed

TASK [cloudformation-infra : Create Greenfield Infrastructure] *****************
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "events": [
        "StackEvent AWS::CloudFormation::Stack test1 ROLLBACK_COMPLETE", 
        "StackEvent AWS::EC2::VPC Vpc DELETE_COMPLETE", 
        "StackEvent AWS::EC2::InternetGateway VpcInternetGateway DELETE_COMPLETE", 
        "StackEvent AWS::IAM::Role NodePolicy DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIP BastionEip DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIP EIP DELETE_COMPLETE", 
        "StackEvent AWS::IAM::Role NodePolicy DELETE_IN_PROGRESS", 
        "StackEvent AWS::S3::Bucket RegistryBucket DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIP EIP DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::EIP BastionEip DELETE_IN_PROGRESS", 
        "StackEvent AWS::IAM::User S3UserName DELETE_COMPLETE", 
        "StackEvent AWS::EC2::VPC Vpc DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::InternetGateway VpcInternetGateway DELETE_IN_PROGRESS", 
        "StackEvent AWS::CloudFormation::Stack test1 ROLLBACK_IN_PROGRESS", 
        "StackEvent AWS::IAM::Role NodePolicy CREATE_FAILED", 
        "StackEvent AWS::EC2::EIP BastionEip CREATE_FAILED", 
        "StackEvent AWS::EC2::InternetGateway VpcInternetGateway CREATE_FAILED", 
        "StackEvent AWS::EC2::VPC Vpc CREATE_FAILED", 
        "StackEvent AWS::EC2::EIP EIP CREATE_FAILED", 
        "StackEvent AWS::S3::Bucket RegistryBucket CREATE_FAILED", 
        "StackEvent AWS::IAM::User S3UserName CREATE_FAILED", 
        "StackEvent AWS::EC2::EIP EIP CREATE_IN_PROGRESS", 
        "StackEvent AWS::IAM::Role NodePolicy CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::VPC Vpc CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::EIP BastionEip CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::EIP EIP CREATE_IN_PROGRESS", 
        "StackEvent AWS::S3::Bucket RegistryBucket CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::VPC Vpc CREATE_IN_PROGRESS", 
        "StackEvent AWS::IAM::Role NodePolicy CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::EIP BastionEip CREATE_IN_PROGRESS", 
        "StackEvent AWS::IAM::User S3UserName CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::InternetGateway VpcInternetGateway CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::InternetGateway VpcInternetGateway CREATE_IN_PROGRESS", 
        "StackEvent AWS::CloudFormation::Stack test1 CREATE_IN_PROGRESS"
    ], 
    "failed": true, 
    "output": "Problem with CREATE. Rollback complete", 
    "stack_outputs": {}, 
    "stack_resources": [
        {
            "last_updated_time": null, 
            "logical_resource_id": "BastionEip", 
            "physical_resource_id": "35.167.72.107", 
            "resource_type": "AWS::EC2::EIP", 
            "status": "DELETE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "EIP", 
            "physical_resource_id": "54.71.20.151", 
            "resource_type": "AWS::EC2::EIP", 
            "status": "DELETE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "NodePolicy", 
            "physical_resource_id": "test1-NodePolicy-1SWUQMCVNKW2", 
            "resource_type": "AWS::IAM::Role", 
            "status": "DELETE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "RegistryBucket", 
            "physical_resource_id": null, 
            "resource_type": "AWS::S3::Bucket", 
            "status": "DELETE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "S3UserName", 
            "physical_resource_id": null, 
            "resource_type": "AWS::IAM::User", 
            "status": "DELETE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "Vpc", 
            "physical_resource_id": "vpc-6a75770d", 
            "resource_type": "AWS::EC2::VPC", 
            "status": "DELETE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "VpcInternetGateway", 
            "physical_resource_id": "igw-2bed2a4c", 
            "resource_type": "AWS::EC2::InternetGateway", 
            "status": "DELETE_COMPLETE", 
            "status_reason": null
        }
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

[ec2-user@ip-10-10-1-80 aws-ansible]$ rpm -qa | grep atomic
atomic-openshift-utils-3.5.60-1.git.0.b6f77a6.el7.noarch
atomic-openshift-clients-3.5.5.8-1.git.0.1a85a97.el7.x86_64
[ec2-user@ip-10-10-1-80 aws-ansible]$ rpm -qa | grep ansible
ansible-2.2.1.0-2.el7.noarch
openshift-ansible-filter-plugins-3.5.60-1.git.0.b6f77a6.el7.noarch
openshift-ansible-docs-3.5.60-1.git.0.b6f77a6.el7.noarch
openshift-ansible-lookup-plugins-3.5.60-1.git.0.b6f77a6.el7.noarch
openshift-ansible-callback-plugins-3.5.60-1.git.0.b6f77a6.el7.noarch
openshift-ansible-playbooks-3.5.60-1.git.0.b6f77a6.el7.noarch
openshift-ansible-3.5.60-1.git.0.b6f77a6.el7.noarch
openshift-ansible-roles-3.5.60-1.git.0.b6f77a6.el7.noarch

**Comment by cooktheryan** [comment]
I believe the error is because you did byo-bastion but also create-vpc=yes
so the ose-on-aws.py tried to deploy "greenfield"


Ryan

**Comment by nnachefski** [comment]
same result

do i have to pre-create the s3 bucket and user?

**Comment by nnachefski** [comment]
i removed the byo bastion and also removed the s3 parameters and it got alot further this time but still bombed out

Configured values:
	stack_name: testing4
	ami: ami-fdcf569d
	region: us-west-2
	master_instance_type: m4.xlarge
	node_instance_type: t2.large
	app_instance_type: t2.large
	bastion_instance_type: t2.micro
	keypair: nick-west2
	create_key: no
	key_path: /dev/null
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: origin
	openshift_sdn: openshift-ovs-subnet
	public_hosted_zone: openshiftdemo.com
	app_dns_prefix: apps
	apps_dns: apps.openshiftdemo.com
	rhsm_user: nnachefs@redhat.com
	rhsm_password: *******
	rhsm_pool: Red Hat OpenShift Container Platform, Standard, 2-Core
	containerized: false
	s3_bucket_name: testing4-ocp-registry-openshiftdemo
	s3_username: testing4-s3-openshift-user
	github_client_id: *******
	github_client_secret: *******
	github_organization: ocptt

Continue using these values? [y/N]: y

PLAY [localhost] ***************************************************************

TASK [ssh-key : OSE ec2 key] ***************************************************
skipping: [localhost] => (item=) 

TASK [cfn-outputs : Get cfn stack outputs] *************************************
skipping: [localhost]

TASK [cfn-outputs : Set s3 facts] **********************************************
skipping: [localhost]

TASK [pre-install-check : Get current Ansible version on local host] ***********
ok: [localhost] => {
    "changed": false
}

MSG:

All assertions passed


TASK [cloudformation-infra : Create Greenfield Infrastructure] *****************
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "events": [
        "StackEvent AWS::CloudFormation::Stack testing4 ROLLBACK_COMPLETE", 
        "StackEvent AWS::EC2::InternetGateway VpcInternetGateway DELETE_COMPLETE", 
        "StackEvent AWS::EC2::VPC Vpc DELETE_COMPLETE", 
        "StackEvent AWS::EC2::VPC Vpc DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::InternetGateway VpcInternetGateway DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::VPCGatewayAttachment VpcGA DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Subnet PublicSubnet1 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup BastionSg DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Subnet PublicSubnet1 DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup BastionSg DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Instance Bastion DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIP EIP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIP EIP DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::NatGateway Nat DELETE_COMPLETE", 
        "StackEvent AWS::EC2::NatGateway Nat DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Subnet PrivateSubnet3 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Subnet PublicSubnet3 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Subnet PrivateSubnet1 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Subnet PublicSubnet2 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIP BastionEip DELETE_COMPLETE", 
        "StackEvent AWS::S3::Bucket RegistryBucket DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIP BastionEip DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Instance Bastion DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::RouteTable PrivateRouteTable DELETE_COMPLETE", 
        "StackEvent AWS::EC2::RouteTable PrivateRouteTable DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Subnet PrivateSubnet3 DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::EIPAssociation BastionEipAssoc DELETE_COMPLETE", 
        "StackEvent AWS::EC2::RouteTable VpcRouteTable DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Subnet PrivateSubnet2 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SubnetRouteTableAssociation PrivateSubnet3RTA DELETE_COMPLETE", 
        "StackEvent AWS::EC2::RouteTable VpcRouteTable DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Subnet PublicSubnet3 DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Subnet PrivateSubnet1 DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Subnet PublicSubnet2 DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SubnetRouteTableAssociation PrivateSubnet1RTA DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SubnetRouteTableAssociation PublicSubnet3RTA DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Route VPCRouteInternetGateway DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SubnetRouteTableAssociation PublicSubnet2RTA DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Route Route DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SubnetRouteTableAssociation PublicSubnet1RTA DELETE_COMPLETE", 
        "StackEvent AWS::IAM::Role NodePolicy DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup MasterSG DELETE_COMPLETE", 
        "StackEvent AWS::IAM::Role NodePolicy DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup MasterIntElbSG DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup NodeSG DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup InfraElbSG DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup InfraSG DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup MasterSG DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup MasterExtElbSG DELETE_COMPLETE", 
        "StackEvent AWS::IAM::Role MasterPolicy DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup NodeSG DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup MasterIntElbSG DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup EtcdSG DELETE_COMPLETE", 
        "StackEvent AWS::IAM::User S3UserName DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup InfraSG DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup InfraElbSG DELETE_IN_PROGRESS", 
        "StackEvent AWS::IAM::InstanceProfile NodeInstanceProfile DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup MasterExtElbSG DELETE_IN_PROGRESS", 
        "StackEvent AWS::IAM::Role MasterPolicy DELETE_IN_PROGRESS", 
        "StackEvent AWS::IAM::InstanceProfile NodeInstanceProfile DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIngressMastersAPITCP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup EtcdSG DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIngressNodesDNSTCP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupEgress MasterIntElbEgressAPI DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIngressNodesDNSUDP DELETE_COMPLETE", 
        "StackEvent AWS::IAM::User S3UserName DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupEgress InfraElbEgressHTTPS DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIntElbIngressMasters DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIngressExtLB DELETE_COMPLETE", 
        "StackEvent AWS::IAM::InstanceProfile MasterInstanceProfile DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress GlusterManagement DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIntElbIngressNodes DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress GlusterSsh DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress EtcdIngressEtcd DELETE_COMPLETE", 
        "StackEvent AWS::EC2::Instance InfraNode03 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress NodeIngressSsh DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupEgress InfraElbEgressHTTP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIngressNodesAPITCP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIntElbIngressMasters DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SubnetRouteTableAssociation PrivateSubnet3RTA DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupIngress EtcdIngressMasters DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIngressNodesDNSUDP DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Subnet PrivateSubnet2 DELETE_IN_PROGRESS", 
        "StackEvent AWS::IAM::InstanceProfile MasterInstanceProfile DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupIngress InfraIngressHTTPS DELETE_COMPLETE", 
        "StackEvent AWS::IAM::AccessKey CFNKeys DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupEgress MasterExtElbEgressAPI DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress MasterIngressIntLB DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress NodeIngressNodeKubelet DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress NodeIngressMasterKubelet DELETE_COMPLETE", 
        "StackEvent AWS::EC2::EIPAssociation BastionEipAssoc DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupEgress InfraElbEgressHTTPS DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupIngress LoggingUDP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress LoggingTCP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress NodeIngressNodeVXLAN DELETE_COMPLETE", 
        "StackEvent AWS::IAM::AccessKey CFNKeys DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroupIngress InfraIngressHTTP DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress InfraIngressHTTPS DELETE_IN_PROGRESS", 
        "StackEvent AWS::EC2::Instance AppNode02 DELETE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroupIngress GlusterDaemon DELETE_COMPLETE"
    ], 
    "failed": true, 
    "output": "Problem with CREATE. Rollback complete",

**Comment by cooktheryan** [comment]
If its possible will you login to AWS and look at the failed cloudformation
and find the line in the events that shows the initial failure? That may
give us a bit more information to see what part failed on and allow us to
clean up the other cloudformations that failed in the event there is an
naming clash

**Comment by cooktheryan** [comment]
Here is the last one I ran

./ose-on-aws.py --keypair=OSE-key --master-instance-type=t2.medium
--github-client-id=id --github-organization=openshift
--github-client-secret=secret--deployment-type=origin --ami=ami-6d1c2007
--public-hosted-zone=rcook-aws.sysdeseng.com

**Comment by nnachefski** [comment]
it deployed fine when i switched to OCP on Atomic AMI, which is what i wanted to do anyway.  Thanks for the help Ryan!
