### ISSUE TITLE
getting error as :TASK [openshift_examples : Import Centos Image streams] STDERR:  The connection to the server master:8443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/openshift-ansible-contrib#364]
I am trying to setup openshift on GCE,using ansible playbook.
i am getting below error:
TASK [openshift_examples : Import Centos Image streams] ***************************************************************************************
fatal: [master.35.184.246.97.nip.io]: FAILED! => {
    "changed": false, 
    "cmd": [
        "/usr/local/bin/oc", 
        "create", 
        "-n", 
        "openshift", 
        "-f", 
        "/etc/origin/examples/image-streams/image-streams-centos7.json"
    ], 
    "delta": "0:00:00.335746", 
    "end": "2017-05-16 14:22:32.639885", 
    "failed": true, 
    "failed_when_result": true, 
    "rc": 1, 
    "start": "2017-05-16 14:22:32.304139"
}
STDERR:
The connection to the server master:8443 was refused - did you specify the right host or port?

this is my /etc/hosts file:
35.188.16.62  infra.35.184.246.97.nip.io infra
35.184.246.97 master.35.184.246.97.nip.io master
104.154.114.167 node1.35.184.246.97.nip.io node1
104.154.220.137 node2.35.184.246.97.nip.io node2

and this is my inventory file:
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
ansible_become=yes

deployment_type=origin
openshift_release=v1.5.0
containerized=true
openshift_install_examples=true

# use htpasswd authentication with demo/demo
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_master_htpasswd_users={'demo': '$apr1$.MaA77kd$Rlnn6RXq9kCjnEfh5I3w/.'}

# put the router on dedicated infra node
openshift_hosted_router_selector='region=infra'
openshift_master_default_subdomain=origin.35.184.246.97.nip.io

# put the image registry on dedicated infra node
openshift_hosted_registry_selector='region=infra'

# project pods should be placed on primary nodes
osm_default_node_selector='region=primary'

[masters]
master.35.184.246.97.nip.io openshift_public_hostname="master.35.184.246.97.nip.io"

[nodes]
# master needs to be included in the node to be configured in the SDN
master.35.184.246.97.nip.io
infra.35.184.246.97.nip.io openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
node1.35.184.246.97.nip.io openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
node2.35.184.246.97.nip.io openshift_node_labels="{'region': 'primary', 'zone': 'default'}"

and my master logs says:

[root@master ~]# systemctl status origin-master.service
● origin-master.service
   Loaded: loaded (/etc/systemd/system/origin-master.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2017-05-16 15:57:14 UTC; 482ms ago
  Process: 12818 ExecStop=/usr/bin/docker stop origin-master (code=exited, status=1/FAILURE)
  Process: 12697 ExecStartPost=/usr/bin/sleep 10 (code=exited, status=0/SUCCESS)
  Process: 12696 ExecStart=/usr/bin/docker run --rm --privileged --net=host --name origin-master --env-file=/etc/sysconfig/origin-master -v /var/lib/origin:/var/lib/origin -v /var/log:/var/log -v /var/run/docker.sock:/var/run/docker.sock -v /etc/origin:/etc/origin openshift/origin:${IMAGE_VERSION} start master --config=${CONFIG_FILE} $OPTIONS (code=exited, status=255)
  Process: 12692 ExecStartPre=/usr/bin/docker rm -f origin-master (code=exited, status=1/FAILURE)
 Main PID: 12696 (code=exited, status=255)

May 16 15:57:14 master systemd[1]: origin-master.service: control process exited, code=exited status=1
May 16 15:57:14 master systemd[1]: Failed to start origin-master.service.
May 16 15:57:14 master systemd[1]: Unit origin-master.service entered failed state.
May 16 15:57:14 master systemd[1]: origin-master.service failed.
[root@master ~]# 

[root@master ~]# docker --version
Docker version 1.12.6, build 3a094bd/1.12.6
[root@master ~]# 

this is my dns setup on GCE
![dns](https://cloud.githubusercontent.com/assets/25741747/26115845/cf9380a2-3a7e-11e7-814e-ac25f11d27b7.png)
please help me on this

**Comment by naveenkumartangallapally** [comment]
Hi @ pschiffe ,

can u help me on this?

**Comment by pschiffe** [comment]
@naveenkumartangallapally well, the problem is that the service `origin-master.service` isn't running. But the reason is hard to tell. If you created only the instances by hand, there might be other gcp resources missing.. But, given only single master.. is the docker daemon running correctly? `systemctl status docker`, maybe post output of `journalctl -u docker`. and check just `journactl` if there isn't any error..

**Comment by naveenkumartangallapally** [comment]
this is the o/p of systemctl status docker

[root@master ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─custom.conf
   Active: active (running) since Tue 2017-05-16 16:40:22 UTC; 18h ago
     Docs: http://docs.docker.com
 Main PID: 3905 (dockerd-current)
   Memory: 57.4M
   CGroup: /system.slice/docker.service
           ├─3905 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current ...
           └─3909 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-container...

May 17 11:37:56 master dockerd-current[3905]: [701.094802ms] [701.064018ms] About to store object in database
May 17 11:37:56 master dockerd-current[3905]: "Create /api/v1/namespaces/openshift-infra/serviceaccounts"... END
May 17 11:37:56 master dockerd-current[3905]: I0517 11:37:56.013890       1 panics.go:76] POST /api/v1/na...238]
May 17 11:37:56 master dockerd-current[3905]: I0517 11:37:56.021351       1 panics.go:76] GET /oapi/v1/cl...238]
May 17 11:37:56 master dockerd-current[3905]: I0517 11:37:56.024627       1 panics.go:76] GET /oapi/v1/cl...238]
May 17 11:37:56 master dockerd-current[3905]: I0517 11:37:56.026780       1 panics.go:76] GET /oapi/v1/cl...238]
May 17 11:37:56 master dockerd-current[3905]: I0517 11:37:56.035605       1 panics.go:76] PUT /oapi/v1/cl...238]
May 17 11:37:57 master oci-register-machine[14990]: 2017/05/17 11:37:57 Register machine: poststop 4da3fcb...tfs
May 17 11:37:57 master dockerd-current[3905]: time="2017-05-17T11:37:57.698564202Z" level=info msg="{Acti...95}"
May 17 11:37:57 master dockerd-current[3905]: time="2017-05-17T11:37:57.767453356Z" level=info msg="{Acti...95}"
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by naveenkumartangallapally** [comment]
journalctl -u docker:
[journalctl -u docker.txt](https://github.com/openshift/openshift-ansible-contrib/files/1007567/journalctl.-u.docker.txt)

**Comment by naveenkumartangallapally** [comment]
journalctl o/p:

May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.241619       1 trace.go:61] Trace "Create /api/v1/namespaces/openshift-infra/serviceaccounts" (starte
May 17 11:46:35 master dockerd-current[3905]: [15.329µs] [15.329µs] About to convert to expected version
May 17 11:46:35 master dockerd-current[3905]: [27.456µs] [12.127µs] Conversion done
May 17 11:46:35 master dockerd-current[3905]: [701.305252ms] [701.277796ms] About to store object in database
May 17 11:46:35 master dockerd-current[3905]: "Create /api/v1/namespaces/openshift-infra/serviceaccounts" [703.258479ms] [1.953227ms] END
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.241693       1 panics.go:76] POST /api/v1/namespaces/openshift-infra/serviceaccounts: (703.617268ms) 
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.249336       1 panics.go:76] GET /oapi/v1/clusterroles/system:build-controller: (6.033179ms) 200 [[op
May 17 11:46:35 master docker[19447]: I0517 11:46:35.241619       1 trace.go:61] Trace "Create /api/v1/namespaces/openshift-infra/serviceaccounts" (started 2017-0
May 17 11:46:35 master docker[19447]: [15.329µs] [15.329µs] About to convert to expected version
May 17 11:46:35 master docker[19447]: [27.456µs] [12.127µs] Conversion done
May 17 11:46:35 master docker[19447]: [701.305252ms] [701.277796ms] About to store object in database
May 17 11:46:35 master docker[19447]: "Create /api/v1/namespaces/openshift-infra/serviceaccounts" [703.258479ms] [1.953227ms] END
May 17 11:46:35 master docker[19447]: I0517 11:46:35.241693       1 panics.go:76] POST /api/v1/namespaces/openshift-infra/serviceaccounts: (703.617268ms) 409 [[op
May 17 11:46:35 master docker[19447]: I0517 11:46:35.249336       1 panics.go:76] GET /oapi/v1/clusterroles/system:build-controller: (6.033179ms) 200 [[openshift/
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.256154       1 panics.go:76] GET /oapi/v1/clusterpolicybindings/:default: (6.229199ms) 200 [[openshif
May 17 11:46:35 master docker[19447]: I0517 11:46:35.256154       1 panics.go:76] GET /oapi/v1/clusterpolicybindings/:default: (6.229199ms) 200 [[openshift/v1.5.0
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.258555       1 panics.go:76] GET /oapi/v1/clusterpolicybindings: (1.797031ms) 200 [[openshift/v1.5.0+
May 17 11:46:35 master docker[19447]: I0517 11:46:35.258555       1 panics.go:76] GET /oapi/v1/clusterpolicybindings: (1.797031ms) 200 [[openshift/v1.5.0+031cbe4 
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.264202       1 panics.go:76] PUT /oapi/v1/clusterrolebindings/system:build-controller: (4.88805ms) 20
May 17 11:46:35 master docker[19447]: I0517 11:46:35.264202       1 panics.go:76] PUT /oapi/v1/clusterrolebindings/system:build-controller: (4.88805ms) 200 [[open
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.264534       1 ensure.go:84] Added build-controller service accounts to the system:build-controller c
May 17 11:46:35 master docker[19447]: I0517 11:46:35.264534       1 ensure.go:84] Added build-controller service accounts to the system:build-controller cluster r
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.269575       1 panics.go:76] GET /api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.273270       1 panics.go:76] POST /api/v1/namespaces/openshift-infra/serviceaccounts: (8.47453ms) 409
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.280237       1 panics.go:76] GET /oapi/v1/clusterroles/system:certificate-signing-controller: (5.5265
May 17 11:46:35 master docker[19447]: I0517 11:46:35.269575       1 panics.go:76] GET /api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&r
May 17 11:46:35 master docker[19447]: I0517 11:46:35.273270       1 panics.go:76] POST /api/v1/namespaces/openshift-infra/serviceaccounts: (8.47453ms) 409 [[opens
May 17 11:46:35 master docker[19447]: I0517 11:46:35.280237       1 panics.go:76] GET /oapi/v1/clusterroles/system:certificate-signing-controller: (5.526586ms) 20
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.284739       1 panics.go:76] GET /oapi/v1/clusterpolicybindings/:default: (4.073018ms) 200 [[openshif
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.287088       1 panics.go:76] GET /oapi/v1/clusterpolicybindings: (1.57532ms) 200 [[openshift/v1.5.0+0
May 17 11:46:35 master docker[19447]: I0517 11:46:35.284739       1 panics.go:76] GET /oapi/v1/clusterpolicybindings/:default: (4.073018ms) 200 [[openshift/v1.5.0
May 17 11:46:35 master docker[19447]: I0517 11:46:35.287088       1 panics.go:76] GET /oapi/v1/clusterpolicybindings: (1.57532ms) 200 [[openshift/v1.5.0+031cbe4 (
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.292318       1 panics.go:76] PUT /oapi/v1/clusterrolebindings/system:certificate-signing-controller: 
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.292517       1 ensure.go:84] Added certificate-signing-controller service accounts to the system:cert
May 17 11:46:35 master docker[19447]: I0517 11:46:35.292318       1 panics.go:76] PUT /oapi/v1/clusterrolebindings/system:certificate-signing-controller: (4.47579
May 17 11:46:35 master docker[19447]: I0517 11:46:35.292517       1 ensure.go:84] Added certificate-signing-controller service accounts to the system:certificate-
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.295669       1 panics.go:76] POST /api/v1/namespaces/openshift-infra/serviceaccounts: (2.869692ms) 40
May 17 11:46:35 master docker[19447]: I0517 11:46:35.295669       1 panics.go:76] POST /api/v1/namespaces/openshift-infra/serviceaccounts: (2.869692ms) 409 [[open
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.303727       1 panics.go:76] GET /oapi/v1/clusterroles/system:daemonset-controller: (6.6453ms) 200 [[
May 17 11:46:35 master docker[19447]: I0517 11:46:35.303727       1 panics.go:76] GET /oapi/v1/clusterroles/system:daemonset-controller: (6.6453ms) 200 [[openshif
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.306848       1 panics.go:76] GET /oapi/v1/clusterpolicybindings/:default: (2.554852ms) 200 [[openshif
May 17 11:46:35 master docker[19447]: I0517 11:46:35.306848       1 panics.go:76] GET /oapi/v1/clusterpolicybindings/:default: (2.554852ms) 200 [[openshift/v1.5.0
May 17 11:46:35 master dockerd-current[3905]: I0517 11:46:35.310501       1 panics.go:76] GET /oapi/v1/clusterpolicybindings: (3.076703ms) 200 [[openshift/v1.5.0+

**Comment by pschiffe** [comment]
Hm, the last log is not complete, please try `journalctl -b > journal.txt` and upload the file here.

**Comment by naveenkumartangallapally** [comment]
[journalctl.txt](https://github.com/openshift/openshift-ansible-contrib/files/1007636/journalctl.txt)

**Comment by pschiffe** [comment]
Well, still no idea. Only error seems to be `May 17 12:07:47 master dockerd-current[3905]: time="2017-05-17T12:07:47.073608401Z" level=error msg="Handler for POST /v1.24/containers/origin-master/stop returne` but I don't know what it means. You can try to reboot the vm and restart the master service, see what it will do. Maybe try to reinstall the package, or remove it and run the playbook again..

**Comment by pschiffe** [comment]
@naveenkumartangallapally any luck?

**Comment by pschiffe** [comment]
Feel free to reopen if you find out something.

**Comment by cooktheryan** [comment]
@aizuddin85 can you open a new issue on this? I don't want us to miss this

**Comment by aizuddin85** [comment]
@cooktheryan about to do so. Will link it here afterwards.

**Comment by aizuddin85** [comment]
Reopened new issue that related to this closed issue since  problem easily reproduced by making host ip clashes with SDN default IP: [Bug #767](https://github.com/openshift/openshift-ansible-contrib/issues/767)
