### ISSUE TITLE
Google Cloud refarch http proxy shouldn't just forward 8080 to the api service

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible-contrib#37]
Instead of leveraging kubeproxy, it would probably be better to stand up either apache or haproxy to forward only the healthz/ready endpoint rather than proxy the entire api behind 8080.

**Comment by smarterclayton** [comment]
Why not use an https health check?

**Comment by pschiffe** [comment]
@smarterclayton it doesn't work. Https health check is only supported with https load balancing. For network based lb and ssl proxy Google supports only http health checks. Hopefully this will change in the future.

**Comment by smarterclayton** [comment]
@liggitt we should consider exposing http 8080 health check on the master
(or another unused port)

**Comment by detiber** [comment]
@smarterclayton that would indeed help with the GCP use case, but almost seems a bit excessive to add it just for this singular use case.  We can add the haproxy support for proxying the health check directly to openshift-ansible and deploy it only when we detect that we are running on GCP.

**Comment by smarterclayton** [comment]
Ultimately there will probably be other things that only support HTTP.
Health checks should be easily accessible on everything since they don't
leak (much) information.
