### ISSUE TITLE
AWS Brownfield Bastion is named with Route53HostedZone instead of PublicHostedZone

### ISSUE THREAD

**Issue by dls314** [openshift/openshift-ansible-contrib#383]
I noticed that the EC2 name tag assigned to the bastion host in a brownfield deployment is using the Route53HostedZone parameter instead of the PublicHostedZone parameter which is used for naming the other nodes. This results in a trailing "." in the name tag for the bastion host.

I think this isn't the intent, and PublicHostedZone was meant instead.
Compare the bastion line to the ose-master01 line, below.

https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/aws-ansible/playbooks/roles/cloudformation-infra/files/brownfield.json#L832

https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/aws-ansible/playbooks/roles/cloudformation-infra/files/brownfield.json#L873

Anyone know about the intent here?

**Comment by cooktheryan** [comment]
If you have the code available submit a PR an I can take a look. I haven't had any install issues but consistency is important.
