### ISSUE TITLE
EC2 instances are not created and CF fails

### ISSUE THREAD

**Issue by mazzy89** [openshift/openshift-ansible-contrib#384]
I'm trying to spin up a new cluster on AWS with the following command:
```bash
./ose-on-aws.py \
--region=us-east-2 \
--keypair=openshift-infra \
--create-key=yes \
--key-path=/home/user/.ssh/id_rsa.pub \
--public-hosted-zone=mydomain.com \
--deployment-type=origin \
--ami=ami-18f8df7d \
--github-organization=#{GITHUB_ORGANIZATION} \
--github-client-secret=#{GITHUB_CLIENT_SECRET} \
--github-client-id=#{GITHUB_CLIENT_ID} \
--containerized=true \
--no-confirm \
--verbose
```

Unfortunately I got back the following error from CF:

<img width="1890" alt="screen shot 2017-05-23 at 10 25 05" src="https://cloud.githubusercontent.com/assets/5463218/26345687/f456d19e-3fa3-11e7-85e5-4fdef3742582.png">

No message and no way to enhance debug. do you have any idea? It seems that it's not possible to create only EC2 resources

**Comment by jcperezamin** [comment]
Please, check the ami ID, I used this ami-10f53a06

**Comment by mazzy89** [comment]
Yep this solve the issue. Thank you @jcperezamin
