### ISSUE TITLE
No hosts file under /etc/ansible

### ISSUE THREAD

**Issue by mazzy89** [openshift/openshift-ansible-contrib#406]
I've installed Openshift Origin by executing `ose-on-aws.py`. The cluster is now operative but I'd like to install metrics and logging. According to the documentation I should follow the [Advanced Installation](https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-ansible). I'm not able to find `/etc/ansible/hosts` file to configure Ansible. Any idea about that? My idea was to use `- include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml` but what should I use as inventory? The EC2 hosts inventory or a plain file configured as wanted?

**Comment by cooktheryan** [comment]
@mazzy89 probably at this point you should be sick of seeing my nick.

So there isn't a file placed in /etc/ansible/hosts as the inventory is created dynamically by ansible. There is this to create a static inventory https://access.redhat.com/documentation/en-us/reference_architectures/2017/html/deploying_openshift_container_platform_3.5_on_amazon_web_services/installation_failure#inventory 

I just realized it is missing a parameter to set containerized true or false upon inventory creation.  

AS for the byo/config.yml the playbook is actually called within https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/aws-ansible/playbooks/openshift-setup.yaml

**Comment by mazzy89** [comment]
Hi @cooktheryan well I definitely could say the same for you :-D no way thanks a lot for jumping on the issue in a quick way. Nice catch I didn't know it is possible to create an inventory file. I will go definitely with that way reminding that `containerized` must be changed after the creation of the inventory

**Comment by mazzy89** [comment]
@cooktheryan also `deployment_type`

**Comment by cooktheryan** [comment]
if you can PR it I can review...im away from real keyboard right now
