### ISSUE TITLE
The ose-on-aws.py --rhsm-pool parameter does not work with Subscription Management Pool ID's

### ISSUE THREAD

**Issue by nickschuetz** [openshift/openshift-ansible-contrib#425]
The rhsm-pool parameter only seems to work when using Subscription Name. When passed the Subscription Management Pool ID (A fully numeric value) it does not seem to work properly and fails to attach the given pool.

Here's a snipit from `ose-on-aws.py --help`:

>  --rhsm-pool TEXT                Red Hat Subscription Management Pool ID or Subscription Name

**Comment by cooktheryan** [comment]
Excellent find. Will resolve

**Comment by pschiffe** [comment]
This also affects GCP and probably others. Related PR #422 , but I don't think that's a correct fix.
