### ISSUE TITLE
Add the ability to add Aggregated Container Logging with EBS Storage at install time

### ISSUE THREAD

**Issue by nickschuetz** [openshift/openshift-ansible-contrib#429]
As a user I want the ability to add the aggregated container logging (EFK) feature to my installation. With this I would like to have ES and Kibana span all the infra nodes. It would be nice to have individual EBS storage for all three clustered ES instances as recommended by: https://docs.openshift.com/container-platform/3.5/install_config/aggregate_logging.html#aggregated-elasticsearch

**Comment by cooktheryan** [comment]
This has been merged in
