### ISSUE TITLE
./gcloud.sh fails when tmp-instance disk is present but instance is not

### ISSUE THREAD

**Issue by bdurrow** [openshift/openshift-ansible-contrib#438]
TASK [deployment-create : check if deployment osd03-tmp-instance exists] **********************************************************************************************************
ok: [localhost]

TASK [deployment-create : debug] **************************************************************************************************************************************************
skipping: [localhost]

TASK [deployment-create : create deployment osd03-tmp-instance] *******************************************************************************************************************
skipping: [localhost]

TASK [refresh gce inventory] ******************************************************************************************************************************************************
ok: [localhost]

TASK [ssh-config-tmp-instance : configure ssh for ocp temp instance] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.hostvars.HostVars object' has no attribute u'osd03-tmp-instance'\n\nThe error appears to have been in '/home/brad/openshift-ansible-contrib/reference-architecture/gce-cli/ansible/playbooks/roles/ssh-config-tmp-instance/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: configure ssh for ocp temp instance\n  ^ here\n"}

**Comment by bdurrow** [comment]
Ultimately I had to gcloud --project openshift-dev-03 deployment-manager deployments delete osd03-tmp-instance.  So it seems that the logic checks that the deployment exists and if it does it then assumes the instance exists.  I think that I probably had an illegal imageSource definition in my configuration in that deployment.  After I fixed the problem the deployment didn't get updated because it already exists.

**Comment by pschiffe** [comment]
Correct, it checks only whether the deployment exists. Best fix, for now, is to teardown the infra and recreate it when you encounter similar problem again `./gcloud.sh --teardown && ./gcloud.sh`. I'll see if I can check also the deployment state and not only its existence.

Thanks for the PR and the issue, feel free create more issues if you encounter more problems.

**Comment by pschiffe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(8) OpenShift-Ansible-Contrib issues and PRs](https://trello.com/c/sdrFM9Dv/800-8-openshift-ansible-contrib-issues-and-prs)
