### ISSUE TITLE
containerized install fails to restart origin-master-api service without reboot

### ISSUE THREAD

**Issue by bdurrow** [openshift/openshift-ansible-contrib#447]
[cloud-user@osacpr00-master-p8tg ~]$ sudo systemctl restart origin-master-api
Job for origin-master-api.service failed because the control process exited with error code. See "systemctl status origin-master-api.service" and "journalctl -xe" for details.
[cloud-user@osacpr00-master-p8tg ~]$ sudo systemctl status origin-master-api.service | cat
● origin-master-api.service - Atomic OpenShift Master API
   Loaded: loaded (/etc/systemd/system/origin-master-api.service; enabled; vendor preset: disabled)
   Active: activating (start-post) (Result: exit-code) since Thu 2017-06-08 20:31:48 UTC; 6s ago
     Docs: https://github.com/openshift/origin
  Process: 2157 ExecStop=/usr/bin/docker stop origin-master-api (code=exited, status=1/FAILURE)
  Process: 2197 ExecStart=/usr/bin/docker run --rm --privileged --net=host --name origin-master-api --env-file=/etc/sysconfig/origin-master-api -v /var/lib/origin:/var/lib/origin -v /var/log:/var/log -v /var/run/docker.sock:/var/run/docker.sock -v /etc/origin:/etc/origin -v /etc/origin/cloudprovider:/etc/origin/cloudprovider openshift/origin:${IMAGE_VERSION} start master api --config=${CONFIG_FILE} $OPTIONS (code=exited, status=125)
  Process: 2191 ExecStartPre=/usr/bin/docker rm -f origin-master-api (code=exited, status=1/FAILURE)
 Main PID: 2197 (code=exited, status=125);         : 2198 (sleep)
   Memory: 84.0K
   CGroup: /system.slice/origin-master-api.service
           └─control
             └─2198 /usr/bin/sleep 10

Jun 08 20:31:48 osacpr00-master-p8tg systemd[1]: Starting Atomic OpenShift Master API...
Jun 08 20:31:48 osacpr00-master-p8tg origin-master-api[2191]: Error response from daemon: No such container: origin-master-api
Jun 08 20:31:48 osacpr00-master-p8tg origin-master-api[2197]: /usr/bin/docker-current: Error response from daemon: devmapper: Error activating devmapper device for '0e92887c9910f82a424e0ba97a8bbbbbca33b663394adc611b0c6132fa8c1e5c-init': devicemapper: Can't set cookie dm_task_set_cookie failed.
Jun 08 20:31:48 osacpr00-master-p8tg origin-master-api[2197]: See '/usr/bin/docker-current run --help'.
Jun 08 20:31:48 osacpr00-master-p8tg systemd[1]: origin-master-api.service: main process exited, code=exited, status=125/n/a
[cloud-user@osacpr00-master-p8tg ~]$ sudo docker --version
Docker version 1.12.6, build 1398f24/1.12.6
[cloud-user@osacpr00-master-p8tg ~]$ sudo rpm -q docker
docker-1.12.6-28.git1398f24.el7.centos.x86_64

**Comment by bdurrow** [comment]
It seems like all deployment now fail because of this:
```
RUNNING HANDLER [openshift_metrics : restart master controllers] ***************
fatal: [gca-dev-00-master-tfmk]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-master-controllers: Job for origin-master-controllers.service failed because the control process exited with error code. See \"systemctl status origin-master-controllers.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by bdurrow** [comment]
Perhaps related: https://github.com/moby/moby/issues/23089

**Comment by pschiffe** [comment]
I wasn't able to reproduce this issue on RHEL and openshift enterprise, so probably issue with centos and docker, as suggested.

**Comment by bdurrow** [comment]
When I worked around #454 this problem was resolved.

**Comment by yves-vogl** [comment]
We had the same issue with Atomic Host and OpenShift Origin 3.9 when enabled VMware and Metrics.
