### ISSUE TITLE
GCE Multizone Deployment doesn't properly honor PV requirement when scheduling

### ISSUE THREAD

**Issue by bdurrow** [openshift/openshift-ansible-contrib#453]
I apologize that I don't understand this problem well enough to succinctly describe it.

I spun up a cluster using master@d10ce131203d6add4baa3d156e9563095ac4703d with the patches necessary to deploying using CentOS/Origin this included the following lines in config.yaml:

```
[brad@ansible gce-cli]$ fgrep metric config.yaml
openshift_hosted_metrics_deploy: true
openshift_hosted_metrics_storage_volume_size: 20Gi
```

After the cluster is built there is a pv bound to a pvc like this:
```
Brads-MBP13:~ brad$ oc get pvc
NAME                  STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
metrics-cassandra-1   Bound     pvc-bfeef7c3-4cdf-11e7-8a2f-42010a80000a   20Gi       RWO           10h
```

I also made these changes after the cluster came up:
```
::::::::::::::
/tmp/gce-pd-storageclass-ssd.yaml
::::::::::::::
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
::::::::::::::
/tmp/gce-pd-storageclass-standard.yaml
::::::::::::::
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard

 sudo /usr/local/bin/oc create -f /tmp/gce-pd-storageclass-standard.yaml
 sudo /usr/local/bin/oc create -f /tmp/gce-pd-storageclass-ssd.yaml  
```

Then I started troublehsooting the problem described in #446.  I changed the image part of the replication controller config and deleted the existing POD so it would get redeployed.  The scheduler assigned it to a node in the wrong zone.  Initially I thought the volume wasn't labeled properly but that doesn't appear to be the case:
```
Brads-MBP13:~ brad$ oc describe pv pvc-bfeef7c3-4cdf-11e7-8a2f-42010a80000a
Name:		pvc-bfeef7c3-4cdf-11e7-8a2f-42010a80000a
Labels:		failure-domain.beta.kubernetes.io/region=us-central1
		failure-domain.beta.kubernetes.io/zone=us-central1-b
StorageClass:
Status:		Bound
Claim:		openshift-infra/metrics-cassandra-1
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	20Gi
Message:
Source:
    Type:	GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:	kubernetes-dynamic-pvc-bfeef7c3-4cdf-11e7-8a2f-42010a80000a
    FSType:
    Partition:	0
    ReadOnly:	false
No events.
```

I tried to work around the problem by deleteing the pod until it was schedule on a node in the correct zone but it still won't mount the volume.

Contrast this with what happens for the pvcs that were created to support fabric8 pods.  Those pvs were created and bound after I did the dynamic provisioning steps mentioned above.  I deleted the fabric8-docker-registry pod and it was immediately recreated and the volume mounted.

I can rule out that the getting scheduled on a node in the right zone but different than the one that previously had the volume because I only have one master, infra and regular node in each of three zones (9 total nodes) and only the regular nodes are labeled such that these PODS get scheduled to them.

I'm happy to provide any output that would help but I don't know how to get logs from the scheduler or know what else would help.

**Comment by cooktheryan** [comment]
I think this is the downside to multi-zone deployment. For example when i create a storageclass in AWS I actually specify a specific AZ for the storage class.  This is resolved in storage solutions such as CNS, CRS, or NFS. 

The downside of the installation based installation of metrics is that you don't really have much a choice where items land.  A work around when using pvc, storage classes, and even dcs is to specify a zone for the storage to ensure that the pods are always launched in a location of storage.

**Comment by bdurrow** [comment]
I'm not sure if you noticed in my problem report but it appears that pvs bound to pvs created after the cluster is already up behave properly.

**Comment by bdurrow** [comment]
The PVC currently uses annotation
volume.alpha.kubernetes.io/storage-class: "dynamic"

This commit advances the annotation to volume.beta...
https://github.com/openshift/openshift-ansible/commit/521ebaf9eecc38029cfe6fe0e10a13888cb3f83e

**Comment by pschiffe** [comment]
@bdurrow could you try to deploy your ocp with the updated openshift installer on release-1.5 branch + the change from https://github.com/openshift/openshift-ansible/commit/521ebaf9eecc38029cfe6fe0e10a13888cb3f83e ? As I'm not really sure if this problem belongs to the ref. arch. or to the installer.

**Comment by bdurrow** [comment]
There are a number of problems with the metrics deployment.  I'm not sure if they are all related to the "installer".  The openshift-infra namespace doesn't have a node selector after deployment (correction it does but it is set to "").  The original deployment of metrics happens to role=infra labeled nodes but after that nodes selected with the default node selector.  Also the kubernetes.io/gce-pd doesn't successfully unmount the filesystem from the host when I terminate the POD so the volume isn't available to the next node where the pod gets scheduled (because of the node selector circumstances killing the pod will always try to schedule on a different node because the infra node it is initially started on doesn't meet the requirements for the node selector).  I'm not sure if this is related to openshift/openshift-ansible@521ebaf.  I have found that if I manually edit the pvc to have the following and also fix the node selector in the namespace the problem goes away (or is masked by the fact that only one node matches the selection criteria).
```
    volume.beta.kubernetes.io/storage-class: standard
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
```
I think to fully test this I would need to have 2 infra nodes in the same availability zone.  I don't have the bandwidth to fully address all the problems with metrics deployment this week.  I'll try to pick it up in a few days.

Ultimately to work around the problem I have to:
1) Add this line to my config.yaml before deployment: openshift_hosted_metrics_deployer_version: 'v1.5.1'
2) Define Storage Classes (after deployment)
3) Modify the metrics-cassandra-1 PVC (as indicated above)
4) Modify the openshift-infra namespace to have the correct node selector
5) Reboot the infra node where the cassandra volume is attached

I don't know if some of these steps aren't necessary.  Ideally I would be able to handle 2-4 using the installer.

**Comment by pschiffe** [comment]
So, with 3.6 + couple of fixes done in this repo, this issue shouldn't be a problem any more. OCP on GCP now has 2 storage classes defined by default (`standard` and `ssd`) and `openshift-infra` namespace has infra node selector defined. By increasing the minimum number of nodes to 3 of each kind (3 masters, 3 infra nodes and 3 app nodes), pvs should be always created in a zone where is a node (at least until https://github.com/kubernetes/kubernetes/issues/50115 is resolved).
