### ISSUE TITLE
[Openstack provider] persist nameservers by networkmanager via dnsmasq deployed by openshift-ansible

### ISSUE THREAD

**Issue by bogdando** [openshift/openshift-ansible-contrib#455]
Testing OpenShift origin on OpenStack, with Centos7 servers provisioned by Heat.
The networkmanager config needs to persist nameservers to the hosts' /etc/resolv.conf or better off to the dnsmasq deployed. The current [code](https://github.com/openshift/openshift-ansible-contrib/blob/d81278c8e4b28f0ff756219d174a3ceef57056e4/playbooks/provisioning/openstack/post-provision-openstack.yml#L46) does not persist that `private_dns_server` and the hacked /etc/resolv.conf entry will be removed after the ``systemctl restart network`` command or a reboot.

**Comment by bogdando** [comment]
https://github.com/openshift/openshift-ansible-contrib/pull/397/files#r121722908

**Comment by bogdando** [comment]
While the fix works for hosts, containers seem still receiving nameservers in a wrong order:

See the snippet that demonstrates the name resolve issues, both for the service FQDN from within deployed openshift cluster, and from the container of an example cakePHP app to external resources (github) https://pastebin.com/V1c91juW

The failed container's config:
```
[openshift@app-node-0 ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                                                                                             COMMAND                  CREATED             STATUS                      PORTS               NAMES
564693ddddb3        openshift/origin-sti-builder:v1.5.1                                                               "/usr/bin/openshift-s"   19 minutes ago      Exited (1) 18 minutes ago                       k8s_sti-build.8a7c96a8_cakephp-mysql-example-1-build_foo_370d1312-529e-11e7-a284-fa163e18994e_78b81144

[openshift@app-node-0 ~]$ sudo docker cp 564693ddddb3:/etc/resolv.conf /tmp/resolv.conf
[openshift@app-node-0 ~]$ cat /tmp/resolv.conf
search foo.svc.cluster.local svc.cluster.local cluster.local openstacklocal openshift.cluster.lc
nameserver 172.30.0.1
nameserver 192.168.99.8
nameserver 192.168.1.1
nameserver 8.8.8.8
```

**Comment by bogdando** [comment]
The command dig cakephp-mysql-example-foo.apps.openshift.cluster.lc @<dns-0-floating-IP> works from my laptop. So it seems I have only bad DNS config for container that prevents it to resolve external names.

**Comment by bogdando** [comment]
@tomassedovic @oybed I need some help please with understanding the `private_dns_server` vs `openshift.common.kube_svc_ip` placement as an authoritative DNS server for the cluster DNS domain.

**Comment by tomassedovic** [comment]
What if we just modify our Neutron subnet to use our DNS? That way we don't need to configure anything on the nodes and just let openshift do its thing. It should persist across reboots and everything.

So after we deploy the named server, we would just run this command:

openstack subnet set --no-dns-nameserver --dns-nameserver DNS_IP SUBNET_NAME
