### ISSUE TITLE
[Openstack provider] Installation of provisioning prerequisites must be automated for cluster nodes

### ISSUE THREAD

**Issue by bogdando** [openshift/openshift-ansible-contrib#468]
Provision prerequisites (for cluster nodes) must be covered by some automation. We can not expect users to ssh to nodes and install prerequisites once they provisioned nodes on top of OpenStack cloud with a Heat stack. User_data could help to address that.

For localhost played roles/tasks, it is OK to leave them only documented perhaps.

**Comment by bogdando** [comment]
@oybed @tomassedovic

**Comment by tomassedovic** [comment]
It's already there, isn't it?

https://github.com/openshift/openshift-ansible-contrib/blob/master/playbooks/provisioning/openstack/README.md#dependencies

**Comment by bogdando** [comment]
@tomassedovic yes, in docs. I'll submit a patch to install the package as well

**Comment by bogdando** [comment]
Ok, there is localhost requirements, which is ok to not automate I suppose. This ticket is for addressing requirements (if any) for the cluster nodes. Sorry for confusion!

**Comment by tomassedovic** [comment]
Closing this. All packages the cluster nodes require are installed by the playbooks, no manual work required.
