### ISSUE TITLE
README adoc requires prerequisite of atomic-openshift-utils

### ISSUE THREAD

**Issue by rlopez133** [openshift/openshift-ansible-contrib#476]
The readme https://github.com/openshift/openshift-ansible-contrib/tree/master/playbooks/provisioning/openstack makes no mention of requiring `atomic-openshift-utils`. This is required if you want to use the `byo/config.yml` that exists within `/usr/share/ansible/openshift-ansible/playbooks/byo/config.yml` not the one upstream

@tomassedovic

**Comment by tomassedovic** [comment]
Where should this be installed? On the Ansible host (the computer executing the openstack provider playbooks) or on the deployed nodes?

**Comment by rlopez133** [comment]
should be deployed on the Ansible host (the computer executing the openstack provider playbooks)

**Comment by bogdando** [comment]
would be nice to use a [container](https://hub.docker.com/r/karafior/atomic-openshift-utils/) to allow openshift installed from any OS type
