### ISSUE TITLE
Readme prereq - python-openstackclient

### ISSUE THREAD

**Issue by rlopez133** [openshift/openshift-ansible-contrib#479]
The `https://github.com/openshift/openshift-ansible-contrib/tree/master/playbooks/provisioning/openstack` readme file makes no mention of requiring  the package `python-openstackclient` . Please add this as a prereq as it will be required for the ansible deployment to be able to use commands such as 'openstack server list` etc. 

@tomassedovic

**Comment by bogdando** [comment]
@rlopez133 is it for localhost (aka ansible admin node)?

**Comment by rlopez133** [comment]
yes @bogdando
