### ISSUE TITLE
The host installing OCP on OSP requires openstack repository

### ISSUE THREAD

**Issue by rlopez133** [openshift/openshift-ansible-contrib#480]
Within the readme https://github.com/openshift/openshift-ansible-contrib/tree/master/playbooks/provisioning/openstack , please include a prereq that the repository `rhel-7-server-openstack-10-rpms` is required in order to install the `python-openstackclient`

NOTE: This should be on the ansible host that does all the provisioning. 

@tomassedovic

**Comment by bogdando** [comment]
@rlopez133 thank you for thorough testing and pointing out those gaps in the docs!

**Comment by oybed** [comment]
May I suggest using the control host that was originally paired with this provisioning code? In that way all requirements are met:
https://github.com/redhat-cop/casl-ansible/tree/master/docker/control-host-openstack

**Comment by tomassedovic** [comment]
For the record, python-openstackclient is not required for the deployment. It is however quite useful to have so we should document it in optional dependencies.

**Comment by bogdando** [comment]
Yeah, not a requirement, just a nice to have for debugging
