### ISSUE TITLE
add ICMP to security groups that create the ocp instances

### ISSUE THREAD

**Issue by rlopez133** [openshift/openshift-ansible-contrib#485]
The playbooks in https://github.com/openshift/openshift-ansible-contrib/tree/master/playbooks/provisioning/openstack , when creating the instances don't have ICMP enabled on the security groups. If you could please add that as not being able to ping systems can make it hard to troubleshoot.

@tomassedovic

**Comment by bogdando** [comment]
will do that as a follow up to that https://github.com/openshift/openshift-ansible-contrib/pull/488 . Adding ICMP to the common sec group (and dns secgroup) will make more sens after that patch merged.
