### ISSUE TITLE
AWS  - question

### ISSUE THREAD

**Issue by stuartbfox** [openshift/openshift-ansible-contrib#49]
Is anyone working on auto scaling groups? 
If not I wouldn't mind starting on it

**Comment by detiber** [comment]
I'm starting some work here: https://github.com/openshift/openshift-ansible-contrib/pull/41

I plan to have ASG support for infra nodes and application nodes added to that PR by the end of the day.

The work is still pretty rough, but it is going to be the basis for supported ansible-based AWS provisioning for OpenShift.

**Comment by stuartbfox** [comment]
Excellent! Let me know if you need a hand with anything

**Comment by detiber** [comment]
@stuartbfox didn't quite get to adding the ASG support today (Wed), will pick back up on it tomorrow (Thu).
