### ISSUE TITLE
[Openstack provider] re-apply of the post-provision tasks fails with "Add DNS A records"

### ISSUE THREAD

**Issue by bogdando** [openshift/openshift-ansible-contrib#494]
If provision playbook re-applied, the task "Add DNS A records" fails with rc:2 and logs looking like:

```
failed: [localhost] (item=({u'key_algorithm': u'hmac-sha256', u'zone': u'openshift.cluster.lc', u'key_name':
u'private-openshift.cluster.lc', u'server': u'<dns_public_ip>', u'key_secret': u'<some_secret>', u'view':
u'private'}, {'ip': u'192.168.99.4', 'hostname': u'master-0', 'type': u'A'})) => {"changed": false, "dns_rc": 
2, "dns_rc_str": "SERVFAIL", "failed": true, "item": [{"key_algorithm": "hmac-sha256", "key_name": 
"private-openshift.cluster.lc", "key_secret": "<some_secret>", "server": "<dns_public_ip>", "view": 
"private", "zone": "openshift.cluster.lc"}, {"hostname": "master-0", "ip": "192.168.99.4", "type": "A"}], 
"msg": "Failed to create DNS record (rc: 2)"}
```

**Comment by tomassedovic** [comment]
I've verified this. Running the provision playbook and then re-running the same thing without changes fails updating the DNS records.

The nsupdate keys are different each time.

**Comment by tomassedovic** [comment]
I think we absolutely want to keep the provision playbooks idempotent. So I propose we require that the users generate their keys up front for now (and document how to do it in the readme as well as the sample `all.yml`)

We will want to autogenerate the keys going forward, but I'd like to have that in a separate playbook/role that would make sure the keys doesn't change across runs.

/cc @oybed

**Comment by bogdando** [comment]
I found there is named startup issues preventing it from reading zones:
```
Jun 23 14:33:44 host-192-168-99-12 named[937]: zone openshift.cluster.lc/IN/public: journal rollforward failed: journal out of sync with zone
Jun 23 14:33:44 host-192-168-99-12 named[937]: zone openshift.cluster.lc/IN/public: not loaded due to errors.
```

**Comment by bogdando** [comment]
Perhaps the fix will be both updating facts to catch up new keys AND do some dances with jorunal files as well

**Comment by oybed** [comment]
@bogdando as mentioned before, these roles are moving out of `contrib` and it has already been changed in the other repo:
https://github.com/redhat-cop/infra-ansible/pull/24

**Comment by oybed** [comment]
@tomassedovic FYI ^^

**Comment by bogdando** [comment]
@oybed I'm not sure how to sync changes ongoing for several places

**Comment by oybed** [comment]
@bogdando @tomassedovic please see the following PR for how I'm proposing to use `ansible-galaxy` to manage the inter-repo dependency. Maybe something to consider for `contrib` as well?
https://github.com/redhat-cop/casl-ansible/pull/49
