### ISSUE TITLE
Role 'rhel_subscribe' not found - vSphere Ref Arch

### ISSUE THREAD

**Issue by jtcressy** [openshift/openshift-ansible-contrib#527]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

# BUG REQUEST INFO:

**Environment**:
- **Cloud provider:** vSphere

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** Fedora 25

- **Version of Ansible:** (`ansible --version`): 2.3.1.0

- **Version of Jinja:** 2.9.6

- **Version of Shade:** 1.22.2

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):** 27f0424

**Copy of used inventory files and custom variables (please omit your secrets!):**

```
[vmware]
# console port and install type for OpenShift
console_port=8443
# choices are: openshift-enterprise or origin
deployment_type=origin

# OpenShift Version
openshift_vers: v3_5

# vCenter host address/username and password
vcenter_host=vcenter.crl.coloradomesa.edu
vcenter_username=openshift
vcenter_password=

# name of RHEL template to use for OpenShift install
vcenter_template_name=basecentos

# folder/cluster/resource pool in vCenter to organize VMs
vcenter_folder=Production Servers/OpenShift
vcenter_datastore=MainVol
vcenter_cluster=VMServs
vcenter_resource_pool=servers/OpenShift
vcenter_datacenter=CSMS Server Room

# DNS zone where everything will be hosted and app wildcard prefix
public_hosted_zone=cloud.crl.coloradomesa.edu
app_dns_prefix=apps

# DNS/gateway/interface name the OpenShift nodes should utilize
vm_dns=172.16.1.10,172.16.1.11
vm_gw=192.168.246.1
vm_netmask=24
vm_network="Containers"

# red hat subscription name and password
rhel_subscription_user=
rhel_subscription_pass=

# Internal satellite 6 server
rhel_subscription_server=

# pool with openshift repo access
rhel_subscription_pool=Red Hat OpenShift Container Platform

# bringing your own load balancer?
byo_lb=no
lb_host=haproxy-0

# bringing your own NFS server for registry?
byo_nfs=no
nfs_host=nfs-0
nfs_registry_mountpoint=/exports

#create_inventory vars
# number of nodes of each type
master_nodes=2
infra_nodes=3
app_nodes=3
storage_nodes=0

# start node IP address *must be a contiguous space
vm_ipaddr_start=192.168.246.100

# node hostname prefix
ocp_hostname_prefix=ocp-prod

# create_ocp_vars vars
# ldap bind user/password and FQDN ldap domain
# valid auth_types: none, ldap
auth_type=ldap
ldap_user=openshift
ldap_user_password=
ldap_fqdn=ad.crl.coloradomesa.edu

# Deplot OpenShift Metrics
openshift_hosted_metrics_deploy=true

# OpenShift SDN (default value redhat/openshift-ovs-subnet)
openshift_sdn=redhat/openshift-ovs-subnet

# Containerized installation of OpenShift
containerized: false

# persistent container storage: none, crs, cns
container_storage=none
```

**Command used to invoke ansible**: N/A, does not get to this step.

**Anything else do we need to know**:
Followed steps in https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/vmware-ansible
and stopped on ``./ocp-on-vmware.py`` after doing ``--create_ocp_vars`` and ``--create_inventory``.
Error output contains title above: ``ERROR: role 'rhel_subscribe' not found``
and lists all the directories it searches for roles in, including the ``roles`` directory in the root of this repo.

I'm just trying to deploy OpenShift origin using CentOS hosts on a vSphere cluster so that i can use the underlying vSphere Cloud Provider to schedule storage via vmdk on a datastore using ``kubernetes.io/vsphere-volume`` volume plugin.

**Comment by cooktheryan** [comment]
If you can either do a symlink or just clone openshift-ansible to
/usr/share/ansible/openshift-ansible

Underneath that directory you will then see roles.


Ryan

**Comment by jtcressy** [comment]
Oh, ok. i'll give that a try. I did notice some correlations to that other repo.

**Comment by jtcressy** [comment]
This solves the issue. Clone the openshift-ansible repo to /usr/share/ansible/openshift-ansible.
