### ISSUE TITLE
Move openshift_master_identity_providers from playbooks/openshift-setup.yaml

### ISSUE THREAD

**Issue by stuartbfox** [openshift/openshift-ansible-contrib#53]
Hi again :)

I tried moving `openshift_master_identity_providers:` from `playbooks/openshift-setup.yaml` to `playbooks/vars/main.yaml` so I can use a different oauth provider without editing a core playbook.
I commented the provider out of `openshift-setup.yaml` but always ended up with the default DenyAll provider when I put it in `vars/main.yaml`
I'd like the ability to change the oauth provider per env so using the `--env-file=`  feature in #39 

Use case is to have this repo as a git submodule of a larger deployment system that manages multiple IaaS providers and environments. I dont want to have to modify an upstream repo

**Comment by cooktheryan** [comment]
Ya we got bit when we switched to ansible 2.x due to no longer being able to include vars_files with an include statement.

**Comment by stuartbfox** [comment]
I dont mind fixing the code but Im not much of an ansible guy so not sure where to start :)

**Comment by cooktheryan** [comment]
Let me look at the auth providers and see if there are generic items in all of them. It may be something we could remedy at run time or by passing variables from somewhere.

**Comment by detiber** [comment]
Would it make more sense to set this using set_fact, so that it can be set only if it isn't already set?

Of course, that would assume calling the playbooks outside of the cli tooling.

**Comment by stuartbfox** [comment]
I'll need to fix this as part of an upcoming PR (per_env_vars) and also expose many more OCP config items. Any thoughts on how to solve this before I get going?
