### ISSUE TITLE
The Heat stack hosting OpenShift cluster is highly ephemeral and requires data persistence for clusters deployed

### ISSUE THREAD

**Issue by bogdando** [openshift/openshift-ansible-contrib#533]
# BUG REQUEST INFO:

**Environment**:
- **Cloud provider:** Openstack

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** any

- **Version of Ansible:** (`ansible --version`): 2.3.1

- **Version of Jinja:** (`pip freeze | grep -i jinja`) N/A

- **Version of Shade:** (`pip freeze | grep -i shade`) 1.21, os-client-config==1.27.0

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):** 7ce0793

**Copy of used inventory files and custom variables (please omit your secrets!):** N/A

**Command used to invoke ansible**:
the provision playbook

**Output of ansible run**:
N/A

**Anything else do we need to know**:

Some stack update actions, like changing ssh keys to be sent via cloud init, destroys and recreates VMs. This makes any deployed OpenShift clusters w/o a shared storage, like Ceph, *highly* ephemeral. The data, like etcd keys and certificates and what else k8s/openshift needs, must be kept on persistent volumes and survive VMs recreation/migration.

**Comment by ioggstream** [comment]
@bogdando: I found an issue in persisting root volumes attached to heat hosts.

In case of a failed node, a 

```
openstack stack resource mark unhealthy ....
openstack stack update ... --existing
```

The following happens:
1- heat creates a new node to replace the unhealthy one. This happens *before* heat removes the new one!
2- heat tries to attach the root volume to the new node
3- this fail as the root volume is attached to the old node.


If you look at the 'programmable infrastructure' paradigm, it should be preferable to programmatically replace a single node (eg while just retaining data volumes) than to attach a root volume to eg. a new flavored server.

**Comment by ioggstream** [comment]
@bogdando for further limiting host replacement, you can see restricted_actions. https://docs.openstack.org/heat/latest/template_guide/environment.html#restrict-update-or-replace-of-a-given-resource 

Let me know,
R.

**Comment by bogdando** [comment]
thanks @ioggstream !

**Comment by ioggstream** [comment]
@bogdando let us know if that works. I actually made a lot of work on the openshift-on-openstack repo and it won't be hard to backport most of that work here. You can check relevant patches there.
