### ISSUE TITLE
Failure downloading https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm

### ISSUE THREAD

**Issue by clintea** [openshift/openshift-ansible-contrib#544]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

# BUG REQUEST INFO:

**Environment**:
- **Cloud provider:**

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** Ubuntu 17.04 

- **Version of Ansible:** (`ansible --version`): 2.2.1.0

- **Version of Jinja:** (`pip freeze | grep -i jinja`)

- **Version of Shade:** (`pip freeze | grep -i shade`)

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):**

**Copy of used inventory files and custom variables (please omit your secrets!):**

**Command used to invoke ansible**: using Vagrant to setup a cluster with openshift origin 

**Output of ansible run**:
TASK [package] *****************************************************************                                                                                                  
fatal: [admin1]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm, 'NoneType
' object has no attribute 'read'"}    

**Anything else do we need to know**:
File openshift-ansible-contrib/vagrant/tasks/install_bootstrap_origin.yaml should use epel-release-7-10.noarch.rpm because release-7-9 no longer exists in https://dl.fedoraproject.org/pub/epel/7/x86_64/e/

**Comment by e-minguez** [comment]
I think it would be better to point to the latest released package: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
