### ISSUE TITLE
Deploying OpenShift Container Platform 3 on Amazon Web Services - What is the AMI to use if I want to install in another AWS region?

### ISSUE THREAD

**Issue by alberttwong** [openshift/openshift-ansible-contrib#55]
What is the AMI to use if I want to install in another AWS region?  It seems that I can only install in us-east-1.  I don't have the ami for other regions.

**Comment by kenthua** [comment]
For the hourly image, use the following below:

| AMI           | Amazon Region  |
| ---           | ---            |
| ami-2051294a | us-east-1     |
| ami-d1315fb1  | us-west-1      |
| ami-775e4f16  | us-west-2      |
| ami-8b8c57f8  | eu-west-1      |
| ami-875042eb  | eu-central-1   |
| ami-0dd8f963  | ap-northeast-1 |
| ami-44db152a  | ap-northeast-2 |
| ami-3f03c55c  | ap-southeast-1 |
| ami-e0c19f83  | ap-southeast-2 |
| ami-27b3094b  | sa-east-1      |

If you have private, red hat gold images, use those.

**Comment by cooktheryan** [comment]
@kenthua :+1:

**Comment by detiber** [comment]
@cooktheryan I'm wondering if we should add a mapping to the cloudformation templates for the default ami for each region and then use those by default if not explicitly set.

**Comment by sensiblemedia** [comment]
**Centos Atomic Host Builds**

Ami ID | Type | Region  |  Built On 
------- | -----------| --------- | -------------
ami-ba2b67dd | 8GB EBS HVM gp2 | ap-northeast-1 | 2017-Feb-13
ami-adbd6dc3 | 8GB EBS HVM gp2 |ap-northeast-2 | 2017-Feb-13
ami-a8388fcb | 8GB EBS HVM gp2 | ap-southeast-1 | 2017-Feb-13
ami-1f84857c | 8GB EBS HVM gp2 | ap-southeast-2 | 2017-Feb-13
ami-e8c20987 | 8GB EBS HVM gp2 | eu-central-1 | 2017-Feb-13
ami-1daa8c7b | 8GB EBS HVM gp2 | eu-west-1 | 2017-Feb-13
ami-1f492e73 | 8GB EBS HVM gp2 | sa-east-1 | 2017-Feb-13
ami-10f53a06 | 8GB EBS HVM gp2 | us-east-1 |2017-Feb-13
ami-4ae1bd2a | 8GB EBS HVM gp2 | us-west-1 | 2017-Feb-13
ami-4d9b1c2d | 8GB EBS HVM gp2 | us-west-2 | 2017-Feb-13

**List available Centos Atomic Host ami's by region:**
410186602215 = Centos Atomic Owner
`$ aws --region us-west-1 ec2 describe-images --owners 410186602215 | grep 'CentOS Atomic Host 7 x86_64 HVM EBS'`

**Finding AMI ids**
If you want to find the ami ids with the api, you can use the product code to search in each region. Keep in mind that multiple AMI ids may be associated with a product key. These correspond to different releases of the product. Here's an example command using awscli in us-east-1 to find the CentOS-7 images:  ( Lifted from https://wiki.centos.org/Cloud/AWS )
```
$ aws --region us-east-1 ec2 describe-images --owners aws-marketplace --filters Name=product-code,Values=aw0evgkw8e5c1q413zgy5pjce

IMAGES	x86_64	2016-02-26T21:11:52.000Z	CentOS Linux 7 x86_64 HVM EBS 1602	xen	ami-6d1c2007	aws-marketplace/CentOS Linux 7 x86_64 HVM EBS 1602-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-d7e1d2bd.3	aws-marketplace	machine	CentOS Linux 7 x86_64 HVM EBS 1602-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-d7e1d2bd.3	679593333241	True	/dev/sda1	ebs	available	hvm
BLOCKDEVICEMAPPINGS	/dev/sda1
EBS	False	False	snap-9ac0730c	8	standard
PRODUCTCODES	aw0evgkw8e5c1q413zgy5pjce	marketplace
```

**Comment by cooktheryan** [comment]
Closed since it's described well above
