### ISSUE TITLE
[openshift-ansible] OSError: [Errno 12] Cannot allocate memory (m1.large VMs)

### ISSUE THREAD

**Issue by bogdando** [openshift/openshift-ansible-contrib#551]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

# BUG REQUEST INFO:

Something looks had been changed on the openshift-ansible side badly. The task `TASK [openshift_hosted_templates : Unarchive the OpenShift hosted templates on the remote]` fails for me with "OSError: [Errno 12] Cannot allocate memory". Even on m1.large 8G VMs. While it was deploying with m1.small 2G before (with checks disabled [like that](https://github.com/bogdando/ocp-inventory/blob/cdecb6f696f614dc42a583a66e6239b8a94900e9/group_vars/OSEv3.yml#L25)

**Environment**:
- **Cloud provider:** OpenStack

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** Centos7.3

- **Version of Ansible:** (`ansible --version`): ansible==2.3.1.0

- **Version of Jinja:** (`pip freeze | grep -i jinja`): Jinja2==2.9.6

- **Version of Shade:** (`pip freeze | grep -i shade`): shade==1.22.2

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):** openshift-ansible: 0b0a7af

**Copy of used inventory files and custom variables (please omit your secrets!):**
[1](https://github.com/bogdando/ocp-inventory/blob/cdecb6f696f614dc42a583a66e6239b8a94900e9/group_vars/OSEv3.yml)
[2](https://github.com/bogdando/ocp-inventory/blob/cdecb6f696f614dc42a583a66e6239b8a94900e9/group_vars/all.yml)
[3](https://github.com/bogdando/ocp-inventory/blob/cdecb6f696f614dc42a583a66e6239b8a94900e9/no_examples.yml)

**Command used to invoke ansible**:
`ansible-playbook --become openshift-ansible/playbooks/byo/config.yml -e@inventory/no_examples.yml`

**Output of ansible run**:

**Anything else do we need to know**:

**Comment by bogdando** [comment]
@tomassedovic please confirm if this applies for you as well. Then let's open a bug for openshift-ansible perhaps

**Comment by bogdando** [comment]
The w/a is to [not install examples](https://github.com/bogdando/ocp-inventory/blob/cdecb6f696f614dc42a583a66e6239b8a94900e9/no_examples.yml#L7)

**Comment by tomassedovic** [comment]
@bogdando what's your commit has of openshift-ansible? I can try master, but would like to try the same commit that you have.

**Comment by bogdando** [comment]
it seems related to my control node VM, which uses m1.tiny
