### ISSUE TITLE
Having problems with AWS deployment - ERROR: "Forbidden", while: getting RDS instances

### ISSUE THREAD

**Issue by alberttwong** [openshift/openshift-ansible-contrib#56]
command
```
./ose-on-aws.py --create-key=yes --rhsm-user=alwong@redhat.com --rhsm-password=XXXX --public-hosted-zone=ocp.alberttwong.com --key-path=/root/.ssh/id_rsa.pub --keypair=us-east-1 --rhsm-pool=Employee
```
error message
```
ERROR: "Forbidden", while: getting RDS instancesERROR! Inventory script (inventory/aws/hosts/ec2.py) had an execution error: ERROR: "Forbidden", while: getting RDS instances
```

modified my IAM policy to below with S3FullAccess
```
{
   "Version": "2012-10-17",
   "Statement": [
       {
           "Sid": "Stmt1459269951000",
           "Effect": "Allow",
           "Action": [
               "cloudformation:*",
               "iam:*",
               "route53:*",
               "elasticloadbalancing:*",
               "ec2:*",
               "cloudwatch:*",
               "autoscaling:*"
           ],
           "Resource": [
               "*"
           ]
       }
   ]
}
```

**Comment by alberttwong** [comment]
also tried in ec2.ini

```
rds = False
```

but get

```
ERROR: "Forbidden", while: getting ElastiCache clustersERROR! Inventory script (inventory/aws/hosts/ec2.py) had an execution error: ERROR: "Forbidden", while: getting ElastiCache clusters
```

**Comment by cooktheryan** [comment]
I have this fix in a PR that's already approved give me 5 minutes.

Ryan

**Comment by alberttwong** [comment]
just did a pull on the newest code from git... trying again.

**Comment by alberttwong** [comment]
new error in cloudformation

```
Value (us-east-1a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1c, us-east-1e, us-east-1d, us-east-1b.
```

**Comment by cooktheryan** [comment]
Ill need to look into this as I have not seen it before.

**Comment by alberttwong** [comment]
I had this problem with demo-ansible too.... switching to us-west-2 (Oregon).

**Comment by alberttwong** [comment]
Just for fun... also attached the following policies.

AmazonRDSFullAccess, AmazonEC2FullAccess, AmazonElastiCacheFullAccess, AmazonS3FullAccess, AmazonRoute53FullAccess 

with the custom policy I posted above.

**Comment by alberttwong** [comment]
us-west-2 is working for me.  cloudformation passed and now I'm on rest of the ansible scripts.

**Comment by cooktheryan** [comment]
From a quick look it seems like the issue may be a common thing on the aws
end.

**Comment by detiber** [comment]
@alberttwong does your account have access to AWS Classic?

@cooktheryan it looks like the version of ec2_zones_by_region.py you are using it removes us-east-1b from the zone list, I suspect this is related to a specific account not having a us-east-1b, where @alberttwong's account does not have a us-east-1a (at least for vpc-enabled).

**Comment by alberttwong** [comment]
not sure... how do I get there (google isn't helpful)?

**Comment by cooktheryan** [comment]
@detiber  I believe us-east-1b is classic that is why it's scrubbed. Early on I tried to deploy there with no luck and had to write in the work around.

**Comment by detiber** [comment]
@cooktheryan only on a specific account, us-east-1b on one account != us-east-1b on another account.

**Comment by detiber** [comment]
@cooktheryan trying to see if we can do a better job of introspecting the zones returned in the filter

**Comment by cooktheryan** [comment]
Ahh TIL

**Comment by detiber** [comment]
@cooktheryan @alberttwong I believe that https://github.com/openshift/openshift-ansible-contrib/pull/59 will help with the zone issue (to a point). The changes filter the zones returned to ones that have a VPC subnet. It'll still cause issues if no VPCs are defined for a EC2 Classic account, but I haven't been able to find a way to query the zones themselves to determine if they are vpc-enabled.

**Comment by alberttwong** [comment]
I'm having ssh issues

```
[root@localhost ~]# ssh ec2-user@bastion.ocp.alberttwong.com
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
06:35:3b:37:90:8e:50:32:4c:c0:67:d2:0e:54:79:0c.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /root/.ssh/known_hosts:2
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
Agent forwarding is disabled to avoid man-in-the-middle attacks.
Error: forwarding disabled due to host key check failure
ssh_exchange_identification: Connection closed by remote host
[root@localhost ~]# ssh ec2-user@35.160.172.216
Last login: Wed Oct 19 23:25:31 2016 from cpe-75-83-58-118.socal.res.rr.com
```

**Comment by detiber** [comment]
@alberttwong added disabling of rds and elasticache instances to #59 as well.

**Comment by reubensml** [comment]
In my case i don't use Elasticache  set the following in ec2.ini file
'elasticache = False' and it completed sucessfully and listed all the instances
