### ISSUE TITLE
[RFE] GCP - Allow use of Atomic Hosts

### ISSUE THREAD

**Issue by Fale** [openshift/openshift-ansible-contrib#568]
FEATURE REQUEST

As far as I can see, there is no way to use Atomic Hosts with gcloud.sh. I think it would be very nice to have such a feature

**Comment by pschiffe** [comment]
I agree :-) Unfortunately, atomic host is not yet supported on GCP - but we are actively working on it.

**Comment by Fale** [comment]
I've been able to create an Atomic Host instance in GCP using the upload way. Not sure if something could be problematic on the medium/long term but it seemed to be working properly for what I tested.
I wonder if the same technique could be used or not. Also, if Atomic Hosts would be officially supported, maybe is better waiting slightly longer for that :)

**Comment by pschiffe** [comment]
Yes, it works, but not all GCP features are available on atomic host yet. For them to work, you need to have running https://github.com/pschiffe/gce-system-container 
And of course, we want atomic host to be officially available in the GCP.
