### ISSUE TITLE
gcloud.sh: Fail when create dns-zone

### ISSUE THREAD

**Issue by gizmodemente** [openshift/openshift-ansible-contrib#570]
Environment:
- GoogleCloud Platform
- CentOS 7
- ansible 2.3.1.0
- Commit 913006e

Using gcloud.sh to inovke ansible and adding this variable for point the proper ansible-installer branch:

> openshift_ansible_branch: 'openshift-ansible-3.5.5.21-1'

Before run edit gcloud.sh to add verbosity to output in this line:

> ansible-playbook -vvv -e @playbooks/openshift-installer-common-vars.yaml -e @../config.yaml $@ "$playbook"

Obtain this output:

> TASK [dns-zone : create dns zone] **************************************************************************************************************************************************************************
> task path: /openshift-ansible-contrib/reference-architecture/gce-cli/ansible/playbooks/roles/dns-zone/tasks/main.yaml:2
> Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/google/gcdns_zone.py
> <localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
> <localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
> <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1500624973.57-166128673263178 `" && echo ansible-tmp-1500624973.57-166128673263178="` echo /root/.ansible/tmp/ansible-tmp-1500624973.57-166128673263178 `" ) && sleep 0'
> <localhost> PUT /tmp/tmpD5qGWo TO /root/.ansible/tmp/ansible-tmp-1500624973.57-166128673263178/gcdns_zone.py
> <localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1500624973.57-166128673263178/ /root/.ansible/tmp/ansible-tmp-1500624973.57-166128673263178/gcdns_zone.py && sleep 0'
> <localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1500624973.57-166128673263178/gcdns_zone.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1500624973.57-166128673263178/" > /dev/null 2>&1 && sleep 0'
> The full traceback is:
> Traceback (most recent call last):
>   File "/tmp/ansible_qkxJwV/ansible_module_gcdns_zone.py", line 153, in <module>
>     PROVIDER = Provider.GOOGLE
> NameError: name 'Provider' is not defined
> 
> fatal: [localhost]: FAILED! => {
>     "changed": false, 
>     "failed": true, 
>     "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_qkxJwV/ansible_module_gcdns_zone.py\", line 153, in <module>\n    PROVIDER = Provider.GOOGLE\nNameError: name 'Provider' is not defined\n", 
>     "module_stdout": "", 
>     "msg": "MODULE FAILURE", 
>     "rc": 0
> }

 
I tried to fix following the instructions in #308 but don't work for me

**Comment by pschiffe** [comment]
This really looks like problem with libcloud, what's yours `rpm -q python2-libcloud`?

BTW you can increase verbosity by directly passing `-vvvv` to the `./gcloud.sh` script.

BTW2, why is `openshift-ansible-3.5.5.21-1` proper?

**Comment by gizmodemente** [comment]
```
$ rpm -q python2-libcloud 
python2-libcloud-2.0.0rc2-1.el7.noarch
```

I use `openshift-ansible-3.5.5.21-1` following the instructions in (note: Previously i obtained same result without modify this property):

[https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/gce-cli#ansible-installer](url)

Thanks

**Comment by pschiffe** [comment]
Ah, sorry for that documentation, it's outdated, now the ref. arch. code manages the ansible installer itself, and the `release-1.5` branch is correct thing to use.

Reg. the libcloud, it's possible that there is some bug, I need to investigate.

**Comment by gizmodemente** [comment]
Ok, thanks for the indications, i removed the branch variable.

**Comment by gizmodemente** [comment]
Hi @pschiffe, the problem i solved. I need install apache-libcloud using `pip install apache-libcloud`.

I close this issue.

Thanks for help.

**Comment by gizmodemente** [comment]
Sorry, i must reopen the issue, fail only was masked under other ssl error message caused for python version, when solve this problem the original fail persists.

**Comment by gizmodemente** [comment]
Sorry again i have some mess with python versions and libraries. Close the issue.
