### ISSUE TITLE
When printing node information, IPs are printed out instead of node names

### ISSUE THREAD

**Issue by Tlacenka** [openshift/openshift-ansible-contrib#577]
After running the whole deployment (provisioning + installation) successfully and running `oc get nodes` on OpenShift master node, I get an output similar to this:

```
NAME            STATUS                     AGE
192.168.99.11   Ready,SchedulingDisabled   19m
192.168.99.13   Ready                      19m
192.168.99.15   Ready                      19m
192.168.99.4    Ready                      19m
192.168.99.5    Ready                      19m
```
where names are replaced by private IPs. This should not happen.

Note: running `openstack server list` on the undercloud returns correct domain names for all nodes

cc @bogdando @tomassedovic

**Comment by bogdando** [comment]
@Tlacenka the undercloud? Do you deploy with tripleo? Does this reproduce on RDO cloud VMs?

**Comment by Tlacenka** [comment]
No, by undercloud I meant the host from which I run ansible. Does it have a specific name?

**Comment by bogdando** [comment]
I can confirm the same behavior on RDO cloud hosted VMs:
```
[openshift@master-0 ~]$ oc get nodes
NAME            STATUS                     AGE
192.168.99.10   Ready                      5d
192.168.99.16   Ready                      5d
192.168.99.7    Ready,SchedulingDisabled   5d
[openshift@master-0 ~]$ hostname
master-0.openshift.cluster.lc
```

**Comment by bogdando** [comment]
@Tlacenka yes, it's a control node or (ansible) admin node or the like

**Comment by bogdando** [comment]
@tomassedovic is it related to the openshift-ansible `masterURL: {{ openshift.master.api_url }}`?

**Comment by tomassedovic** [comment]
I don't think so, that should just be the URL of the UI/API endpoint. My guess would be that the static inventory doesn't set some node variable that was coming out of openstack.py.

After a brief look, the `openshift_hostname` variable on each node seems promising.

**Comment by bogdando** [comment]
@tomassedovic should not be the facts issue, ansible_fqdn contains the correct value for nodes

**Comment by tomassedovic** [comment]
Question is whether openshift-ansible reads that value. I'll try it out. Openstack.py sets a tons of vars that we're not using.

**Comment by tomassedovic** [comment]
Yep, so setting `openshift_hostname` fixes the issue.
