### ISSUE TITLE
AWS - TASK [host-up : check to see if host is available] - Timeout waiting for bastion

### ISSUE THREAD

**Issue by alberttwong** [openshift/openshift-ansible-contrib#58]
getting this error...

```
TASK [host-up : check to see if host is available] *****************************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for bastion.ocp.alberttwong.com:22"}
```

tried to manually connect
```
[root@localhost aws-ansible]# ssh ec2-user@ec2-35-161-6-30.us-west-2.compute.amazonaws.com
[ec2-user@ip-10-20-1-191 ~]$ ls
[ec2-user@ip-10-20-1-191 ~]$ exit
logout
Connection to ec2-35-161-6-30.us-west-2.compute.amazonaws.com closed.
```

Didn't ask me a username and let me in.  

I found out the issue is that somehow the DNS entry in route53 aren't coming down to me (DNS propagation).    Make sure you can get to your bastion (bastion.ocp.alberttwong.com) by ssh ec2-user@bastion.ocp.alberttwong.com.  If this doesn't work, modify your dns.

**Comment by cooktheryan** [comment]
Can you ssh to the bastion instance using the route 53 name?

**Comment by alberttwong** [comment]
```
TASK [setup] *******************************************************************
fatal: [ose-master01.ocp.alberttwong.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=5    unreachable=0    failed=0
ose-master01.ocp.alberttwong.com : ok=0    changed=0    unreachable=1    failed=0

[root@localhost aws-ansible]# ssh ec2-user@ose-master01.ocp.alberttwong.com
```

No but I found an issue with my .ssh/config file so I'm going to start from the beginning.

**Comment by alberttwong** [comment]
So this is weird.   bastion is the only one that doesn't come back from DNS lookup.  Everything else works.  

Now I have a new error.   Reinstall everything from the beginning to be clean.   Ansible can't connect to all the instances.  Looking in AWS console, there isn't any exposed public dns names... only private IPs.   I'm running my ansible scripts on RHEL7 in my virtualbox at home.   Maybe I'm not supposed to?!?!?!?

![screen shot 2016-10-21 at 12 56 09 pm](https://cloud.githubusercontent.com/assets/749093/19609828/42299406-978e-11e6-801d-27db9d42540c.png)

**Comment by alberttwong** [comment]
/root/.ssh/config file.

![screen shot 2016-10-21 at 1 03 43 pm](https://cloud.githubusercontent.com/assets/749093/19609948/d364bc0c-978e-11e6-9705-6313fb196a33.png)

**Comment by alberttwong** [comment]
```
[root@ose aws-ansible]# ssh root@ose-master03.ocp.alberttwong.com
channel 0: open failed: administratively prohibited: open failed
ssh_exchange_identification: Connection closed by remote host
```

**Comment by alberttwong** [comment]
@cooktheryan any ideas on what I can do next?

**Comment by cooktheryan** [comment]
Try ec2-user rather than root

**Comment by cooktheryan** [comment]
As long as your .ssh/config is setup in virtualbox you are fine. That's how
I actually launch my environment. It appears the bastion was ok because it
passed host up playbook.  Id check the .ssh/known_hosts.

You wont be able to ping because ping is not allowed. Also in regards to
the public ips there is only a public ip on the bastion as the rest of the
environment is private ip and accessible through the bastion as a ssh
jumpbox.

Ryan

**Comment by alberttwong** [comment]
It seems that the answer may be to add the DNS NS entry from ocp.alberttwong.com to alberttwong.com in route53.    This is missing from the documentation.

**Comment by cooktheryan** [comment]
Reference arch document is shipping today

**Comment by robert-greathouse** [comment]
I'm having the same problem. I'm installing to AWS from an EC2 VM to run Ansible. I'm getting the same error. And I can't ssh to the bastion. I did add the NS entries from my sub domain to the NS entries for the main domain. So now I have both the original and the new ones. I would think the DNS should be updated inside an Amazon instance. Is there something else I should check?

**Comment by robert-greathouse** [comment]
I was able to ssh to the bastion when to set the SSH config to the EIP domain name on AWS. But the script still stalls at the same place.

**Comment by cooktheryan** [comment]
The .ssh/config should be performed on the system in which ose-on-aws.py
was ran
