### ISSUE TITLE
RFE - GCP autoscaling

### ISSUE THREAD

**Issue by Fale** [openshift/openshift-ansible-contrib#602]
FEATURE REQUEST
Google Cloud Platform, in a similar way to AWS and other clouds, allow the creation of auto-scaling group of machines.
I think it would be very useful to be able to leverage this concept to auto-scale the nodes in an OpenShift cluster.

From an implementation stand point, I think it could be easily done by injecting the OCP dependencies/application/configuration in the golden image and then having the newly arrived node just starting and checking in with the masters.
I'm not sure if this implementation would have downsides and/or limits and therefore if it would be suggestible to have it working in this way.

**Comment by cooktheryan** [comment]
@Fale it may not be worth visiting this until upcoming releases. With any sort of autoscaling including AWS there is roughly a 15-20 minute time before a node can only be eligible to be an OpenShift node

**Comment by Fale** [comment]
@cooktheryan is upcoming 1.6 or are you talking about a more future one?
Yeah, the slowness of autoscaling surely makes this option not the best one

**Comment by cooktheryan** [comment]
I believe in a future release sadly not 1.6

**Comment by Fale** [comment]
I see, thanks. I hope it will be soon :)
