### ISSUE TITLE
[RFE] GCP Enable different auth providers in OpenShift 

### ISSUE THREAD

**Issue by mperezco** [openshift/openshift-ansible-contrib#617]
**Introduction**
Improving auth providers flexibility in OpenShift on GCP

**Problem Description**
The current playbooks are made so the only auth provider for OpenShift is GCP IAM.

**Proposed Change**
Create an independent playbook to configure OpenShift auth provider to use GCP IAM as in the config.yaml.example file:

    # OpenShift Identity providers. This is Google oauth example (hosted_domain is
    # optional and restricts login to users only from the specified domain)
    openshift_master_identity_providers:
    - name: 'google'
     kind: 'GoogleIdentityProvider'
     login: true
     challenge: false
     mapping_method: 'claim'
     clientID: 'xxx-yyy.apps.googleusercontent.com'
     clientSecret: 'zzz'
     hostedDomain: 'example.com'

Remove it from config.yaml.example file and leave just the vars. As example:

    openshift_auth_provider: 'gcp-iam'
    openshift_auth_client_id: 'xxx-yyy.apps.googleusercontent.com'
    openshift_auth_client_secret: 'zzz'
    openshift_auth_hosted_domain: 'example.com'

Enabling a way to add other auth providers such as htpass_file or github.

 *Security Impact*
It can enable users to use their own auth and also, make the solution more multi-cloud friendly.

*Other End User Impact*
It's easier to migrate workloads

*Developer Impact*
1 account multiple openshifts.

*Documentation Impact*
Regenerate auth section in documentation

**Implementation**
I'm willing to help :-D

**Acceptance criteria**
I can deploy OpenShift to GCP in ways so it can validate users against:
- plain htpasswd files
- github
... only by changing variable values in config.yaml file

**Testing**
Deploy several OpenShift instances in GCP one with each auth method implemented.
Validate a user against those methods with right password --> result OK
Validate a user against those methods with wrong password --> result Not-OK

**References**
https://docs.openshift.com/container-platform/3.5/admin_solutions/authentication.html

**Comment by pschiffe** [comment]
Hello @mperezco . Variable `openshift_master_identity_providers` is directly passed to the openshift ansible installer, so you can already configure it in any way you need [1]. We are using Google oauth by default, because we are deploying on Google's cloud :-)

[1] https://docs.openshift.com/container-platform/3.5/install_config/configuring_authentication.html#identity-providers-ansible

**Comment by mperezco** [comment]
Hello @pschiffe 

In the documentation, section 3.3, table 3.2, states that the SSO snippet shall not be changed [1]
[1] https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/deploying_red_hat_openshift_container_platform_3_on_google_cloud_platform/#prepare_the_installation_script

Users deploying OpenShift on GCP will therefore not use any other auth mechanism available in OpenShift.

For users that want to be "cloud independent", being able to decouple auth service from the cloud where OpenShift is deployed is important. An example would be a Push Button Infrastructure that uses the best priced cloud for the project, depending on the offers received, which will be consumed by the same users and teams.

Another example would be for ephemeral OpenShift deployments to be used as demo environments that require to show HA, or classroom environments to learn OpenShift internals, having a "AllowAllPasswordIdentityProvider" could be really useful.

**Comment by pschiffe** [comment]
Thanks @mperezco , noted. The paper will be updated for 3.6, I'll update this section as well.

**Comment by mperezco** [comment]
Thanks!!!

**Comment by pschiffe** [comment]
The documentation should be updated now. New paper will be published soon, so closing this issue. Thanks for letting me know.
