### ISSUE TITLE
Openstack provider creates Open DNS service

### ISSUE THREAD

**Issue by ggillies** [openshift/openshift-ansible-contrib#621]
**Environment**: Openshift Origin 1.5 on CentOS 7
- **Cloud provider:** Openstack

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** Linux 3.10.0-514.10.2.el7.x86_64 x86_64
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Version of Ansible:** (`ansible --version`): ansible 2.3.1.0
  config file = /home/ggillies/code/upshift-scale/ansible.cfg
  configured module search path = [u'library', u'ceph-ansible/library']
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

- **Version of Jinja:** (`pip freeze | grep -i jinja`) Jinja2==2.9.6

- **Version of Shade:** (`pip freeze | grep -i shade`) shade==1.22.2

- **Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):** dc9a301

After successfully using the Openstack provider playbooks to deploy Openshift on Openstack, I noticed that the dns service deployed (dns-0 VM) is deployed as an Open DNS service. My deployment is publicly facing (on the internet) and this is a security vulnerability as people can use Open DNS servers for attacks on other services (as well as attacking my own infrastructure). This DNS service should be restricted to only provide the records it serves.

**Comment by bogdando** [comment]
Please take a look the [security notes](https://github.com/openshift/openshift-ansible-contrib/blob/master/playbooks/provisioning/openstack/README.md#security-notes) . Specifying the `node_ingress_cidr` effectively hides the provisioned DNS servers from a public/open access

**Comment by tomassedovic** [comment]
(reopening this -- just making sure this is actually resolved)

@ggillies does the node_ingress_cidr option work for you? It restricts access to the dns node to the given IP range.

I guess what we could do in addition would be to optionally forbid any non-cluster requests from the public view (we need to forward the requests coming from within the nodes, but that's not necessary from the outside).

**Comment by bogdando** [comment]
@tomassedovic restricting public access to a single admin/control node seems enough to me. That node has a trust and full admin access and drives the deployment, no need to restrict it from doing specific DNS requests.

**Comment by ggillies** [comment]
So I have had a closer look at the node_ingress_cidr option and how it is utilised, and I don't think its a satisfactory solution at all. In fact, I'd say the security group setup is done quite lazily and not reflective of how it should be done.

My point is if I wish to deploy an Openshift instance to the public internet (as an example), I would expect the Openshift instance to be available to everyone, no restrictions by IP. I realise that because of this, the dns server would be open to the internet as well. However, this means anyone can use my dns server recursively, which is a massive security hole. I would expect the dns server to be an authoritative nameserver for the records it serves, but not be a general recursive nameserver.

On top of this, I notice you configure the instances to use the dns server you provision as its dns resolver, this I don't like either. Often we have specific resolves we wish to use in our setups for security reasons (dns blackholes for nefarious sites as an example), and you have essentially hijacking that process and building your own entire dns infrastructure for the environment, with predictable security concerns.

I think the whole setup of how this is deployed and works needs to be revisited from the ground up as at the moment it's not really usable in any production fashion.

**Comment by bogdando** [comment]
@ggillies that's a fair point, thank you! @oybed what do you think of adding an option for the infra-casl DNS server [role](https://github.com/redhat-cop/infra-ansible/tree/master/roles/dns-server) to prohibit recursion?

**Comment by bogdando** [comment]
I believe we should address a single issue at a time, @ggillies could you please split this into 1) open DNS issue , 2) disable recursive behavior of authoritative DNS, 3) authoritative DNS server used as a resolver.
Then we can start discussing and addressing those one by one.

**Comment by bogdando** [comment]
It seems that the [dns-server role](https://github.com/redhat-cop/infra-ansible/tree/master/roles/dns-server) provides all the flexibility we may want, just need to compose it for the contrib repo as appropriate. But let's please discuss each issue in its own space.

**Comment by oybed** [comment]
@bogdando yes, the dns-server role allows you to turn off recursion as-is. This is on a per-view basis and should be sufficient. However, we can also enhance the role to allow for a configuration option to turn it off globally - if needed. 

@ggillies you do have the option to not have a dns-server provided by the provisioning, and just use all external DNS servers (i.e.: your own). They just need to be correctly configured up front and provide the necessary interfaces/resolution along the way of the provisioning (i.e.: support nsupdate to allow the provisioning to add records for the newly provisioned instances).

**Comment by bogdando** [comment]
@ggillies there is also an inventory var to define public resolvers, see [README](https://github.com/openshift/openshift-ansible-contrib/blob/master/playbooks/provisioning/openstack/README.md) :

> The public_dns_nameservers is a list of DNS servers accessible from all the created Nova servers.
> These will be serving as your DNS forwarders for external FQDNs that do not belong to the cluster's 
> DNS domain and its subdomains.

I hope this helps to identify and triage the aforementioned issues.

**Comment by ggillies** [comment]
@bogdando thanks for pointing out public_dns_nameservers. Can we modify it so by default that defaults to the nameservers that Openstack provides.

I guess what I am thinking is that typically when we setup an Openstack installation, we configure it to use the right nameservers and thus any neutron networks created have the right dns configuration (even if it's just forwarding requests through neutron dnsmasq).

So the out of the box experience should be all the instances should just use whatever dns resolvers that Openstack provides by default, with the exception for the domain running the environment which needs to go to the dns server that's created. That dns server should not allow public recursion (or any recursion at all), I would expect the instances to use the neutron provided setup for general recursion

**Comment by bogdando** [comment]
We established the Neutron subnet a [live update hook](https://github.com/openshift/openshift-ansible-contrib/blob/f512cada069c77d2029cbd75a57d8ca9c77d64a3/roles/openstack-stack/tasks/subnet_update_dns_servers.yaml#L8) and a [switch call](https://github.com/openshift/openshift-ansible-contrib/blob/f512cada069c77d2029cbd75a57d8ca9c77d64a3/playbooks/provisioning/openstack/post-provision-openstack.yml#L69) on post-install for it, in order to make a persistent DNS configuration for nodes. The decision we made was to prepend the defined `public_dns_nameservers` to the configured (auto-detected by the detect-dns-server role) `private_dns_server` IP. So when a node reboots, it re-gets the consistent DNS config with the configured (or external) authoritative DNS server going always in the first place.

To revise that decision, we should come up with an alternative way to ensure Nova servers always getting the valid configuration to resolve cluster FQDNs natively, which is via the cloud-init & network-manager configs. Note, there is also an option to deploy dnsmasq for each node, which shifts the DNS stack configuration a little bit...

**Comment by bogdando** [comment]
Note, https://github.com/openshift/openshift-ansible-contrib/pull/623 will allow to use a secure mixed setup of an open DNS server for public view dynamic records updates, and the instack DNS server for the private view updates. The latter may be done hidden from outer world completely, by setting the `node_ingress_cidr` to a private network CIDR.

**Comment by oybed** [comment]
Quick PR to allow for the global recursion option to be set to `no`:
https://github.com/redhat-cop/infra-ansible/pull/66

**Comment by bogdando** [comment]
Thank you @oybed !
related issue https://github.com/redhat-cop/infra-ansible/issues/65

**Comment by bogdando** [comment]
Another related change https://github.com/redhat-cop/infra-ansible/pull/69

**Comment by bogdando** [comment]
@ggillies could you please provide us feedback on the implemented fixes and remaining issues for this item's scope?

**Comment by ggillies** [comment]
@bogdando I haven't had a chance to have a close look at this and unfortunately it looks like I won't be able to, so I am happy for you to close this for the moment and myself or others can re-open with more specific issues if needed
