### ISSUE TITLE
Support Openstack Provider using an existing provider network

### ISSUE THREAD

**Issue by ggillies** [openshift/openshift-ansible-contrib#622]
Support Openstack Provider using an existing provider network

## **Problem Description**

In a typical deployment on Openshift on Openstack, when using the Openshift SDN, you essentially have two layers of encapsulation with Openvswitch (once at the Openshift SDN level, and one at the Openstack network level). I would like the Openstack provider playbooks to support using either a new, or an existing provider network for SDN traffic. This would solve this problem as we could use a provider network of type vlan, bypassing openstacks normal openvswitch encasulation

## **Implementation**

Describe your plan for implementation steps and potential
assignees/contributors.

## **Acceptance criteria**

Provide a definition of done and acceptance criteria.

## **Testing**

Describe how to test this, including manual steps, if any.

**Comment by tomassedovic** [comment]
Thanks! I'll give this a stab shortly.

**Comment by tomassedovic** [comment]
@ggillies I missed the "provider" bit.

Don't have much experience with those so just to make sure I understand:

When we attach the servers to a provider network, they won't have floating IP addresses, but the IPs they get from the network will be accessible, right?

So to support this, we would:

* not create a new Neutron network
* instead, add servers to the one you would specify
* not create floating IP addresses
* access the nodes using the IP addresses from the provider network

Is that correct?

As for creating a new provider network, how would that work?

`openstack network create --help` gives me these options: `--provider-network-type`, `--provider-physical-network` and `--provider-segment`. Is that it or would we need to get more info?

**Comment by ggillies** [comment]
@tomassedovic Thinking about this more how I would expect it to work is that I create the provider network myself outside of Openshift, and that network is used for the openshift internal/sdn traffic only. Because provider networks appear no different than non provider networks, basically you can expand this RFE to be, how can an operator use the installer with an existing neutron network they have created, provider or no?

**Comment by tomassedovic** [comment]
Yeah that's what I was thinking, too. In fact, since I don't have an openstack with a provider network enabled, this is how I'm developing & testing this.

**Comment by tomassedovic** [comment]
@rlopez133 adding you to this since you iirc asked for the same thing some time ago.

I created a pull request, would be great if you both tried it out and shared your thoughts.

https://github.com/openshift/openshift-ansible-contrib/pull/701
