### ISSUE TITLE
Origin Installation required Redhat subscription

### ISSUE THREAD

**Issue by jcperezamin** [openshift/openshift-ansible-contrib#633]
Why Openshift origin require a RedHat Subscription?
Configured values:
	stack_name: openshift
	ami: ami-d74be5b8
	region: eu-central-1
	master_instance_type: m4.xlarge
	node_instance_type: t2.large
	app_instance_type: t2.large
	bastion_instance_type: t2.micro
	keypair: OpenshiftKeyPub
	create_key: no
	key_path: /dev/null
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: origin
	openshift_sdn: redhat/openshift-ovs-multitenant
	public_hosted_zone: <mydomain>
	app_dns_prefix: dev
	apps_dns: dev. <mydomain>
	rhsm_user: None
	rhsm_password: *******
	rhsm_pool: None
	containerized: False
	s3_bucket_name: openshift- <mydomain>
	s3_username: openshift- <mydomain>
	github_client_id: *******
	github_client_secret: *******
	github_organization: openshift
	openshift_metrics_deploy: true
	openshift_metrics_storage_volume_size: 20Gi
	openshift_logging_deploy: false
	openshift_logging_storage_volume_size: 100Gi

TASK [aws-rhsm-subscription : Is the host already registered?] ********************************************************************************
fatal: [ose-master03.mindcurv-labs.es]: FAILED! => {"changed": false, "cmd": ["subscription-manager", "status"], "delta": "0:00:00.157849", "end": "2017-08-12 06:31:19.645934", "failed": true, "rc": 1, "start": "2017-08-12 06:31:19.488085", "stderr": "", "stderr_lines": [], "stdout": "+-------------------------------------------+\n   System Status Details\n+-------------------------------------------+\nOverall Status: Unknown", "stdout_lines": ["+-------------------------------------------+", "   System Status Details", "+-------------------------------------------+", "Overall Status: Unknown"]}
...ignoring

TASK [aws-rhsm-subscription : RedHat subscriptions] *******************************************************************************************
fatal: [ose-master03.mindcurv-labs.es]: FAILED! => {"changed": false, "cmd": "subscription-manager register --username VALUE_SPECIFIED_IN_NO_LOG_PARAMETER --password '********'", "failed": true, "msg": "Invalid username or password. To create a login, please visit https://www.redhat.com/wapps/ugc/register.html", "rc": 70, "stderr": "Invalid username or password. To create a login, please visit https://www.redhat.com/wapps/ugc/register.html\n", "stderr_lines": ["Invalid username or password. To create a login, please visit https://www.redhat.com/wapps/ugc/register.html"], "stdout": "Registering to: subscription.rhsm.redhat.com:443/subscription\n", "stdout_lines": ["Registering to: subscription.rhsm.redhat.com:443/subscription"]}

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=9    changed=5    unreachable=0    failed=0
ose-master03.mindcurv-labs.es : ok=4    changed=0    unreachable=0    failed=1

Failure summary:

  1. Host:     ose-master03.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     aws-rhsm-subscription : RedHat subscriptions
     Message:  Invalid username or password. To create a login, please visit https://www.redhat.com/wapps/ugc/register.html

**Comment by cooktheryan** [comment]
@jcperezamin is the ami rhel?

**Comment by cooktheryan** [comment]
I believe we can bypass this to allow for RHEL to use origin but i just want to make sure I'm starting at the right place.

**Comment by jcperezamin** [comment]
Yes, the AMI is RHEL: RHEL-7.4_HVM_GA-20170808-x86_64-2-Hourly2-GP2 (ami-d74be5b8) Frankfurt region. Is mandatory to use centos image? or atomic?

**Comment by jcperezamin** [comment]
Testing CentOS Atomic Host 7 x86_64 HVM EBS 1607_0

Failure summary:

   1. Host:     ose-infra-node03.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   2. Host:     ose-master01.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   3. Host:     ose-master02.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   4. Host:     ose-master03.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   5. Host:     ose-infra-node01.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   6. Host:     ose-infra-node02.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   7. Host:     ose-app-node01.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   8. Host:     ose-app-node02.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : assert
      Message:  Installation on Atomic Host requires Docker 1.12 or later. Attempting to patch.

   9. Host:     ose-master03.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

  10. Host:     ose-infra-node02.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

  11. Host:     ose-app-node02.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

  12. Host:     ose-infra-node01.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

  13. Host:     ose-master02.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

  14. Host:     ose-infra-node03.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

  15. Host:     ose-master01.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

  16. Host:     ose-app-node01.mindcurv-labs.es
      Play:     cluster_hosts
      Task:     prerequisites : Patching Atomic instances
      Message:  ???

**Comment by jcperezamin** [comment]
Fedora-Atomic-25-20170424.0.x86_64-eu-central-1-HVM-standard-0 (ami-0084586f) - Frankfurt Region

Failure summary:

  1. Host:     ose-master03.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

  2. Host:     ose-app-node02.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

  3. Host:     ose-infra-node02.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

  4. Host:     ose-master02.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

  5. Host:     ose-master01.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

  6. Host:     ose-app-node01.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

  7. Host:     ose-infra-node01.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

  8. Host:     ose-infra-node03.mindcurv-labs.es
     Play:     cluster_hosts
     Task:     prerequisites : Gather facts
     Message:  MODULE FAILURE

**Comment by jcperezamin** [comment]
Same outcome with Fedora-Atomic-26-20170807.0.x86_64-eu-central-1-HVM-gp2-0 (ami-df822cb0) (Optimized for Kubernetes and OpenShift
Building a Kubernetes or Origin cluster to run your containerized applications? Run it on Fedora Atomic, which provides you the platform you need on a smaller, leaner OS.) 👎

**Comment by cooktheryan** [comment]
Rhel PR being resolved now. Will be looking into CentOS next. Fedora is a bit harder due to the python versions and ansible

**Comment by jcperezamin** [comment]
Rhel PR resolved

**Comment by cooktheryan** [comment]
Shouldn't be any issues currently

**Comment by mykaul** [comment]
@cooktheryan - I'm trying to install on oVirt on top of CentOS and I fail pretty early with RHSM stuff.
Even when I disable it, I then fail getting RPMs needed for OpenShift - I suspect we need to add some other CentOS repo I'm not aware of.

**Comment by cooktheryan** [comment]
Can you file a new GitHub issue for this?
