### ISSUE TITLE
Broken Link @ master/reference-architecture/aws-ansible 'Gluster Storage' 404 error

### ISSUE THREAD

**Issue by sensiblemedia** [openshift/openshift-ansible-contrib#640]
Hi Folks, just informing you that there is a broken link on the following page at 'Gluster Storage'
https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible

Broken link, 404 error:
https://access.redhat.com/documentation/en-us/reference_architectures/2017/html/deploying_openshift_container_platform_3_on_amazon_web_services/#persistent_storage

Cheers,
SRG

**Comment by cooktheryan** [comment]
Thank you!!!
