### ISSUE TITLE
subscription-manager rhsm_repos var should be more idempotent.

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible-contrib#658]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

# FEATURE REQUEST INFO:

When re-running the subscription-manager role against a host that has already been subscribed, we should re-enable the repo list to ensure that the proper repos have been enabled.

For example:

Run1:
```
# # Subscription Management Details
rhsm_register: True
rhsm_satellite: 'sat.example.com'
rhsm_org: 'MY_ORG'
rhsm_activationkey: 'openshift'

rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.5-rpms"
 - "rhel-7-server-extras-rpms"
```

Followed by Run 2:
```
# # Subscription Management Details
rhsm_register: True
rhsm_satellite: 'sat.example.com'
rhsm_org: 'MY_ORG'
rhsm_activationkey: 'openshift'

rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.5-rpms"
 - "rhel-7-server-extras-rpms"
 - "rhel-7-fast-datapath-rpms"
```

Should result in 4 repos being enabled. However currently, if a host is already registered, we skip the entire role. We should change this to skip only the registration block.

@oybed

**Comment by oybed** [comment]
@etsauer we should like this with the already open issue in https://github.com/redhat-cop/casl-ansible
https://github.com/redhat-cop/casl-ansible/issues/35

We also have this `rhsm` role that is already idempotent and does what you are requesting - it may just be a matter of porting this over: 
https://github.com/redhat-cop/infra-ansible/tree/master/roles/rhsm

However, I believe the folks here have another plan for subscriptions. Maybe that's a bit longer term, and we can use the above in the meantime, but I'll let @bogdando @cooktheryan @tomassedovic comment on this plan.

**Comment by cooktheryan** [comment]
I believe our long term plan is to use this module

https://github.com/openshift/openshift-ansible/tree/master/roles/rhel_subscribe

**Comment by oybed** [comment]
@cooktheryan that module seems to be very opinionated and has hardcoded values rather than letting the inventory drive it. Do you know if there's a plan to improve this? The `rhsm` role mentioned above sources all its information from the inventory and hence is generic (although it could potentially use some additional work in other areas).

**Comment by cooktheryan** [comment]
@oybed we definitely should seek to make it better in openshift-ansible.  A strong focus and goal that we have is to use as much upstream as we possibly can.

**Comment by dav1x** [comment]
@oybed @cooktheryan  I've done some work to add it via a PR. There is some room to extend it. The repo part is indeed idempotent, but the registration portion is not. Perhaps, the yum repolist should be called before the registration portion and it the repos already exist skip the subscription-manager portion. 

Thoughts?

**Comment by oybed** [comment]
@dav1x are you referring to the `subscription-manager` role in this contrib repo (the one that came from the `casl-ansible` repo)? If so, I'd recommend taking a look at the `rhsm` role in the `infra-ansible` repo as it pretty much does what @etsauer is after - and it is idempotent on both the registration part as well as the repo enabe/disable part. 

https://github.com/redhat-cop/infra-ansible/blob/master/roles/rhsm/tasks/main.yml

**Comment by dav1x** [comment]
Here is the task im issuing:
----
    - name: 'Register system using Red Hat Subscription Manager'
      redhat_subscription:
        state: present
        username: "{{ rhsm_user | default(omit) }}"
        password: "{{ rhsm_password | default(omit) }}"
        pool: "{{ rhsm_pool | default(omit) }}"
        server_hostname: "{{ rhsm_satellite | default(omit) }}"
        activationkey: "{{ rhsm_activation_key | default(omit) }}"
        org_id: "{{ rhsm_org_id | default(omit) }}"
----
TASK [rhsm : Is the system already registered?] **********************************************************************************************************************************************************************
changed: [nfs-0]

https://github.com/ansible/ansible/blob/d8b1cb9a634d0e828a7be39d4019a6215410e643/lib/ansible/modules/packaging/os/redhat_subscription.py#L747-L760

I'm looking at the code and it looks right. But, it should be setting changed to false and exiting.

**Comment by oybed** [comment]
Interesting - let me double check as this has worked for us many times. 
In the meantime: what version are you using of `ansible`?

**Comment by dav1x** [comment]
-> ansible --version
ansible 2.3.1.0

But, upstream devel has the same logic check. I can submit a PR for redhat_subscription and work on a fix for it myself if need be. 

[root@app-0 ~]# subscription-manager list --consumed | grep "Subscription Name" | wc -l
8
[root@app-0 ~]# subscription-manager list --consumed | grep "Subscription Name" | wc -l
10

**Comment by dav1x** [comment]
This is closed
