### ISSUE TITLE
Origin 3.6  dbus python bindings

### ISSUE THREAD

**Issue by daveconde** [openshift/openshift-ansible-contrib#660]
Cluster was upgraded from Origin 3.5 to 3.6, now when running add-node.py I get the error below. Python dbus is installed on the nodes.

**Environment**:
- **AWS:**

- **OS Linux 3.10.0-327.10.1.el7.x86_64 x86_64
            NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7":**

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`): 4de1447**

**Output of ansible run**:
TASK [non-atomic-docker-storage-setup : Gather facts] **************************
fatal: [xxx: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires dbus python bindings"}

**Comment by cooktheryan** [comment]
do you have the centos AMI you based off of handy?

**Comment by cooktheryan** [comment]
also @daveconde containerized or not?

**Comment by daveconde** [comment]
AMI: ami-7abd0209
Non containerized

**Comment by daveconde** [comment]
I just sucked in the latest changes around become: true and I'm seeing the following instead

TASK [non-atomic-docker-storage-setup : Gather facts] **************************
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}

**Comment by daveconde** [comment]
fatal: [xxxx]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\n", "module_stdout": "", "msg": "MODULE FAILURE"}

Similar to above but now complains about tty instead

**Comment by cooktheryan** [comment]
For this one modify ansible.cfg and comment out this line pipelining = True

It appears that in rhel 7.4 and up the requiretty line is removed from /etc/sudoers but it has not yet made it into centos

**Comment by cooktheryan** [comment]
judging by this i may end up rolling back the pipelining=true line in ansible.cfg

**Comment by daveconde** [comment]
It has moved on further but now fails starting docker on the new node with the error

level=fatal msg="Error starting daemon: SELinux is ...false)"

**Comment by cooktheryan** [comment]
Coding this fix now

**Comment by daveconde** [comment]
Thanks :)

**Comment by daveconde** [comment]
Can test it for you when ready

**Comment by cooktheryan** [comment]
@daveconde in the mean time may have to clean up the attempt at docker volume creation on that new host because i believe the vg. pv, and lvm are created but there is some sort of centos bug that will not allow overlay2 to be fully supported

**Comment by daveconde** [comment]
I'll nuke the new host and go again with a fresh one

**Comment by cooktheryan** [comment]
Cool. Performing a test deploy now. Should have you some info in about 5 minutes

**Comment by cooktheryan** [comment]
@daveconde let's see how things are now. Both my tests passed

**Comment by daveconde** [comment]
Bingo, yep node came up and was added to cluster. Thanks a million. Would it be possible to create a 3.6 release branch from that to keep it stable?

Thanks again for fast turn around on it 💯
