### ISSUE TITLE
ca.serial.txt missing kills the install with 3.6

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-ansible-contrib#667]
# BUG REQUEST INFO:

**Environment**:
- **Cloud provider:** AWS

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):**

All the machines are in AWS: installer which hosts this repo and installer tools is a micro instance, and it creates the OCP cluster by this repo using rhel 7.4 template.

```
$ uname -srm; cat /etc/os-release
Linux 3.10.0-693.1.1.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Employee SKU"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

```

- **Version of Ansible:** (`ansible --version`):

> $ rpm -q ansible
> ansible-2.3.1.0-3.el7.noarch

- **Version of Jinja:** (`pip freeze | grep -i jinja`)

> $ pip freeze | grep -i jinja
> Jinja2==2.7.2

- **Version of Shade:** (`pip freeze | grep -i shade`)

no such installed 

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):**

> $ git rev-parse --short HEAD
> 1ce66d0
> 

**Copy of used inventory files and custom variables (please omit your secrets!):**

nothing extra

**Command used to invoke ansible**:

```
./ose-on-aws.py --keypair=$AWS_KEY --rhsm-user=$RHUSER --rhsm-password=$RHPWD \
  --public-hosted-zone=$DOMAIN --rhsm-pool=$RHPOOL \
  --deployment-type=openshift-enterprise --region=eu-west-1 \
  --ami=ami-bb9a6bc2  --app-dns-prefix=apps  \
  --containerized=true \
  --github-client-id $GH_CID --github-client-secret $GH_CSEC \
  --github-organization $GH_ORG --app-node-count 2
```

**Output of ansible run**:

```
TASK [openshift_master_certificates : Create the master server certificate] ****************************
skipping: [ose-master01.xxx] => (item=ose-master01.xxx) 
failed: [ose-master01.xxx -> ose-master01.xxx] (item=ose-master02.xxx) => {
    "changed": true, 
    "cmd": [
        "/usr/local/bin/oc", 
        "adm", 
        "ca", 
        "create-server-cert", 
        "--hostnames=172.30.0.1,kubernetes.default,internal-openshift-master.xxx,10.20.xxx,op
enshift.default,openshift-master.xxx,openshift.default.svc,ip-10-20-xxx.eu-west-1.compute.int
ernal,kubernetes,openshift.default.svc.cluster.local,kubernetes.default.svc,kubernetes.default.svc.clust
er.local,openshift", 
        "--cert=/etc/origin/generated-configs/master-ip-10-20xxx.eu-west-1.compute.internal/master.se
rver.crt", 
        "--key=/etc/origin/generated-configs/master-ip-10-20-xxx.eu-west-1.compute.internal/master.ser
ver.key", 
        "--expire-days=730", 
        "--signer-cert=/etc/origin/master/ca.crt", 
        "--signer-key=/etc/origin/master/ca.key", 
        "--signer-serial=/etc/origin/master/ca.serial.txt", 
        "--overwrite=false"
    ], 
    "delta": "0:00:00.175529", 
    "end": "2017-08-18 20:03:23.015585", 
    "failed": true, 
    "item": "ose-master02.xxx", 
    "rc": 1, 
    "start": "2017-08-18 20:03:22.840056"
}

STDERR:

error: --signer-serial, "/etc/origin/master/ca.serial.txt" must be a valid file
See 'oc adm ca create-server-cert -h' for help and examples.
```

**Anything else do we need to know**:

I had to run the installer several times, as it stopped to different reasons. E.g. not being able to allocate memory, possibly micro instance is too small for ansible. But however, it got past all those, and ansible here didn't make sure if the ca.serial.txt file exists as it should. If the file didn't get created because of earlier failures, it should still be ensured to exist with some dummy value.

E. Rich from Red Hat found the spot where this fails, and his comments were:

> I think you have a bug that you need to file: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master_certificates/tasks/main.yml#L48-L72 is the code your erroring on. 
> 
> However nowhere before this do we check / validate that we have the serial file. Using https://github.com/openshift/openshift-ansible/search?utf8=%E2%9C%93&q=openshift_ca_serial&type= I can't see where we ensure that file is created. To work around this just touch the file, or `echo 1 > file` on the server and re-run it should fix the issue. 
> 

I now echoed the 1 into serial file, I'll report back how it succeeded

**Comment by cooktheryan** [comment]
This is a known downfall of the dynamic inventory. It has to do with no master being officially defined as the "first master" unlike the static inventory. In the appendix of the ref arch we have it defined how to work around this. I do not see us fixing this before the long term solution that is coming in 3.7.

**Comment by daveconde** [comment]
Also seeing this on 3.6, its a total pain to be honest as it adds manual steps in to adding new nodes. Is there anything that could be done in Ansible to keep the files in sync until 3.7 is released? Surely its just a case of reading all 3 files and pushing the highest number out to all masters?

**Comment by mwoodson** [comment]
For the record, this has bitten Openshift Ops.  Since there isn't a "primary master" or "first master" ever defined, re-arranging the order of the masters in the inventory is breaking scale-ups.

**Comment by e-minguez** [comment]
Azure ref. arch. contains a workaround in the post installation steps ([just copying ca.serial.txt from the first master to the masters](https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/azure-ansible/3.6/bastion.sh#L727-L728))

**Comment by waynedovey** [comment]
This needs to be fixed, not a workaround. Thanks :)
