### ISSUE TITLE
add-node.py : Populate AWS data

### ISSUE THREAD

**Issue by jbrannst** [openshift/openshift-ansible-contrib#68]
As a user I want to add a node to my cluster, I know the size and what it should do. I have my credentials ready. I'd preferably not need to dig into the detailed network/security setup of my cluster...

add_node.py
Things the user can easily specify
    region: eu-west-1
    node_instance_type: r3.xlarge
    keypair: OpenShift-Key
    public_hosted_zone: ocp.rocks
    shortname: ose-app-node04
    rhsm_user: jbrannst
    rhsm_password: *******
    rhsm_pool: Employee SKU

Items that are hard to specify that we should be able to provide defaults for, if needed by querying AWS:
    ami: ami-ce66d8bd 
(can be looked up, by hardcoded table, per region as suggested in another thread)
    subnet_id: subnet-44763020 
(as there are typically 3 relevant options they should be printed, one selected and asking the user to confirm or input another option)
    node_sg: sg-f62ce390 
(there is typically only one option)
    iam_role: OpenShift-Infra-NodeInstanceProfile-8DDK8K32INSK 
(also only one option)

I have no idea how hard this would be to do, but it would definitely be a boost to user experience

**Comment by cooktheryan** [comment]
@jbrannst definitely agree. This weekend I found out about the cloudformation lookup module. Hopefully will have something in the near future.

**Comment by cooktheryan** [comment]
This is resolved now with use-cloudformation-facts option
