### ISSUE TITLE
Master nova server(s) are missing etcd sec group, when no dedicated etcd cluster nodes

### ISSUE THREAD

**Issue by bogdando** [openshift/openshift-ansible-contrib#684]
# BUG REQUEST INFO:

**Environment**: critical for multi-master, not a big deal for a single master
- **Cloud provider:** openstack

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** centos7

- **Version of Ansible:** (`ansible --version`): n/a

- **Version of Jinja:** (`pip freeze | grep -i jinja`) n/a

- **Version of Shade:** (`pip freeze | grep -i shade`) n/a

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):** 9c375c8

**Copy of used inventory files and custom variables (please omit your secrets!):** defaults

**Command used to invoke ansible**: the main deployment

**Output of ansible run**:
`etcd : Enable etcd` task fails

**Anything else do we need to know**:
Master nova server(s) are missing etcd sec group, when provisioning with `openstack_flat_secgrp: false` and `openstack_num_etcd: 0` (those are defaults):
```
| security_groups             | name='openshift-ansible-openshift.cluster.lc-common-secgrp'                                                                                      |
|                             | name='openshift-ansible-openshift.cluster.lc-master-secgrp'                                                                                      |
|                             | name='openshift-ansible-openshift.cluster.lc-node-secgrp'
```
This only affects multi-master setup when etcd nodes must communicate via 2379/2380 ports across cluster nodes.

**Comment by tomassedovic** [comment]
This has been resolved by PR #685. I'm closing the issue.
