### ISSUE TITLE
AWS Cluster AutoScaler

### ISSUE THREAD

**Issue by daveconde** [openshift/openshift-ansible-contrib#696]
Would it be possible to add support for https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler in to the AWS reference architecture?

**Comment by sdodson** [comment]
We're looking at adding this to the aws provisioning work that's landed in openshift-ansible (not openshift-ansible-contrib) but we're dependent on an origin auto scaler image.

**Comment by daveconde** [comment]
Awesome thanks
