### ISSUE TITLE
ose-on-aws.py fails during "openshift_logging : template" with "a password is required"

### ISSUE THREAD

**Issue by atgreen** [openshift/openshift-ansible-contrib#743]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

# BUG REQUEST INFO:

**Environment**:
- **Cloud provider:** 
aws

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):**
Linux 3.10.0-693.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Employee SKU"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"

- **Version of Ansible:** (`ansible --version`):
ansible 2.3.2.0
  config file = /home/green/git/openshift-ansible-contrib/reference-architecture/aws-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

- **Version of Jinja:** (`pip freeze | grep -i jinja`)
pip: command not found, but...
python-jinja2-2.7.2-2.el7.noarch

- **Version of Shade:** (`pip freeze | grep -i shade`)
pip: command not found
and no shade rpm found

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):**
42bba54

**Copy of used inventory files and custom variables (please omit your secrets!):**

**Command used to invoke ansible**:
./ose-on-aws.py \
    --stack-name=expo1 \
    --public-hosted-zone=rbcexpo.com \
    --rhsm-user=REDACTED \
    --rhsm-password=REDACTED \
    --rhsm-pool="Employee SKU" \
    --github-client-secret=REDACTED \
    --github-client-id=REDACTED \
    --github-organization=devopsexpo \
    --keypair=OSE-key \
    --create-key=yes \
    --key-path=/home/green/.ssh/id_rsa.pub \
    --s3-bucket-name=expo-registry  \
    --s3-username s4expouser \
    --ami=ami-c998b6b2 \
    --verbose

**Output of ansible run**:

TASK [openshift_logging : template] *******************************************************************************************
fatal: [ose-master02.rbcexpo.com]: FAILED! => {
    "failed": true
}

MSG:

Failed to get information on remote file (/tmp/openshift-logging-ansible-3e0njw/signing.conf): sudo: a password is required

**Anything else do we need to know**:

# FEATURE REQUEST INFO:

An introduction paragraph with "[tl;dr]" info.

## **Problem Description**

What problem is being solved by the proposed feature?
What use cases are for End User vs Deployer? Describe the target Cloud provider
as well.

## **Implementation**

Describe your plan for implementation steps and potential
assignees/contributors.

## **Acceptance criteria**

Provide a definition of done and acceptance criteria.

## **Testing**

Describe how to test this, including manual steps, if any.

**Comment by rhmk** [comment]
HI any progress on this. Just ran into the same problem?

**Comment by cooktheryan** [comment]
Right now the work around is running ose-on-aws as root. The latest openshift rpms either solve this or will solve this in the future

**Comment by rhmk** [comment]
OK, thanks. I ran it with disable logging and metrics. That worked as well.
