### ISSUE TITLE
Error parsing template file ... stack.yaml while parsing a block collection

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible-contrib#746]
# BUG REQUEST INFO:

**Environment**:
- **Cloud provider:** OpenStack

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** Linux 4.11.8-300.fc26.x86_64 x86_64 Fedora26

- **Version of Ansible:** (`ansible --version`): ansible 2.4.0.0

- **Version of Jinja:** (`pip freeze | grep -i jinja`): Jinja2==2.9.6

- **Version of Shade:** (`pip freeze | grep -i shade`): shade==1.23.0

**Openstack-ansible-contrib version (commit) (`git rev-parse --short HEAD`):** 2f3ec73 (master branch Already up-to-date)

**Copy of used inventory files and custom variables (please omit your secrets!):** https://gist.github.com/mbruzek/fda25a425544c98e730a7fa6c5f0b4f5

**Command used to invoke ansible**: `$ source ~/keystonerc; ansible-playbook openshift-ansible-contrib/playbooks/provisioning/openstack/provision.yaml 2>&1 > openshift-ansible-contrib_log.txt`

**Output of ansible run**: 
```
TASK [openstack-stack : create stack] *****************************************************************************************************************************************************************************
Tuesday 19 September 2017  20:25:55 +0000 (0:00:00.185)       0:00:11.111 *****
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error parsing template file:///tmp/casl-ansibleX2hQJN/stack.yaml while parsing a block collection\n  in \"<unicode string>\", line 432, column 13:\n                - { get_resource: lb-secgrp }\n                ^\nexpected <block end>, but found '<block mapping start>'\n  in \"<unicode string>\", line 434, column 15:\n                  floating_network: public_network\n                  ^"}
```
Link to complete playbook output: https://gist.github.com/mbruzek/fda25a425544c98e730a7fa6c5f0b4f5

**Anything else do we need to know**: I am attempting to follow the README located here:
https://github.com/openshift/openshift-ansible-contrib/tree/master/playbooks/provisioning/openstack#run-the-playbook 
The README indicates that running this way "start with an empty inventory" and therefore

**Comment by tzumainn** [comment]
This looks like the same error I ran into! The (hopefully correct) fix is here: https://github.com/openshift/openshift-ansible-contrib/pull/745

**Comment by mbruzek** [comment]
I don't see this problem any longer, #745 must have been the one that fixed it.
