### ISSUE TITLE
VolumeAttachment.mountpoint is not reliable and should not be used

### ISSUE THREAD

**Issue by ioggstream** [openshift/openshift-ansible-contrib#758]
# BUG REQUEST INFO:

**Environment**:
- **Cloud provider:** RHOSP 10

**Anything else do we need to know**:
- when using multiple cinder volumes, openshift-ansible may not be able to distinguish between volumes.

## I expect

As OS::Cinder::VolumeAttachment.mountpoint is unreliable as stated in the doc 
https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Cinder::VolumeAttachment-prop-mountpoint

I expect 
openshift-ansible-contrib heat templates not to use  it in 
https://github.com/openshift/openshift-ansible-contrib/blob/master/roles/openstack-stack/templates/heat_stack_server.yaml.j2#L196

**Comment by tomassedovic** [comment]
Good point, thanks! We should fix this. Looking at the code, we're not actually relying on the hardcoded `mountpoint` value, but that makes it even more confusing.

**Comment by ioggstream** [comment]
@tomassedovic iiuc it's used in the docker-storage-setup role.  https://github.com/openshift/openshift-ansible-contrib/blob/master/roles/docker-storage-setup/defaults/main.yaml#L2

If you add more volumes (eg. etcd, ...) you could experience the issue.

**Comment by tomassedovic** [comment]
@ioggstream that's true, but the Openstack playbooks are not using it yet.

I do plan to switch to it and when we do, I'll remove the mountpoint from our heat templates.
