### ISSUE TITLE
Infinite loop: "Sending SSH keep-alive..."

### ISSUE THREAD

**Issue by dtpest** [openshift/openshift-ansible-contrib#78]
Hi,

vagrant up --provider=libvirt --debug results in an infinte loop.

==> node1: Updating /etc/hosts file on host machine (password may be required)...
 INFO environment: Getting machine: node1 (libvirt)
 INFO environment: Returning cached machine: node1 (libvirt)
 INFO environment: Getting machine: admin1 (libvirt)
 INFO environment: Returning cached machine: admin1 (libvirt)
 INFO warden: Calling OUT action: #VagrantPlugins::HostManager::Action::UpdateAll:0x0000000352d6d8
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x0000000352d728
 INFO provision: Writing provisioning sentinel so we don't provision again
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::Provision:0x00000003565808
 INFO warden: Calling OUT action: #VagrantPlugins::ProviderLibvirt::Action::CreateDomain:0x000000035a4990
 INFO warden: Calling OUT action: #VagrantPlugins::ProviderLibvirt::Action::CreateDomainVolume:0x0000000360b8c0
 INFO warden: Calling OUT action: #VagrantPlugins::ProviderLibvirt::Action::HandleBoxImage:0x0000000364bdd0
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::HandleBox:0x0000000368feb8
 INFO warden: Calling OUT action: #VagrantPlugins::ProviderLibvirt::Action::HandleStoragePool:0x000000036e4878
 INFO warden: Calling OUT action: #VagrantPlugins::ProviderLibvirt::Action::SetNameOfDomain:0x00000003728d70
 INFO warden: Calling OUT action: #<Proc:0x000000037acd28@/opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::Call:0x000000036ec230
 INFO warden: Calling OUT action: #Vagrant::Action::Builtin::ConfigValidate:0x000000036ec280
 INFO interface: Machine: action ["up", "end", {:target=>:node1}]
 INFO environment: Released process lock: machine-action-258d7116eec64fc595d6c05f5e723d3c
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
...

Best,
Peter

**Comment by dtpest** [comment]
@detiber Andy ideas?

**Comment by detiber** [comment]
@dtpest is vagrant-cachier in use? I was hitting issues with it while using the libvirt plugin.

**Comment by dtpest** [comment]
@detiber Not manually installed and if it is no requirement from another plugin, than it should not be installed.

**Comment by cgwalters** [comment]
I hacked around this in https://github.com/openshift/openshift-ansible-contrib/pull/132 :arrow_right: https://github.com/openshift/openshift-ansible-contrib/pull/132/commits/6bfb7b615fc083fd6add59fc433fa6ca747fae3e
