### ISSUE TITLE
Running playbooks/provisioning/openstack/provision.yaml results in an AttributeError

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible-contrib#800]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

```
TASK [openstack-stack : Handle the Stack (create/delete)] ****************************************************************************************************
task path: /home/cloud-user/openshift-ansible-contrib/roles/openstack-stack/tasks/main.yml:8
Thursday 12 October 2017  17:32:14 -0400 (0:00:00.244)       0:00:18.613 ****** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'bool' object has no attribute 'id'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4SwNda/ansible_module_os_stack.py\", line 273, in <module>\n    main()\n  File \"/tmp/ansible_4SwNda/ansible_module_os_stack.py\", line 258, in main\n    id=stack.id)\nAttributeError: 'bool' object has no attribute 'id'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Environment**: scale-ci
- **Cloud provider**: OpenStack 

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`)**: 
```
Linux 3.10.0-733.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
```

- **Version of Ansible:** (`ansible --version`):
```
ansible 2.3.2.0
  config file = /home/cloud-user/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct  3 2017, 11:17:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

- **Version of Jinja:** (`pip freeze | grep -i jinja`) Jinja2==2.7.2

- **Version of Shade:** (`pip freeze | grep -i shade`) shade==1.23.0

**Openshift-ansible-contrib version (commit) (`git rev-parse --short HEAD`):** a52422a

**Copy of used inventory files and custom variables (please omit your secrets!):**
all.yml (summary):
```
env_id: "scale-ci"
public_dns_domain: "example.com"
public_dns_nameservers: [10.11.5.19, 10.12.64.173]
openstack_ssh_public_key: "ci_keypair"
openstack_external_network_name: "public_network"
openstack_default_image_name: "ocp-3.7-rhel"

openstack_num_masters: 3
openstack_num_infra: 3
openstack_num_nodes: 2
openstack_master_flavor: "master_etcd" (yeah all the flavors are defined)
openstack_infra_flavor: "load_balancer"
openstack_node_flavor: "node_small"
openstack_lb_flavor: "load_balancer"
openstack_default_flavor: "m1.medium"
docker_volume_size: "15"
openstack_subnet_prefix: "192.168.99"
ansible_user: openshift
openstack_private_ssh_key: ~/.ssh/openstack
ephemeral_volumes: true
```
**Command used to invoke ansible**:
`source /home/cloud-user/keystonerc; ansible-playbook -vv openshift-ansible-contrib/playbooks/provisioning/openstack/provision.yaml 2>&1 > openstack_provision_log.txt`

**Output of ansible run**:
https://gist.github.com/mbruzek/6954c90107bdb3cadb9108ec2934e545

**Anything else do we need to know**:
I ran this as an automated process configuring the all.yml file programmatically. The all.yml is not complete, I omitted the comments.

**Comment by mbruzek** [comment]
Update:

Looks like the stack failed to complete. Running `openstack stack show scale-ci.example.com` gives me more insight to the error:  
```
Resource CREATE failed: ResourceInError: resources.compute_nodes.resources[0].resources.server: Went to status ERROR due to "Message
: Build of instance 1192a6c4-442f-41db-a565-d625cd219d67 aborted: Flavor's disk is too small for requested image. Flavor disk is 34359738368 bytes, image is 5
4760833024 bytes., Code: 500"
```

**Comment by mbruzek** [comment]
I had the following appended to the OSEv3.yml file: 
```yml
# BEGIN ANSIBLE MANAGED BLOCK
openshift_disable_check: disk_availability,memory_availability,docker_storage

openshift_master_identity_providers:
- name: 'htpasswd_auth'
  login: 'true'
  challenge: 'true'
  kind: 'HTPasswdPasswordIdentityProvider'
  filename: '/etc/origin/master/htpasswd'

openshift_master_htpasswd_users:
  demo: '<hash value>'
# END ANSIBLE MANAGED BLOCK
```

**Comment by tomassedovic** [comment]
OSEv3 disables the OpenShift checks. But if this is coming from Heat, it means it's an openstack thing.

Try creating a VM with the same flavor and image manually. My guess is, you'll encounter the same issue. Some openstack images have a minimum disk size requirements and you just need a flavor that fits.

How did you get the image? Is there any chance you built it from a snapshot of a VM running on a larger flavor?

**Comment by mbruzek** [comment]
The error message that the end user got was some kind of ugly Python error. I really had to dig to get the real cause of the error that the image was larger than the flavor size. We can do better. It should be possible to add a check like this to provide a better error message to the user. This is not all on you and your team, I can help develop a check like this (time permitting).

@tomassedovic the image I am using is the OCP-3.7-rhel image that is built from the latest puddle. I think they are 51 GiB in size and the flavor was configured for 32 GiB.

**Comment by mbruzek** [comment]
This problem resulted from one of the images being larger than the flavor associated with that. Not something everyone would know to check, so it is reasonable to assume this could happen again.
I did some experiments and believe some commands could help us prevent this error in the future.

`openstack image show {{ openstack_default_image_name }} --format value -c min_disk`
When this value is not zero continue.
`openstack flavor show {{ openstack_default_flavor }} --format value -c disk`
Abort or warn if image_disk is greater than flavor_disk .
