### ISSUE TITLE
AWS - Cloud provider question

### ISSUE THREAD

**Issue by stuartbfox** [openshift/openshift-ansible-contrib#81]
Me again :)

Im reading this [doc](https://docs.openshift.org/latest/install_config/configuring_aws.html) on OCP/AWS integration but cant find the AWS_ vars in any of the specified files.

Am I missing something?

**Comment by detiber** [comment]
@stuartbfox I wouldn't necessarily expect the reference architecture to leverage the AWS_* env vars in particular. That said, those variables are used for configuring the cloud provider integration, which is handled through IAM profiles in the ref-arch.

**Comment by stuartbfox** [comment]
But doesn't the openshift master/node processes need those environment variables to talk to the aws api's? All I can find in `/etc/origin/cloudprovider/aws.conf`
is
```
[Global]
Zone = us-east-1a
```

**Comment by detiber** [comment]
@stuartbfox the variables are only needed if the hosts do not have iam profiles that allow the needed access.

**Comment by cooktheryan** [comment]
With the ref arch cloudformations we add the required iam components to the instance at launch so we don't export the access id and secret

**Comment by stuartbfox** [comment]
Perfect! thanks
