### ISSUE TITLE
Failed to deploy openshift origin v3.7.0

### ISSUE THREAD

**Issue by ccll** [openshift/openshift-ansible-contrib#828]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):
**BUG REPORT**

# BUG REPORT INFO

### Environment

- **Cloud provider**:  
GCE

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  

```
Linux 3.10.0-693.2.2.el7.x86_64 x86_64
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Version of Ansible** (`ansible --version`):  
```
  ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

- **Version of Jinja** (`pip freeze | grep -i jinja`):  
N/A

- **Version of Shade** (`pip freeze | grep -i shade`):  
N/A

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  
1d45f20

**Copy of inventory files and custom variables used (please omit your secrets!)**:  

```
# openshift-ansible-contrib/reference-architecture/gcp/config.yaml
...

# OpenShift deployment type
# Use 'origin' to deploy OpenShift Origin on top of CentOS 7
openshift_deployment_type: origin
# Deploy OpenShift within containers instead of RPMs?
containerized: false

# OpenShift SDN selection
# options are 'redhat/openshift-ovs-multitenant', 'redhat/openshift-ovs-subnet'
os_sdn_network_plugin_name: 'redhat/openshift-ovs-subnet'

...
```

```
# openshift-ansible-contrib/reference-architecture/gcp/ansible/playbooks/openshift-installer-common-vars.yaml

...
openshift_release: 3.7.0
...
```

**Command used to invoke ansible**:  
```cd openshift-ansible-contrib/reference-architecture/gcp && ./ocp-on-gcp.sh```

**Output of ansible run**:  

```
...

Failure summary:


  1. Hosts:    ocp-master-0903
     Play:     Determine openshift_version to configure on first master
     Task:     For an RPM install, abort when the release requested does not match the available version.
     Message:  You requested openshift_release 3.7, which is not matched by
               the latest OpenShift RPM we detected as origin-3.6.0
               on host ocp-master-0903.
               We will only install the latest RPMs, so please ensure you are getting the release
               you expect. You may need to adjust your Ansible inventory, modify the repositories
               available on the host, or run the appropriate OpenShift upgrade playbook.

```

**Comment by pschiffe** [comment]
Instead of `openshift_release` variable in  `openshift-installer-common-vars.yaml` try to define `openshift_major_version: 7` in your `config.yaml` file. See here [1]. But there is also no `release-3.7` branch in openshift installer, so you will probably need `openshift_ansible_branch: master` as well. But basically in origin deployment, this package dictates the OpenShift version [2].

[1] https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/gcp/ansible/playbooks/group_vars/all#L5
[2] https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/gcp/ansible/playbooks/roles/gold-image-instance/tasks/main.yaml#L13

**Comment by ccll** [comment]
@pschiffe Thanks, finally I got  v3.7.0-rc.0 deployed with this config:
```
containerized: true
openshift_image_tag: "v3.7.0-rc.0"
openshift_pkg_version: "-3.6.0"
```

The main Openshift components are installed from containerized image, but some components like `excluder` still uses a RPM installation by default and do not have a v3.7 RPM release yet, I suppose these are not that important so I kept them in v3.6.
