### ISSUE TITLE
Greenfield AWS ref arch, rhel cert error

### ISSUE THREAD

**Issue by laupow** [openshift/openshift-ansible-contrib#840]
The greenfield AWS architecture playbooks fail at the `TASK [etcd : Pull etcd container]` step in the `openshift-ansible@release-3.6` playbooks. 

The symlink `/etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt -> /etc/rhsm/ca/redhat-uep.pem` doesn't work. I'm trying to deploy Origin on CentOS7, so I'm not surprised this symlink doesn't work. 

From the aws reference architecture readme, I get the impression that I should be able to deploy Origin on CentOS7 with the tool.

I'm submitting the bug here because I have a hunch it's related to the parameters passed to the `openshift-ansible` playbooks (but I'm not certain).

# BUG REPORT INFO

### Environment

- **Cloud provider**:  AWS

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
```
Linux 3.10.0-514.10.2.el7.x86_64 x86_64
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Version of Ansible** (`ansible --version`):  
```
ansible 2.3.3.0
  config file = /home/ec2-user/openshift-ansible-contrib/reference-architecture/aws-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
- **Version of Jinja** (`pip freeze | grep -i jinja`):  
```
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Jinja2==2.9.6
```

- **Version of Shade** (`pip freeze | grep -i shade`):  not installed

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  3857ac0

**Copy of inventory files and custom variables used (please omit your secrets!)**:  
Possible bug fixes:
```
[ec2-user@ip-172-31-8-46 aws-ansible]$ git diff
diff --git a/reference-architecture/aws-ansible/ansible.cfg b/reference-architecture/aws-ansible/ansible.cfg
index 0373b80..c53d1b7 100644
--- a/reference-architecture/aws-ansible/ansible.cfg
+++ b/reference-architecture/aws-ansible/ansible.cfg
@@ -10,7 +10,7 @@ remote_user = ec2-user
 gathering = smart
 retry_files_enabled = false
 nocows = true
-timeout = 30
+timeout = 600
 #lookup_plugins = ./playbooks/lookup_plugins
 #log_path = /tmp/ansible.log
 
diff --git a/reference-architecture/aws-ansible/playbooks/openshift-setup.yaml b/reference-architecture/aws-ansible/playbooks/openshift-setup.yaml
index 4ce075a..e59e90b 100644
--- a/reference-architecture/aws-ansible/playbooks/openshift-setup.yaml
+++ b/reference-architecture/aws-ansible/playbooks/openshift-setup.yaml
@@ -71,3 +71,5 @@
     openshift_logging_es_nodeselector: {"role":"infra"}
     openshift_logging_kibana_nodeselector: {"role":"infra"}
     openshift_logging_curator_nodeselector: {"role":"infra"}
+    
+    openshift_disable_check: docker_image_availability,docker_storage
```

**Command used to invoke ansible**:  
```
./ose-on-aws.py --keypair=mlauer-openshift2017 --public-hosted-zone=carlwebtest.com --deployment-type=origin --ami=ami-0c2aba6c --github-client-secret=<snip> --github-organization=carleton --github-client-id=<snip> --containerized=true --region=us-west-2
```

```
Configured values:
	stack_name: openshift-infra
	ami: ami-0c2aba6c
	region: us-west-2
	master_instance_type: m4.xlarge
	node_instance_type: t2.large
	app_instance_type: t2.large
	app_node_count: 3
	keypair: mlauer-openshift2017
	create_key: no
	key_path: /dev/null
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: origin
	openshift_sdn: redhat/openshift-ovs-multitenant
	public_hosted_zone: carlwebtest.com
	app_dns_prefix: apps
	apps_dns: apps.carlwebtest.com
	containerized: true
	s3_bucket_name: openshift-infra-ocp-registry-carlwebtest
	s3_username: openshift-infra-s3-openshift-user
	github_client_id: *******
	github_client_secret: *******
	github_organization: carleton
	openshift_metrics_deploy: true
	openshift_metrics_storage_volume_size: 20Gi
	openshift_logging_deploy: true
	openshift_logging_storage_volume_size: 100Gi
```

**Output of ansible run**:  

https://gist.github.com/laupow/00f71e604bb0039bdd506072b796089e

**Anything else do we need to know**:  
I'm using the AWS  CentOS7 ami: `CentOS Linux 7 x86_64 HVM EBS 1703_01 (ami-0c2aba6c)`

This behavior is repeatable, at least for me :)
 1. follow the setup and configuration steps in the aws reference architecture readme for a greenfield Origin deployment
 1. checkout the `release-36` branch for openshift-ansible on the control machine
 1. run the `ose-on-aws` command above, and [it dies](https://gist.github.com/laupow/00f71e604bb0039bdd506072b796089e#file-centos7-openshift-aws-reference-arch-failure-L6954).

**Comment by cooktheryan** [comment]
add the following to the aws-ansible/playbooks/openshift-setup.yaml


```
osm_etcd_image: registry.fedoraproject.org/f26/etcd
```

**Comment by e-minguez** [comment]
Related -> https://github.com/openshift/openshift-ansible/issues/6018

**Comment by laupow** [comment]
Thanks, guys. I'll follow openshift/openshift-ansible#6018 for now and close this thread.
