### ISSUE TITLE
Unable to scale nodes on gcp

### ISSUE THREAD

**Issue by vikasroonwal** [openshift/openshift-ansible-contrib#846]
Unable to scaleup an existing setup on GCP. Need to add a few more nodes and keep running into this issue.

**BUG REPORT**

# BUG REPORT INFO

### Environment

- **Cloud provider**:  GCP

- **OS details** : RHEL 7.4  

- **Version of Ansible** : 2.4.0.0  

- **Version of Jinja** :  2.7.2

- **The openstack-ansible-contrib version (commit)** :  4382587

**Copy of inventory files and custom variables used (please omit your secrets!)**:  

**Command used to invoke ansible**:  ./ocp-on-gcp.sh --scaleup

**Output of ansible run**:  
[WARNING]:  * Failed to parse /home/vikas_roonwal1/fresh_start/openshift-ansible-contrib/reference-
architecture/gcp/ansible/inventory/gce/hosts/secrets.py with ini plugin: /home/vikas_roonwal1/fresh_start
/openshift-ansible-contrib/reference-architecture/gcp/ansible/inventory/gce/hosts/secrets.py:1: Expected key=value
host variable assignment, got: (ocp-ansible@my-development.iam.gserviceaccount.com,

 [WARNING]: Unable to parse /home/vikas_roonwal1/fresh_start/openshift-ansible-contrib/reference-
architecture/gcp/ansible/inventory/gce/hosts/secrets.py as an inventory source

[DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead. This feature 
will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
ERROR! conflicting action statements: shell, async

The error appears to have been in '/home/vikas_roonwal1/fresh_start/openshift-ansible-contrib/roles/atomic-update/tasks/main.yml': line 51, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Reboot when patched
    ^ here

The error appears to have been in '/home/vikas_roonwal1/fresh_start/openshift-ansible-contrib/roles/atomic-update/tasks/main.yml': line 51, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Reboot when patched
    ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: conflicting action statements: shell, async

The error appears to have been in '/home/vikas_roonwal1/fresh_start/openshift-ansible-contrib/roles/atomic-update/tasks/main.yml': line 51, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Reboot when patched
    ^ here

Thanks

**Comment by pschiffe** [comment]
Please try to use Ansible 2.3. Ansible 2.4 is not fully supported yet.

**Comment by pschiffe** [comment]
Issue in ansible 2.4 preventing our code to run: https://github.com/ansible/ansible/issues/33177

**Comment by pschiffe** [comment]
The GCP ref. arch. code should now work even with ansible 2.4 thanks to https://github.com/openshift/openshift-ansible-contrib/commit/c0f0cccdfbda475906c17fe5e3a00239adddaaea
