### ISSUE TITLE
Ansible run does not disconnect from RHSM when joining to satellite. Invalid credentials when trying to run subscription-manager commands

### ISSUE THREAD

**Issue by esarakaitis** [openshift/openshift-ansible-contrib#848]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one): BUG REPORT

# BUG REPORT INFO

### Environment

- **Cloud provider**:  vmware

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):   Linux 3.10.0-693.2.2.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME=OpenShift
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

- **Version of Ansible** (`ansible --version`):  
ansible 2.3.2.0
  config file = /root/git/openshift-ansible-contrib/reference-architecture/vmware-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
- **Version of Jinja** (`pip freeze | grep -i jinja`):  
Jinja2==2.7.2
- **Version of Shade** (`pip freeze | grep -i shade`):  

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  

**Copy of inventory files and custom variables used (please omit your secrets!)**:  
#Ansible VMware external inventory script settings

[vmware]

# The resolvable hostname or ip address of the vsphere
server=10.0.1.202

# The port for the vsphere API
#port=443

# The username with access to the vsphere API
username=administrator@vcenter.local

# The password for the vsphere API
password=password1

# Specify the number of seconds to use the inventory cache before it is
# considered stale.  If not defined, defaults to 0 seconds.
cache_max_age = 300

# Specify the directory used for storing the inventory cache.  If not defined,
# caching will be disabled.
cache_dir = ~/.cache/ansible

# Max object level refers to the level of recursion the script will delve into
# the objects returned from pyvomi to find serializable facts. The default
# level of 0 is sufficient for most tasks and will be the most performant.
# Beware that the recursion can exceed python's limit (causing traceback),
# cause sluggish script performance and return huge blobs of facts.
# If you do not know what you are doing, leave this set to 1.
#max_object_level=1

# Lower the keynames for facts to make addressing them easier.
#lower_var_keys=True

# Host alias for objects in the inventory. VMWare allows duplicate VM names
# so they can not be considered unique. Use this setting to alter the alias
# returned for the hosts. Any atributes for the guest can be used to build
# this alias. The default combines the config name and the config uuid and
# expects that the ansible_host will be set by the host_pattern.
#alias_pattern={{ config.name + '_' + config.uuid }}
alias_pattern={{ config.name }}

# Host pattern is the value set for ansible_host and ansible_ssh_host, which
# needs to be a hostname or ipaddress the ansible controlhost can reach.
#host_pattern={{ guest.ipaddress }}
host_pattern={{ guest.hostname }}

# Host filters are a comma separated list of jinja patterns to remove
# non-matching hosts from the final result.
# EXAMPLES:
#   host_filters={{ config.guestid == 'rhel7_64Guest' }}
#   host_filters={{ config.cpuhotremoveenabled != False }},{{ runtime.maxmemoryusage >= 512 }}
#   host_filters={{ config.cpuhotremoveenabled != False }},{{ runtime.maxmemoryusage >= 512 }}
# The default is only gueststate of 'running'
host_filters={{ guest.gueststate == "running" }}, {{ config.guestid == 'rhel7_64Guest' }}, {{ config.template != 'templates' }}

# Groupby patterns enable the user to create groups via any possible jinja
# expression. The resulting value will the groupname and the host will be added
# to that group. Be careful to not make expressions that simply return True/False
# because those values will become the literal group name. The patterns can be
# comma delimited to create as many groups as necessary
#groupby_patterns={{ guest.guestid }},{{ 'templates' if config.template else 'guests'}},
groupby_patterns={{ config.annotation }}

**Command used to invoke ansible**:  
ocp-on-vmware.py

**Output of ansible run**:  

STDERR:

Invalid credentials.

failed: [ocpinfra-2] (item=rhel-7-server-satellite-tools-6.2-rpms) => {
    "changed": true, 
    "cmd": "subscription-manager repos --disable=rhel-7-server-satellite-tools-6.2-rpms", 
    "delta": "0:00:09.535731", 
    "end": "2017-11-09 18:39:30.157737", 
    "failed": true, 
    "item": "rhel-7-server-satellite-tools-6.2-rpms", 
    "rc": 70, 
    "start": "2017-11-09 18:39:20.622006"
}

**Anything else do we need to know**:  

# FEATURE REQUEST INFO

An introduction paragraph with "[tl;dr]" info.

## Problem Description

What problem is being solved by the proposed feature?

What are the use cases for End User vs Deployer?

Also describe the target cloud provider.

## Proposed Change

Describe the change you would like to make.

## Implementation

Describe your plan for implementation steps and potential
assignees/contributors.

## Acceptance criteria

Provide a definition of done and acceptance criteria.

## Testing

Describe how to test this, including manual steps, if any.

**Comment by dav1x** [comment]
Howdy @esarakaitis are you still having these issues?
