### ISSUE TITLE
Problems with bastion ssh forwarding on AWS green field deployment

### ISSUE THREAD

**Issue by boeboe** [openshift/openshift-ansible-contrib#852]
Hi all,

I have been trying to run green field deployment of openshift origin on AWS. The phase of setting up all AWS entities works well. However, using the bastion as SSH FW agent fails (read, the AWS setting up is ok, it's the next step of connecting to them and installing OS Origin that fails).

I can connect SSH to the bastion successfully in a manual way like this:

    # ssh bastion
    Last login: Sat Nov 11 00:22:44 2017 from 84.197.224.231
    -bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory

Doing a manual SSH login to bastion.mydomain.whatever fails as well as ose-master01.mydomain.whatever fails:

    channel 0: open failed: administratively prohibited: open failed
    stdio forwarding failed
    ssh_exchange_identification: Connection closed by remote host

As a result, my ansible playbook attempt gets stuck at:

    TASK [host-up : check to see if host is available] *********************************************************************************************************************************************
    fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 799, "failed": true, "msg": "Timeout when waiting for bastion.mydomain.whatever:22"}

Are we sure the following ~/.ssh/config is correct?

    Host *.mydomain.whatever
         ProxyCommand               ssh ec2-user@bastion -W %h:%p
         IdentityFile               /Users/abc/.ssh/aws-key.pem

    Host bastion
         Hostname                   bastion.mydomain.whatever
         user                       ec2-user
         StrictHostKeyChecking      no
         ProxyCommand               none
         CheckHostIP                no
         ForwardAgent               yes
         IdentityFile               /Users/abc/.ssh/aws-key.pem

PS: I am using 3.6 branch of **openshift-ansible** combined with master **openshift-ansible-contrib**.

PPS: Take into account that ssh to bastion without FQDN works but this not:

    ---
    - name: check to see if host is available
      wait_for:
        port: 22
        host: "bastion.{{ public_hosted_zone }}"
        state: started
        delay: "{{ host_up_time }}"
      when: byo_bastion == "no"

**Comment by cooktheryan** [comment]
Are you attempting to connect using a Mac?

**Comment by boeboe** [comment]
@cooktheryan yes I am ;)

**Comment by boeboe** [comment]
I got a bit further now, but still not working as it should.

I added ControlMaster and ControlPersist to my ssh config file:

    Host *.domain.whatever
         ProxyCommand               ssh ec2-user@bastion -W %h:%p
         IdentityFile               /Users/bartvanbos/.ssh/aws-key.pem

    Host bastion
         Hostname                   bastion.domain.whatever
         user                       ec2-user
         StrictHostKeyChecking      no
         ProxyCommand               none
         CheckHostIP                no
         ForwardAgent               yes
         IdentityFile               /Users/bartvanbos/.ssh/aws-key.pem
         ControlMaster              auto
         ControlPersist             10m

I now can login manually using ssh to bastion and protected hosts:

    # alias ssh-boeboe
    ssh-boeboe='ssh -i ~/.ssh/aws-key.pem '

    # ssh-boeboe ec2-user@bastion.domain.whatever
    Last login: Sat Nov 11 11:57:28 2017 from 52.31.152.210
    [ec2-user@ip-10-20-1-96 ~]$ echo "OK"
    OK
    [ec2-user@ip-10-20-1-96 ~]$ exit
    logout
    Connection to bastion.domain.whatever closed.
    Killed by signal 1.

    # ssh-boeboe ec2-user@bastion
    Last login: Sat Nov 11 12:32:40 2017 from 52.31.152.210
    [ec2-user@ip-10-20-1-96 ~]$ echo "OK"
    OK
    [ec2-user@ip-10-20-1-96 ~]$ exit
    logout
    Connection to bastion.domain.whatever closed.

    # ssh-boeboe ec2-user@ose-app-node01.domain.whatever
    Last login: Sat Nov 11 11:56:35 2017 from 10.20.1.96
    [ec2-user@ip-10-20-4-230 ~]$ echo "OK"
    OK
    [ec2-user@ip-10-20-4-230 ~]$ exit
    logout
    Connection to ose-app-node01.domain.whatever closed.
    Killed by signal 1.


The ansible playbook still fails however (I enabled debugging this time):

    TASK [host-up : check to see if host is available] *********************************************************************************************************************************************
    task path: /Users/bartvanbos/Git/openshift/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/roles/host-up/tasks/main.yaml:2
    Using module file /Library/Python/2.7/site-packages/ansible/modules/utilities/logic/wait_for.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bartvanbos
    <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
    The full traceback is:
      File "/var/folders/9l/2vkm0b193_z_mcvd9txvdtdc0000gn/T/ansible_f07j1D/ansible_module_wait_for.py", line 185, in <module>
        import psutil

    fatal: [localhost]: FAILED! => {
        "changed": false,
        "elapsed": 799,
        "failed": true,
        "invocation": {
            "module_args": {
                "active_connection_states": [
                    "ESTABLISHED",
                    "FIN_WAIT1",
                    "FIN_WAIT2",
                    "SYN_RECV",
                    "SYN_SENT",
                    "TIME_WAIT"
                ],
                "connect_timeout": 5,
                "delay": 800,
                "exclude_hosts": null,
                "host": "bastion.domain.whatever",
                "msg": null,
                "path": null,
                "port": 22,
                "search_regex": null,
                "sleep": 1,
                "state": "started",
                "timeout": 300
            }
        },
        "msg": "Timeout when waiting for bastion.domain.whatever:22"
    }

I have started the playbook like this:

    # ./ose-on-aws.py --region=eu-west-1 --keypair=aws-key --public-hosted-zone=domain.whatever \
        --deployment-type=origin --ami=ami-bb9a6bc2 --github-client-secret=******************************** \
        --github-organization=openshift --github-organization=allbits --github-client-id=************** \
        --key-path=/Users/bartvanbos/.ssh/aws-key.pem

**Comment by boeboe** [comment]
Ok, I found the problem, I messed up the delay (which I increased originally to deal with DNS propagation delay):

    ansible localhost -m wait_for -a 'delay=800 sleep=1 timeout=20 state=started port=22 host=bastion.dmain.whatever'

Changing delay back to something smaller (10) made it work fine.
