### ISSUE TITLE
Running provisioning/openstack/provision.yaml task [docker : Install Docker] fails in error

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible-contrib#856]
# BUG REPORT INFO

### Environment

- **Cloud provider**:  OpenStack

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
        "Linux 3.10.0-774.el7.x86_64 x86_64", 
        "NAME=\"Red Hat Enterprise Linux Server\"", 
        "VERSION=\"7.4 (Maipo)\"", 
        "ID=\"rhel\"", 
        "ID_LIKE=\"fedora\"", 
        "VARIANT=\"Server\"", 
        "VARIANT_ID=\"server\"", 
        "VERSION_ID=\"7.4\"", 
        "PRETTY_NAME=\"Red Hat Enterprise Linux Server 7.4 (Maipo)\"", 
        "ANSI_COLOR=\"0;31\"", 
        "CPE_NAME=\"cpe:/o:redhat:enterprise_linux:7.4:GA:server\"", 
        "HOME_URL=\"https://www.redhat.com/\"", 
        "BUG_REPORT_URL=\"https://bugzilla.redhat.com/\"", 
        "", 
        "REDHAT_BUGZILLA_PRODUCT=\"Red Hat Enterprise Linux 7\"", 
        "REDHAT_BUGZILLA_PRODUCT_VERSION=7.4", 
        "REDHAT_SUPPORT_PRODUCT=\"Red Hat Enterprise Linux\"", 
        "REDHAT_SUPPORT_PRODUCT_VERSION=\"7.4\""

- **Version of Ansible** (`ansible --version`):  2.3.2.0

- **Version of Jinja** (`pip freeze | grep -i jinja`):  2.7.2

- **Version of Shade** (`pip freeze | grep -i shade`):  1.24.0

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  22aa303

**Copy of inventory files and custom variables used (please omit your secrets!)**:  Attached all.yml and OSEv3.yml
[openstack_provision_log.txt](https://github.com/openshift/openshift-ansible-contrib/files/1483869/openstack_provision_log.txt)
[variable_files.zip](https://github.com/openshift/openshift-ansible-contrib/files/1483900/variable_files.zip)

**Command used to invoke ansible**:  
`source /home/cloud-user/keystonerc; ansible-playbook -vvv openshift-ansible-contrib/playbooks/provisioning/openstack/provision.yaml 2>&1 > openstack_provision_log.txt`

**Output of ansible run**:  
The provisioner seems to run a yum install of docker, even though docker is already installed. Then we see errors like the mirror's repomd.xml does not match the metalink for epel. 

The following message is repeated a few times:
```
http://mirror.es.its.nyu.edu/epel/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.es.its.nyu.edu/epel/7/x86_64/repodata/repomd.xml: (28, \'Connection timed out after 30001 milliseconds\')
Trying other mirror.
http://csc.mcs.sdsmt.edu/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
Trying other mirror.
http://download-i2.fedoraproject.org/pub/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
Trying other mirror.
http://mirror.utexas.edu/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
Trying other mirror.
``` 
Eventually the install fails with this message:
```
 One of the configured repositories failed (Extra Packages for Enterprise Linux 7 - x86_64),
 and yum doesn\'t have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work \\"fix\\" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=epel ...

     4. Disable the repository permanently, so yum won\'t use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable epel
        or
            subscription-manager repos --disable=epel

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=epel.skip_if_unavailable=true
```

https://gist.github.com/mbruzek/089de67818efb11798ab2ce7510cf89e

**Anything else do we need to know**:  

I have tried running the provisioner manually and do get the same error. What we have found that works is clearing the yum cache. `yum clean all -y`. I created a task before the Docker install manually and the provisioner passed. I don't know how to get this same functionality using the "yum" Ansible module so I used the command module to call "yum clean all -y". 

Please advise on this issue it is blocking the scale-ci work.

**Comment by mbruzek** [comment]
Does anyone know if the `update_cache` option on the yum module would do what is needed here? I could propose that as a potential fix for this problem if that is equivalent functionality.

**Comment by jeremyeder** [comment]
Definitely worth a try.

**Comment by mbruzek** [comment]
> Out of curiousity, why is EPEL enabled?
I don't know. These are the OSP 3.7 images that are generated for testing. Perhaps @chaitanyaenr knows why this repo is disabled.

**Comment by chaitanyaenr** [comment]
we enable the epel repo while building the image for installing additional packages like the ones we have in os-kickstart role of image provisioner.

**Comment by mbruzek** [comment]
> we enable the epel repo while building the image for installing additional packages like the ones we have in os-kickstart role of image provisioner.

I was using the ocp 3.7 gold images, when I got this error. Reading your comment indicates that you enable the repo. Are you disabling the epel repo after you build it? Or why else was the epel repo disabled when I got this error?
