### ISSUE TITLE
Question: "docker-storage-setup" and "is_atomic" var

### ISSUE THREAD

**Issue by gbenhaim** [openshift/openshift-ansible-contrib#865]
Since https://github.com/openshift/openshift-ansible-contrib/pull/839 `openshift.common.is_atomic` variable should be defined in order to invoke `docker-storage-setup` role.

Is this variable should be provided manually by the user? or is there an automated way to provide it?

thanks.

**Comment by cwilkers** [comment]
@gbenhaim , the `openshift.common.is_atomic` variable is defined during the playbook's default pre-tasks when facts are collected on the hosts. The code that sets the variable is in one of the `openshift-ansible` rpms we have as a prerequisite. When that rpm is installed on the host you run your playbook from, it engages during the gather facts stage.

**Comment by gbenhaim** [comment]
@cwilkers Thanks for the quick response.
I'm a bit confused now. How do I incorporate between the `byo` playbook and the `docker-storage-setup` role?

**Comment by cwilkers** [comment]
Are you seeing an error around the `openshift.common.is_atomic` variable?

For typical usage, I can offer the RHV [playbook](https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/rhv-ansible/playbooks/openshift-install.yaml).

**Comment by gbenhaim** [comment]
I'm using `docker-storage-setup` role with a custom playbook. 
The following task was missing from my playbook:
```
- name: Gather facts
  openshift_facts:
    role: common
```

Do you think that it's worth to mention this in the docs of the role?

**Comment by cwilkers** [comment]
@gbenhaim Good catch--I'd missed that the rhsm-timeout role was calling that module. 

I think rather than a documentation fix, it might be better to have a test for whether the `openshift.common.is_atomic` variable is defined, and if not, call that module at the start of the role.

I'll open this up for discussion with the team.
@e-minguez @dav1x @cooktheryan @markllama @pschiffe

**Comment by gbenhaim** [comment]
Seems like `openshift.common.is_atomic` was dropped in the ansible modules of Openshift 3.9.

**Comment by cwilkers** [comment]
@gbenhaim Thanks for the heads-up, the existing test is trivial enough that we can duplicate it in our roles, but it will require some coordination.

**Comment by cwilkers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPIKE Fix deprecation of is_atomic variable in ocp 3.9](https://trello.com/c/GDHkRtJh/1279-spike-fix-deprecation-of-isatomic-variable-in-ocp-39)

**Comment by mmckinst** [comment]
I was running in to this problem trying to install openshift 3.9. I worked around the issue by modifying `/usr/share/ansible/openshift-ansible/roles/openshift_facts/library/openshift_facts.py`. In the function `set_aggregate_facts` I added `facts['common']['is_atomic'] = False`  right after the line that says `facts['common']['all_hostnames'] = list(all_hostnames)` .

**Comment by cwilkers** [comment]
With 3.9, the Docker setup is handled in OpenShift's prerequisites.yml playbook. See 'example/inventory' in the rhv-ansible subdirectory for variables to pass in.
