### ISSUE TITLE
Looks like the password for the admin account is wrong

### ISSUE THREAD

**Issue by zonArt** [openshift/openshift-ansible-contrib#87]
Hi,

I tried to deploy openshift origin using these ansible playbooks with vagrant and for some reason when trying to connect to the web console using admin/admin123 I always had "Invalid username or password". I then changed the htpasswd file with a re-hased value of "admin123" and it worked. What's the actual value of "$2y$11$jJioXC3WgyRq.FVy1vqtfuywDwEZp18d9Kkqb4MgFVzlgCGQNwy36" ?
I guess either the documentation or the Vagrantfile should be updated with something that matches.
Am I alone with this problem ?

**Comment by detiber** [comment]
@zonArt I suspect that the hash is indeed incorrect.

**Comment by zonArt** [comment]
Ok, then I'll open a PR to fix that, thanks

**Comment by detiber** [comment]
Closing since #118 is merged
