### ISSUE TITLE
azure deploy failure to install OSCP

### ISSUE THREAD

**Issue by brasser** [openshift/openshift-ansible-contrib#872]
**BUG REPORT**

When launching on azure security setting are configured incorrectly. Specifically azure.conf file. 

Sample after running deployment via ansible ansibledeployocp

azure.conf
{
   "tenantId": script enters **APID**  ..
   "subscriptionId": script enters **tenantId**
   "aadClientId":  script enters str(activationkey),
  "aadTenantID": script enters **appID**
 "resourceGroup": myresourceGroup
 "location": ****
}

**Comment by e-minguez** [comment]
Do you mind to attach the ansible variables file you've used to the issue? (please remove passwords, etc.)

**Comment by brasser** [comment]
`---
# The parameters detailed description can be found in https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/deploying_red_hat_openshift_container_platform_3_on_microsoft_azure/#provision_the_emphasis_role_strong_openshift_container_platform_emphasis_environment

# id_rsa.pub content
sshkeydata: 

# id_rsa content in base64 without \n characters
# cat ~/.ssh/id_rsa | base64 | tr -d '\n'
sshprivatedata: 

# User that will be created to login via ssh and as OCP cluster-admin
adminusername: "tri"

# Password in plain text
adminpassword: 

# This should be "usernamepassword" or "activationkey"
# If "usernamepassword", then the username and password should be specified
# If "activationkey", then the activation key and organization id should be specified
rhsmusernamepasswordoractivationkey: "activationkey"
# or rhsmusernamepasswordoractivationkey: "activationkey"

# The RHN username where the instances will be registered
rhnusername: 
# or rhnusername: "activationkey" if activation key method has been chosen

# The RHN password where the instances will be registered in plain text
rhnpassword: 
# or rhnpassword: "organizationid" if activation key method has been chosen

# The subscription pool id the instances will use
subscriptionpoolid: 

# The Azure resource name that will be created
resourcegroupname: 

# Active Directory ID needed to be able to create, move and delete persistent volumes
aadclientid: "

# The Active Directory Password to match the AAD Client ID
aadclientsecret: "

# Subdomain for applications in the OpenShift cluster (required by the load balancer, but nip.io will be used). It is just the subdomain, not the full FQDN.
wildcardzone: "triapps"

# Optional (default values are set in playbooks/roles/azure-deploy/default/main.yaml)
# The ARM template that will be deployed
# templatelink: "https://raw.githubusercontent.com/openshift/openshift-ansible-contrib/master/reference-architecture/azure-ansible/azuredeploy.json"
# From 3 to 30 nodes
numberofnodes: 3
# image: "rhel"
mastervmsize: "Standard_DS2_v2"
infranodesize: "Standard_DS2_v2"
nodevmsize: "Standard_DS2_v2"
# Azure location:
location: "canadacentral"
# OpenShift SDN:
openshiftsdn: "redhat/openshift-ovs-multitenant"
# Deploy metrics
metrics: false
# Deploy agregated logging
logging: false
# Deploy agregated logging for ops
opslogging: false 
`

**Comment by brasser** [comment]
[var.txt](https://github.com/openshift/openshift-ansible-contrib/files/1540454/var.txt)

**Comment by brasser** [comment]
Looks like subscriptionID and tenantID are missing from parameters. 

When commandToExecute runs, the init script on the vm is expecting arguments in a specific order. The missing parameters, and the missing arguments in commandToExecute mess up the order. Resulting in a failed deployment .. ?

**Comment by e-minguez** [comment]
Hey @brasser , sorry for the delay, I completely forgot about this x(
The bastion.sh script uses the variable order to create the files, so I think some variable is missing. Do you mind to attach the bastion.sh logs, cmdline, etc.? They should be located either in the user you've created or in /root:

* ~/cmdline.out
* ~/.azuresettings/*

Any logs you see.

Thanks and apologies for the late answer.

**Comment by glennswest** [comment]
Actually I commonly run these 
Are you a employee using employee subs 
There been a issue in employee subs and they need to be resume by ops team 
And u need to check the pool which will change
