### ISSUE TITLE
'dict object' has no attribute 'tag_openshift_role_master'

### ISSUE THREAD

**Issue by demo-crossvale** [openshift/openshift-ansible-contrib#883]
***ISSUE***

### Environment

- **Cloud provider**:  
AWS 
RHEL 7.4 AMI

When trying to create a static inventory, using the create-inventory-file.yaml, I get the following issue:

**Command used to invoke ansible**

ansible-playbook -vvv -i inventory/aws/hosts -e 'stack_name=company-stack-name region=eu-west-1 github_client_secret=XXXXX github_organization=["XXXXX"] github_client_id=XXXX console_port=443 wildcard_zone=apps.company.com public_hosted_zone=company.com' create-inventory-file.yaml

ISSUE:

TASK [inventory-file-creation : command for masters] ******************************************************************************************
task path: /home/ec2-user/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/roles/inventory-file-creation/tasks/main.yaml:13
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found:
hostvars[item]['ec2_tag_KubernetesCluster'] == "{{ stack_name }}"

fatal: [localhost]: FAILED! => {
    "failed": true
}

MSG:

'dict object' has no attribute 'tag_openshift_role_master'

	to retry, use: --limit @/home/ec2-user/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/create-inventory-file.retry

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1

**Comment by cooktheryan** [comment]
What version of Ansible are you using?

**Comment by demo-crossvale** [comment]
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

**Comment by cooktheryan** [comment]
sorry for the delay due to the holidays but please use ansible 2.3.2 or lower for the installation

**Comment by cooktheryan** [comment]
@demo-crossvale can you try to downgrade to ansible-2.3.2.0-2.el7.noarch
