### ISSUE TITLE
ocp-on-gcp.sh fails on node play with 'deployment_type' is undefined

### ISSUE THREAD

**Issue by thomascooper** [openshift/openshift-ansible-contrib#897]
# BUG REPORT INFO

### Environment

- **Cloud provider**:  GCP

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  CentOS Linux 7 (Core) (deploy box, GCP)

- **Version of Ansible** (`ansible --version`):   2.4.2.0

- **Version of Jinja** (`pip freeze | grep -i jinja`):  n/a

- **Version of Shade** (`pip freeze | grep -i shade`):  n/a 

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  8ffc9f0

**Copy of inventory files and custom variables used (please omit your secrets!)**:  
inventory: gce.py
config.yaml:
rhsm_user: 'REDACTED' #correct value
rhsm_password: 'REDACTED' #correct value
rhsm_pool: 'Red Hat OpenShift Enterprise Infrastructure'
rhel_image_path: '~/Downloads/rhel-server-7.4-x86_64-kvm.qcow2'
gcloud_project: 'REDACTED' #correct value
gcloud_zone: 'REDACTED' #correct value

**Command used to invoke ansible**:  
./ocp-on-gcp.sh

**Output of ansible run**:  

https://gist.github.com/thomascooper/774b6f631e501594ebab010c218a01b8

**Anything else do we need to know**:  
Based on some older research went to the openshift-ansible repo cloned during this play and pulled down master instead of 3.7

**Comment by pschiffe** [comment]
Please try to use ansible 2.3 for the time being, 2.4 is broken: https://github.com/ansible/ansible/issues/33177

**Comment by thomascooper** [comment]
Ok I have made it past the place I was having the error. Thanks @pschiffe

**Comment by thomascooper** [comment]
Closing
