### ISSUE TITLE
infra-ansible dns-server role changed, no longer directly compatible

### ISSUE THREAD

**Issue by pearj** [openshift/openshift-ansible-contrib#899]
infra-ansible just made a breaking change to the dns-server role:

See: https://github.com/redhat-cop/infra-ansible/pull/114

Looks like the syntax of the role has changed too:
https://github.com/redhat-cop/infra-ansible/commit/c7af8d7d8aa68a2dfebb88adc649488d521b0723#diff-df708502f6c97ba489d6d378b6fed07f

# BUG REPORT INFO

### Environment

- **Cloud provider**:  openstack

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  fa05d56

**ansible error**:  
```
# ansible-playbook -i inventory openshift-ansible-contrib/playbooks/provisioning/openstack/provision.yaml
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! the role 'infra-ansible/roles/dns-server' was not found in /root/openshift/openshift-ansible-contrib/playbooks/provisioning/openstack/roles:/etc/ansible/roles:/root/openshift/openshift-ansible-contrib/playbooks/provisioning/openstack

The error appears to have been in '/root/openshift/openshift-ansible-contrib/playbooks/provisioning/openstack/post-provision-openstack.yml': line 53, column 7, but maybe elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - role: dns-views
    - role: infra-ansible/roles/dns-server
      ^ here
```

**Comment by pearj** [comment]
I worked around this by editing the galaxy-requirements:
```
[root@18272c80ad12 openshift-ansible-contrib]# git diff
diff --git a/playbooks/provisioning/openstack/galaxy-requirements.yaml b/playbooks/provisioning/openstack/galaxy-requirements.yaml
index 1d745dc..90ac118 100644
--- a/playbooks/provisioning/openstack/galaxy-requirements.yaml
+++ b/playbooks/provisioning/openstack/galaxy-requirements.yaml
@@ -3,8 +3,8 @@

 # From 'infra-ansible'
 - src: https://github.com/redhat-cop/infra-ansible
-  version: master
+  version: v1.0.0
```

**Comment by oybed** [comment]
@pearj yes - please use the [v1.0.0](https://github.com/redhat-cop/infra-ansible/releases/tag/v1.0.0) version (as mentioned in this comment : https://github.com/redhat-cop/infra-ansible/pull/114#issuecomment-354858297).

Also, from what I've been told, the `openshift-ansible-contrib` code is no longer used/maintained as things have moved to `openshift-ansible`. @tomassedovic @bogdando is there a plan to get these users over on to that version?
