### ISSUE TITLE
gcp error - Unknown short_version 3.7

### ISSUE THREAD

**Issue by orgadk** [openshift/openshift-ansible-contrib#907]
# BUG REPORT INFO

### Environment

- **Cloud provider**:  gcp

- **OS details** 
Linux 3.10.0-693.11.6.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"

- **Version of Ansible  ansible 2.4.2.0

- **Version of Jinja  NA

- **Version of Shade NA

- **The openstack-ansible-contrib version (commit)  cdba45a

**Copy of inventory files and custom variables used (please omit your secrets!)**:  

**Command used to invoke ansible**:  ./ocp-on-gcp.sh 

**Output of ansible run**:  

2018-01-22 13:38:07,054 p=14512 u=root |  TASK [openshift_master_facts : Set Default scheduler predicates and priorities] ******************************************
******************************************
2018-01-22 13:38:07,313 p=14512 u=root |  fatal: [ocp-master-1ssg]: FAILED! => {}
MSG:
An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, orig
inal message: Unknown short_version 3.7

**Comment by pschiffe** [comment]
I've just completed whole deployment and didn't get this error (OCP 3.7 on RHEL). Do you some special configuration, or did you change the `ansible/inventory/group_vars/all` file? Do you have `atomic-openshift-utils` rpm package installed, or are you using the installer from github? See `openshift-ansible` directory next to your `openshift-ansible-contrib` dir with this repo. Is it a link or a git repo?

**Comment by orgadk** [comment]
I followed the steps based on the "Deploying and Managing OpenShift Container Platform 3 on Google Cloud Platform" architecture document:

 https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/deploying_and_managing_openshift_container_platform_3_on_google_cloud_platform/

Kindly note that the document refers to OCO 3.6 and you are referring to OCP 3.7 
I didn't change the  ansible/inventory/group_vars/all

rpm -qa | grep atomic-openshift-utils
atomic-openshift-utils-3.6.173.0.83-1.git.0.84c5eff.el7.noarch

It's a link 
lrwxrwxrwx.  1 root root   36 Jan 21 12:48 openshift-ansible -> /usr/share/ansible/openshift-ansible
drwxr-xr-x. 15 root root 4096 Jan 21 11:24 openshift-ansible-contrib

**Comment by pschiffe** [comment]
OK, in that case, please add to your `config.yaml` file the following: `openshift_major_version: 6`. The document wasn't updated for 3.7 yet, but you can deploy OCP 3.7 with updated `atomic-openshift-utils` rpm package for 3.7. In that case the `openshift_major_version` variable has to have the value `7` (currently the default). I'll look into how to handle this better in the code.

**Comment by pschiffe** [comment]
Closing, feel free to reopen if you still see the problem.
