### ISSUE TITLE
ERROR! the role 'ovirt-image-template' was not found

### ISSUE THREAD

**Issue by kfp** [openshift/openshift-ansible-contrib#908]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):

# BUG REPORT INFO

### Environment

- **Cloud provider**:  
RHV 4.1
- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
Linux 3.10.0-693.11.6.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Employee SKU"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

- **Version of Ansible** (`ansible --version`):  
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

- **Version of Jinja** (`pip freeze | grep -i jinja`):  NA

- **Version of Shade** (`pip freeze | grep -i shade`): NA  

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  cdba45a

**Copy of inventory files and custom variables used (please omit your secrets!)**:  NA (error happens before file is parsed)

**Command used to invoke ansible**:  
ansible-playbook -e@ocp-vars.yaml playbooks/ovirt-vm-infra.yaml

**Output of ansible run**:  

ERROR! the role 'ovirt-image-template' was not found in 
/root/git/openshift-ansible-contrib/reference-architecture/rhv-ansible/playbooks/roles:
/root/git/openshift-ansible-contrib/reference-architecture/rhv-ansible/playbooks/roles:
/root/git/openshift-ansible-contrib/roles:
/root/git/ovirt-ansible/roles:
/root/git/openshift-ansible-contrib/reference-architecture/rhv-ansible/playbooks

The error appears to have been in '/root/git/openshift-ansible-contrib/reference-architecture/rhv-ansible/playbooks/ovirt-vm-infra.yaml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ovirt-image-template
      ^ here

**Anything else do we need to know**:  

It appears that https://github.com/ovirt/ovirt-ansible no longer contains the /roles dir. I was able to install the roles via https://ovirt.org/blog/2017/08/ovirt-ansible-roles-how-to-use/ and update the ansible.cfg to point to /usr/share/ansible/roles which worked.

**Comment by cooktheryan** [comment]
@cwilkers

**Comment by cwilkers** [comment]
@kfp Thanks for filing the issue!

I've run into the same trouble in my test environment while working on a different problem. It's on my list to make the updates to documentation and the ansible.cfg

Also of note is that all the role names have been changed to use the 'oVirt.rolename' format.

**Comment by cwilkers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Update RHV RA to reflect changes in ovirt-ansible roles [epic-rhv]](https://trello.com/c/ZvbjGoq7/1202-3-update-rhv-ra-to-reflect-changes-in-ovirt-ansible-roles-epic-rhv)

**Comment by cwilkers** [comment]
Hi @kfp,

I've merged changes to:
1. Use the new role names
2. Adjust documentation to specify using Ansible Galaxy to install roles rather than pulling them from GH
3. Adjust the deploy-host role to use an Ansible Galaxy install rather than a GitHub clone.
