### ISSUE TITLE
GCP: deployment manager should be enabled (documentation)

### ISSUE THREAD

**Issue by rgordill** [openshift/openshift-ansible-contrib#919]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):

# BUG REPORT INFO

### Environment

- **Cloud provider**:  GCP

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  rhel74

- **Version of Ansible** (`ansible --version`):  2.4.2

- **Version of Jinja** (`pip freeze | grep -i jinja`):  2.7.2-2

- **Version of Shade** (`pip freeze | grep -i shade`):  N/A

- **The openshift-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  aae4f53

**Copy of inventory files and custom variables used (please omit your secrets!)**:  

**Command used to invoke ansible**:  

./ocp-on-gcp.sh --infra

**Output of ansible run**:  

TASK [deployment-create : check if deployment ocp-network exists] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["gcloud", "--project", "ocp-test-drive-iberia", "deployment-manager", "deployments", "describe", "ocp-network", "--format", "yaml(deployment.operation)"], "delta": "0:00:00.566950", "end": "2018-01-29 23:53:52.904966", "msg": "non-zero return code", "rc": 1, "start": "2018-01-29 23:53:52.338016", "stderr": "API [deploymentmanager.googleapis.com] not enabled on project \n[912620037711]. Would you like to enable and retry?  (y/N)?  \nERROR: (gcloud.deployment-manager.deployments.describe) HTTPError 403: Access Not Configured. Google Cloud Deployment Manager API has not been used in project 912620037711 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/deploymentmanager.googleapis.com/overview?project=912620037711 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "stderr_lines": ["API [deploymentmanager.googleapis.com] not enabled on project ", "[912620037711]. Would you like to enable and retry?  (y/N)?  ", "ERROR: (gcloud.deployment-manager.deployments.describe) HTTPError 403: Access Not Configured. Google Cloud Deployment Manager API has not been used in project 912620037711 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/deploymentmanager.googleapis.com/overview?project=912620037711 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."], "stdout": "", "stdout_lines": []}

**Comment by pschiffe** [comment]
This applies also to the Google DNS. I guess it depends on the project what is enabled and what not by default.

**Comment by gordillo-ramon-redhat** [comment]
That's the reason I think it should be added in the documentation.
