### ISSUE TITLE
'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, orig inal message: Unknown short_version 3.7

### ISSUE THREAD

**Issue by hareeshrao4839** [openshift/openshift-ansible-contrib#928]
i trying to install openshift-container platform V3.6 but i am getting Error.

BUG REPORT INFO
Environment
Cloud provider: gcp
OS details RHEL-7.4
Ansible ansible 2.4.2.0

##i am changed parameters value in group_var/all
**The openshift-ansible-contrib/reference-architecture/gcp/ansible/inventory/group_vars/all
openshift_major_version: 6

Command used to invoke ansible: ./ocp-on-gcp.sh

Output of ansible run:

An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predicates'. Error was a <class 'ansible.errors.AnsibleError'>, orig
inal message: Unknown short_version 3.7

please help me out solve it out ( my requirement is V3.6)

**Comment by pschiffe** [comment]
@hareeshrao4839 what version of `atomic-openshift-utils` rpm package do you have installer on your deployer machine?

**Comment by hareeshrao4839** [comment]
atomic-openshift-utils-3.6.128-1.el7.noarch.rpm

**Comment by pschiffe** [comment]
Next to the `openshift-ansible-contrib` git directory, there should be a link `openshift-ansible -> /usr/share/ansible/openshift-ansible`, is that correct?
I've just tried to deploy 3.6 and it worked fine. The error you see usually happens when there is a mismatch between installer version and `openshift_major_version` variable, but in your case, both seems to be correct, pointing to the v3.6. Can also please double check the `openshift_major_version` variable if it's still set to the value of 6, or if it's not overridden elsewhere (like in config.yaml)?

**Comment by hareeshrao4839** [comment]
---
# Variables shared by multiple playbooks and roles, which are not interesting
# to user
openshift_major_version: 6
openshift_ansible_branch: release-3.{{ openshift_major_version }}
openshift_required_repos:
- rhel-7-server-rpms
- rhel-7-server-extras-rpms
- rhel-7-server-ose-3.{{ openshift_major_version }}-rpms
- rhel-7-fast-datapath-rpms
gcloud_region: '{{ gcloud_zone[:-2] }}'
gcs_registry_bucket: '{{ gcloud_project }}-{{ prefix }}-registry-bucket'
deployment_type: '{{ openshift_deployment_type }}'
# This is either a symlink to /usr/share/ansible/openshift-ansible or
# git repo of openshift ansible installer from github
openshift_ansible_installer_dir: '{{ playbook_dir }}/../../../../../openshift-ansible'
ssh_config_file: '~/.ssh/config'
rhel_image: '{{ rhel_image_path | basename | regex_replace("^(.*)\.qcow2$", "\1") }}'
rhel_image_gce: '{{ rhel_image | replace(".", "-") | replace("_", "-") | lower }}'
gold_image: '{{ rhel_image_gce + "-gold" if openshift_deployment_type == "openshift-enterprise" else "centos-7-ocp-
gold-image" }}'
gold_image_family: '{{ "rhel-guest-gold" if openshift_deployment_type == "openshift-enterprise" else "centos-7-ocp-
gold" }}'
console_port: 443
validate_etcd_short_hostname: true
service_account: 'ocp-ansible'
service_account_id: '{{ service_account }}@{{ gcloud_project }}.iam.gserviceaccount.com'
service_account_name: 'OCP Ansible'
credentials_file: '{{ inventory_dir }}/gce/hosts/project.json'
~                                                                 
TASK [openshift_master_facts : Set Default scheduler predicates and priorities] ***********************************
task path: /opt/openshift-ansible/roles/openshift_master_facts/tasks/main.yml:113
fatal: [po-master-skv5]: FAILED! => {
    "failed": true, 
    "msg": "An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_predica
tes'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.7"
}
PLAY RECAP ********************************************************************************************************
localhost                  : ok=49   changed=22   unreachable=0    failed=0   
po-bastion                 : ok=5    changed=0    unreachable=0    failed=0   
po-infra-node-2q1k         : ok=116  changed=17   unreachable=0    failed=0   
po-master-skv5             : ok=241  changed=54   unreachable=0    failed=1   
po-node-719f               : ok=116  changed=17   unreachable=0    failed=0   
po-node-gvwt               : ok=116  changed=17   unreachable=0    failed=0   
po-tmp-instance            : ok=12   changed=8    unreachable=0    failed=0   
Failure summary:
  1. Hosts:    po-master-skv5
     Play:     Configure masters
     Task:     Set Default scheduler predicates and priorities
     Message:  An unhandled exception occurred while running the lookup plugin 'openshift_master_facts_default_pred
icates'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unknown short_version 3.7
