### ISSUE TITLE
failed: [10.128.0.8] (item=/usr/share/openshift/examples/image-streams/image-streams-rhel7.json) 

### ISSUE THREAD

**Issue by hareeshrao4839** [openshift/openshift-ansible-contrib#929]
RHEL7.4--4 machines

INVENTORY:
[OSEv3:children]
nodes
masters
nfs
etcd

[OSEv3:vars]
openshift_master_default_subdomain=apps.openshiftv36.online
ansible_ssh_user=deep_dutta
ansible_become=yes
openshift_override_hostname_check=true
openshift_master_cluster_method=native
openshift_master_cluster_vip=10.128.0.8
openshift_master_cluster_public_vip=35.225.198.90
openshift_master_public_api_url=https://master.openshiftv36.online:8443
openshift_master_public_console_url=https://master.openshiftv36.online:8443/console
deployment_type=openshift-enterprise
openshift_disable_check=memory_availability,disk_availability,docker_storage
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
openshift_clock_enabled=true
openshift_docker_insecure_registries=172.30.0.0/16

[nodes]
10.128.0.8     openshift_public_ip=10.128.0.8 openshift_ip=10.128.0.8   openshift_schedulable=False
10.128.0.9     openshift_public_ip=10.128.0.9 openshift_ip=10.128.0.9   openshift_schedulable=False openshift_node_labels="{'region': 'infra'}"
10.128.0.10    openshift_public_ip=10.128.0.10 openshift_ip=10.128.0.10    openshift_schedulable=True
10.128.0.11    openshift_public_ip=10.128.0.11 openshift_ip=10.128.0.11   openshift_schedulable=True

[masters]
10.128.0.8  openshift_public_ip=10.128.0.8 openshift_ip=10.128.0.8

[nfs]
10.128.0.8  openshift_public_ip=10.128.0.8 openshift_ip=10.128.0.8

[etcd]
10.128.0.8  openshift_public_ip=10.128.0.8 openshift_ip=10.128.0.8

-----ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml -b

ERROR
failed: [10.128.0.8] (item=/usr/share/openshift/examples/image-streams/image-streams-rhel7.json) => {
    "changed": false, 
    "cmd": [
        "oc", 
        "create", 
        "--config=/etc/origin/master/admin.kubeconfig", 
        "-n", 
        "openshift", 
        "-f", 
        "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json"
    ], 
    "delta": "0:00:00.207471", 
    "end": "2018-02-08 07:36:27.971376", 
    "failed_when_result": true, 
    "item": "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json", 
    "rc": 1, 
    "start": "2018-02-08 07:36:27.763905"
}

STDERR:

The connection to the server os-cp-master1.10.128.0.8.xip.io:8443 was refused - did you specify the right host or port?

MSG:

non-zero return code

failed: [10.128.0.8] (item=/usr/share/openshift/examples/image-streams/dotnet_imagestreams.json) => {
    "changed": false, 
    "cmd": [
        "oc", 
        "create", 
        "--config=/etc/origin/master/admin.kubeconfig", 
        "-n", 
        "openshift", 
        "-f", 
        "/usr/share/openshift/examples/image-streams/dotnet_imagestreams.json"
    ], 
    "delta": "0:00:00.483498", 
    "end": "2018-02-08 07:36:29.390841", 
    "failed_when_result": true, 
    "item": "/usr/share/openshift/examples/image-streams/dotnet_imagestreams.json", 
    "rc": 1, 
    "start": "2018-02-08 07:36:28.907343"
}

STDERR:

The connection to the server 10.128.0.8:8443 was refused - did you specify the right host or port?

MSG:

non-zero return code

**Comment by pschiffe** [comment]
Is this GCP as well? If yes, console port 8443 won't work, you need to use 443 (in `openshift_master_public_api_url` and `openshift_master_public_console_url` vars).

**Comment by hareeshrao4839** [comment]
thanks its woking, can u share me sample inventory file

**Comment by pschiffe** [comment]
For the installation, no inventory file is needed. This code utilizes GCP dynamic inventory. Configuration is done only in `config.yaml`. After the deployment, if you need static inventory file, you can generate it with `./ocp-on-gcp.sh --static-inventory`
