### ISSUE TITLE
Vagrantfile openshift-ansible playbook does not exist on guest

### ISSUE THREAD

**Issue by nickkeyzer** [openshift/openshift-ansible-contrib#931]
# BUG REPORT INFO

### Environment

- **OS details** :  CentOS Linux release 7.4.1708

- **Version of Ansible** :  ansible 2.4.0.0

- **Version of Jinja** :  Jinja2==2.9.6

- **The openshift-ansible-contrib version (commit)** :  48644bd

**Copy of inventory files and custom variables used (please omit your secrets!)**:  n/a

**Command used to invoke ansible**:  `vagrant up`

**Output of ansible run**:  
```
==> admin1: Running provisioner: ansible_local...
`playbook` does not exist on the guest: /home/vagrant/openshift-ansible/playbooks/byo/config.yml
```

**Anything else do we need to know**:  

There's an issue with the Vagrant contrib where it blindly pulls the master branch of the `openshift-ansible` project. Because of this I'm getting the error listed above. The issue here is that `openshift-ansible/playbooks/byo/config.yml` no longer exists in the master branch of the `openshift-ansible` project.

In order to fix this, we need to correct the `Vagrantfile` at line _150_ (https://github.com/openshift/openshift-ansible-contrib/blob/master/vagrant/Vagrantfile#L150)

**_From_**:
```
config_playbook = "/home/vagrant/openshift-ansible/playbooks/deploy_cluster.yml"
```
**_To_**:
```
config_playbook = "/home/vagrant/openshift-ansible/playbooks/deploy_cluster.yml"
```

A longer term fix could include a mechanism to specify the desired release of the `openshift-ansible` project. We can do this through interpolation while still leaving the default behavior of pulling the master branch if that's preferred. 

I can put together a fix for this if desired.

**Comment by cooktheryan** [comment]
If you could put together a PR that would be great

**Comment by dry4ng** [comment]
In addition to `deploy_cluster.yml` you also need `prerequisites.yml` from the same dir. Otherwise deployment will fail due to missed dependencies.
