### ISSUE TITLE
Is the storage_nodes setting used anywhere?

### ISSUE THREAD

**Issue by everett-toews** [openshift/openshift-ansible-contrib#935]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one): **BUG REPORT**

I see the setting `storage_nodes` defined in a [number of places](https://github.com/openshift/openshift-ansible-contrib/search?q=storage_nodes&type=Code&utf8=%E2%9C%93). However, AFAICT, it isn't actually used anywhere.

Am I completely missing something or can it be deleted?

**Comment by dav1x** [comment]
It's heavily used in:
https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/vmware-ansible/add-node.py

Its used to increment storage node count (gluster CNS and CRS) for ipaddr assignment in the provisioning inventory. 

https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/vmware-ansible/add-node.py#L294-L322

**Comment by everett-toews** [comment]
Ah, I see it now. Thanks for the clarification.

And thanks for the VMware reference architecture! I plan to make use of it in the near future.

**Comment by everett-toews** [comment]
@dav1x Actually, if you don't mind one more question related to `storage_nodes`...

It looks to me like `storage_nodes` is only used if you were to enable CNS or CRS. So if `byo_nfs=False` then NFS would just use the disk(s) allocated to the created VM and _not_ anything created from setting `storage_nodes`.

Is that correct?

**Comment by dav1x** [comment]
Hey @everett-toews yes. That is correct. If you byo_nfs=false a VM will be created and the backend datastore will be the source of the VMDK.

**Comment by everett-toews** [comment]
Thanks!
