### ISSUE TITLE
Error: TASK [instance-groups : Add loadbalancer instances to allnodes]

### ISSUE THREAD

**Issue by hareeshrao4839** [openshift/openshift-ansible-contrib#938]
Redhat container platform 3.6:

TASK [instance-groups : Add NFS instances to allnodes] *****************************************************************************************************************************************************
task path: /root/git/openshift-ansible-contrib/reference-architecture/vmware-ansible/playbooks/roles/instance-groups/tasks/main.yaml:64
fatal: [localhost]: FAILED! => {}

MSG:

'dict object' has no attribute u'5noqntg7k7zlhi19jl62-infra-nfs'

...ignoring
Read vars_file 'vars/main.yaml'

TASK [instance-groups : Add loadbalancer instances to allnodes] ********************************************************************************************************************************************
task path: /root/git/openshift-ansible-contrib/reference-architecture/vmware-ansible/playbooks/roles/instance-groups/tasks/main.yaml:70
fatal: [localhost]: FAILED! => {}

MSG:

'dict object' has no attribute u'5noqntg7k7zlhi19jl62-loadbalancer'

...ignoring
Read vars_file 'vars/main.yaml'
fatal: [pocmaster-0]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

SSH Error: data could not be sent to remote host "pocmaster-0". Make sure this host can be reached over ssh

fatal: [pocinfra-0]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

SSH Error: data could not be sent to remote host "pocinfra-0". Make sure this host can be reached over ssh

fatal: [pocapp-1]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

SSH Error: data could not be sent to remote host "pocapp-1". Make sure this host can be reached over ssh

fatal: [pocapp-2]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

SSH Error: data could not be sent to remote host "pocapp-2". Make sure this host can be reached over ssh

fatal: [pocapp-0]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

SSH Error: data could not be sent to remote host "pocapp-0". Make sure this host can be reached over ssh

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=7    changed=4    unreachable=0    failed=0
pocapp-0                   : ok=0    changed=0    unreachable=1    failed=0
pocapp-1                   : ok=0    changed=0    unreachable=1    failed=0
pocapp-2                   : ok=0    changed=0    unreachable=1    failed=0
pocinfra-0                 : ok=0    changed=0    unreachable=1    failed=0
pocmaster-0                : ok=0    changed=0    unreachable=1    failed=0

**Comment by dav1x** [comment]
Howdy @hareeshrao4839 ! 

Can you run the inventory and show me the output?
