### ISSUE TITLE
The error was: ImportError: No module named ipaddress

### ISSUE THREAD

**Issue by james-knott** [openshift/openshift-ansible-contrib#941]
Local Workstation RedHat 7.4
Ansible version 2.4

./ose-on-aws.py --keypair= --public-hosted-zone= --deployment-type=origin --ami=ami-6d1c2007 --github-client-secret= --github-organization= --github-client-id=

TASK [non-atomic-docker-storage-setup : Gather facts] ********************************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named ipaddress
fatal: [ose-app-node02]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tJ6HB4/ansible_module_openshift_facts.py\", line 19, in <module>\n    import ipaddress\nImportError: No module named ipaddress\n", "modul

**Comment by cooktheryan** [comment]
@james-knott which branch of openshift-ansible are you using?

**Comment by dav1x** [comment]
@james-knott try running the deploy-host with the provider of aws:

ansible-playbook playbooks/deploy-host.yaml -e provider=aws

This should properly prepare the required packages.

**Comment by cooktheryan** [comment]
@dav1x i believe the python-ipaddress needs patched into all providers as a prereq

**Comment by james-knott** [comment]
@dav1x Thanks for the help. I already added a role for epel, and pip to install the missing requirements.

**Comment by tdudgeon** [comment]
I think I hit this problem running the openshift-ansible installer from the release-3.9 branch. This issue is marked as closed, but its not clear how to fix the problem.

**Comment by dav1x** [comment]
@tdudgeon Are you still having an issue?

**Comment by tdudgeon** [comment]
@dav1x 
Can't tell at present. Can't get Origin 3.9 to install at  present as I'm not clear what params to try. I've tried this (and a few variations) but can't get a working combination:
```
openshift_deployment_type=origin
openshift_release=v3.9
openshift_image_tag=v3.9.0
openshift_pkg_version=-3.9.0
```
Not sure whether the fact generation comes before this. If so then maybe its fixed.

**Comment by dav1x** [comment]
Hey @tdudgeon 

Try this combination:

```
openshift_release="3.9"
deployment_type=openshift-enterprise
```
The release and image version should be set via the release.

**Comment by mikecali** [comment]
also having an issue on OCP 3.7.
ansible 2.4.2.0
RHEL 7.4
openshift-ansible-playbooks-3.7.42

" [non-atomic-docker-storage-setup : Gather facts] *************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named ipaddress
fatal: [ose-master03.makeaangayon.com]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_JeaHJg/ansible_module_openshift_facts.py\", line 19, in <module>\n    import ipaddress\nImportError: No module named ipaddress\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named ipaddress
fatal: [ose-master01.makeaangayon.com]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gJNDfa/ansible_module_openshift_facts.py\", line 19, in <module>\n    import ipaddress\nImportError: No module named ipaddress\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named ipaddress"
=====================================

Istack_name: openshift-infra
	ami: ami-0b1e356e
	region: us-east-2
	master_instance_type: m4.xlarge
	node_instance_type: m4.xlarge
	app_instance_type: t2.large
	app_node_count: 3
	keypair: aws_ocp_contrib
	create_key: yes
	key_path: /root/.ssh/aws_ocp_contrib.pub
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: openshift-enterprise
	openshift_sdn: redhat/openshift-ovs-multitenant
	public_hosted_zone: makeaangayon.com
	app_dns_prefix: apps
	apps_dns: apps.makeaangayon.com
	containerized: False
	s3_bucket_name: openshift-infra-ocp-registry-makeaangayon
	s3_username: openshift-infra-s3-openshift-user

**Comment by cooktheryan** [comment]
@mikecali you will need to install python-ipaddress as one of the first steps in the deployment either in its own pre_task play or in cloud-init

**Comment by mikecali** [comment]
@cooktheryan, that fix the problem. Thanks!
So to be clear for future reference, python-ipaddress needs to be installed in all nodes. What I did is I created a simple role and add it on playbooks/openshift-install.yaml

```
- hosts: nodes
  gather_facts: yes
  become: yes
  vars_files:
  - vars/main.yaml
  roles:
  **- adding-python-ipaddress**
  - non-atomic-docker-storage-setup
  - openshift-versions
```
