### ISSUE TITLE
ocp deployment failure on gcp: failed API check during the deployement.

### ISSUE THREAD

**Issue by jihed** [openshift/openshift-ansible-contrib#951]
# BUG REPORT INFO

### Environment

- **Cloud provider**:  GCP

- **OS details** :  
Linux 3.10.0-693.17.1.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:beta:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5 Beta"

- **Version of Ansible**:  
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/joe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Dec  8 2017, 16:39:59) [GCC 4.8.5 20150623 (Red Hat 4.8.5-25)]

**Command used to invoke ansible**:  ocp-on-gce

**Output of ansible run**:  

fatal: [ocp-a1-master-ktcd]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "--silent", "--tlsv1.2", "--cacert", "/etc/origin/master/ca-bundle.crt", "https://internal.master.sbox.jlab.ovh/healthz/ready"], "delta": "0:00:00.019442", "end": "2018-02-26 09:33:23.423800", "msg": "non-zero return code", "rc": 6, "start": "2018-02-26 09:33:23.404358", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

> 

**Anything else do we need to know**:  
I am using a rhel 7.4 for the infrastructure.
During the installtion, the new records for the master api (internal) were not resolved. So, the curl check  for the api is failed.

I am deploying OCP 3.7 (3.7.23)
I see the records for the Cloud-DNS were created but, can't be resolved.

> 
nslookup internal.master.sbox.jlab.ovh
Server:		10.200.0.245
Address:	10.200.0.245#53

** server can't find internal.master.sbox.jlab.ovh: NXDOMAIN

nslookup jlab.ovh
Server:		10.200.0.245
Address:	10.200.0.245#53

Non-authoritative answer:
Name:	jlab.ovh
Address: 213.186.33.5

any thoughts about this ?
Regards,

**Comment by jihed** [comment]
I think this is related to the dns propagation between the third party and google dns domains.
I don't have the issue anymore.

**Comment by pschiffe** [comment]
Closing per previous comment.
