### ISSUE TITLE
Upgrade Existing AWS 3.6 cluster to 3.7

### ISSUE THREAD

**Issue by daveconde** [openshift/openshift-ansible-contrib#956]
Is is possible and if so are there any docs available to upgrade an existing 3.6 install to 3.7?
If this is possible does it also create the auto scaling groups that are now in openshift-ansible?
Thanks

**Comment by vrutkovs** [comment]
> Is is possible and if so are there any docs available to upgrade an existing 3.6 install to 3.7?

https://docs.openshift.com/container-platform/3.6/install_config/upgrading/index.html

> If this is possible does it also create the auto scaling groups that are now in openshift-ansible?

Not sure about that, maybe @sdodson or @kwoodson would know?

**Comment by sdodson** [comment]
Yes, you can follow the docs in https://github.com/openshift/openshift-ansible/tree/master/playbooks/aws which describe how to deploy a scale group. We're working on automated workflows to support upgrades now.

This is not yet supported for OCP customers though.

**Comment by daveconde** [comment]
I have provisioned via the reference architecture scripts, will the upgrade mentioned above work with the reference architecture scripts to upgrade or should we be using openshift-ansible directly?

**Comment by cooktheryan** [comment]
@daveconde so the instances themselves will not be re-provisioned with ASGs. The deployment of the aws code from this repo creates a static inventory which you can then use https://docs.openshift.com/container-platform/3.7/upgrading/automated_upgrades.html#preparing-for-an-automated-upgrade and the manual upgrade process

**Comment by daveconde** [comment]
Will it create a ASG for new nodes to be provisioned in to as part of the upgrade?

**Comment by kwoodson** [comment]
@daveconde,

The upgrade playbook for 3.9 will create scale groups based upon an AMI that you would be required to build.

**Comment by daveconde** [comment]
Thanks
