### ISSUE TITLE
Instruction should contain ntp installation and setup

### ISSUE THREAD

**Issue by tahonen** [openshift/openshift-ansible-contrib#96]
When doing installation from vagrant image etc. time might not be synced correctly. This may cause python errors that are really hard to figure out.

**Comment by detiber** [comment]
@tahonen we should be enabling either ntpd or chronyd at install time, did you hit an issue with this?

**Comment by tahonen** [comment]
Installed hosts are running fine and in correct time. I had time issue with vm that I used to install. I used  vagrant and clock was no in sync after host laptop when to sleep. When clock was no sync I got very weird errors from python code accessing AWS. Installed aws cli and noted ant SSL was failing due time problems.

**Comment by dwojciec** [comment]
@tahonen on my vagrant project here: https://github.com/dwojciec/ocp-on-aws  I setup ntp. I include Vagrant-timezone and I setup ntp inside setup.sh script. By doing that I'm able to rerun the provisonning later when I want.
