### ISSUE TITLE
app_instance_type is not used

### ISSUE THREAD

**Issue by jbrannst** [openshift/openshift-ansible-contrib#97]
Hello,
I intended to start up a cluster with small defaults but higher capacity app nodes, and used the app_instance_type parameter. But the result is I have all nodes the same size, t2.medium. There were no errors reported.

$  ./ose-on-aws.py --region=eu-west-1 --rhsm-user=jbrannst --public-hosted-zone=ocp.rocks --keypair=OpenShift-Key --rhsm-pool="Employee SKU" --app-instance-type=m4.xlarge  --ami=ami-8b8c57f8 --s3-bucket-name=ocp-infra-registry-123456 --s3-username=ec2-user
RHSM password?: 
Configured values:
	stack_name: openshift-infra
	ami: ami-8b8c57f8
	region: eu-west-1
	master_instance_type: m4.large
	node_instance_type: t2.medium
	app_instance_type: m4.xlarge
	bastion_instance_type: t2.micro
	keypair: OpenShift-Key
	create_key: no
	key_path: /dev/null
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: openshift-enterprise
	public_hosted_zone: ocp.rocks
	app_dns_prefix: apps
	apps_dns: apps.ocp.rocks
	rhsm_user: jbrannst
	rhsm_password: *******
	rhsm_pool: Employee SKU
	containerized: False
	s3_bucket_name: ocp-infra-registry-123456
	s3_username: ec2-user

**Comment by cooktheryan** [comment]
Resolved with above. Good find
