### ISSUE TITLE
ose-on-aws.py fails at CHECK [memory_availability : ose-infra-node02.*] with  check "package_version"

### ISSUE THREAD

**Issue by naumannt** [openshift/openshift-ansible-contrib#971]
**BUG REPORT**

OpenShift-deployment with minimal changes using ose-on-aws.py fails at 

CHECK [memory_availability : ose-infra-node02.*] with 
check "package_version":
               Some required package(s) are available at a version
               that is higher than requested
                 docker-1.13.1
               This will prevent installing the version you requested.
               Please check your enabled repositories or adjust openshift_release.

Did not find any information on how to fix this.
Do I understand right that because there is a newer Docker version available, the script does not allow the installation to proceed? Why is that? Where do I need to adjust the script/an inventory file to fix this?

# BUG REPORT INFO

### Environment

- **Cloud provider**:  AWS

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  none yet/ OS 3.7 expected 

- **Version of Ansible** (`ansible --version`):  2.4.3.0

- **Version of Jinja** (`pip freeze | grep -i jinja`):  Jinja2==2.10

- **Version of Shade** (`pip freeze | grep -i shade`):  no output

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  4e9331158722f41020861fa1ccb58934748b81f5 (e-minguez authored and cooktheryan committed a day ago)

**Copy of inventory files and custom variables used (please omit your secrets!)**:  Likely irrelevant, provided on request

**Command used to invoke ansible**:  python ose-on-aws.py --keypair=* --stack-name=* --public-hosted-zone=* --rhsm-user=* --rhsm-password=* --rhsm-pool="Red Hat OpenShift, Standard Support (10 Cores, NFR, Partner Only)"  --s3-bucket-name=* --ami=* --region=eu-central-1

**Output of ansible run**:  

https://gist.github.com/naumannt/a9041601f2bca74520d6e8294401467b

**Comment by naumannt** [comment]
Issue also reported as https://github.com/openshift/openshift-ansible/issues/7518. Probably a better fit because the problem regards installation of OpenShift after infrastructure provisioning is finished.

**Comment by cooktheryan** [comment]
You most likely need to bump the instance size when defining the node types
when running ose-on-aws

We didn't do a paper based off of 3.7 so there is no reflecting code updates
