### ISSUE TITLE
ARM templates fail pre-flight checks if resource group has uppercase characters.

### ISSUE THREAD

**Issue by matt-watson90** [openshift/openshift-ansible-contrib#980]
# BUG REPORT INFO

### Environment

- **Cloud provider**: Azure  

**Anything else do we need to know**:  

If building using the azure-ansible reference architecture: https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/azure-ansible and the target resource group name uppercase letters then the pre-flight checks will fail.  This is because the ARM template concatenates the resource group name to storage account names and storage account names only permit lowercase.

Our solution was to update the scripts to automatically lowercase the resource group name when creating storage accounts, for example: `"infranodeStorageName" [concat('sainf',toLower(resourcegroup().name))]",`.

If this behavior is desirable as a default then I can create a pull request.

**Comment by cooktheryan** [comment]
Would it be possible to create the PR. It would be greatly appreciated

**Comment by matt-watson90** [comment]
No worries. I should get the chance today / tomorrow.
