### ISSUE TITLE
Ansible parser error

### ISSUE THREAD

**Issue by jaywryan** [openshift/openshift-ansible-contrib#997]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):

# BUG REPORT INFO

### Environment

- **Cloud provider**:  AWS

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
Linux 3.10.0-123.8.1.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.0 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.0"
PRETTY_NAME="OpenShift Enterprise"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.0:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.0

- **Version of Ansible** (`ansible --version`):  
ansible 2.3.3.0
  config file = /home/ec2-user/git/openshift-ansible-contrib/reference-architecture/aws-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Feb 11 2014, 07:46:25) [GCC 4.8.2 20140120 (Red Hat 4.8.2-13)]

- **Version of Jinja** (`pip freeze | grep -i jinja`):  
Jinja2==2.7.2

- **Version of Shade** (`pip freeze | grep -i shade`):  
N/A
- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  
N/A

**Copy of inventory files and custom variables used (please omit your secrets!)**:  

**Command used to invoke ansible**:  
./ose-on-aws.py \
    --stack-name=$AWS_STACK_NAME \
    --region=$AWS_REGION \
    --ami=$AMI_ID \
    --keypair=$AWS_KEYPAIR_NAME \
    --rhsm-user=$RHN_USER \
    --rhsm-password=$RHN_PASSWORD \
    --public-hosted-zone=$PUBLIC_HOSTED_ZONE \
    --rhsm-pool=$RHN_POOL_ID \
    --github-client-secret=$GITHUB_CLIENT_SECRET \
    --github-organization=$GITHUB_ORGANIZATION \
    --github-client-id=$GITHUB_CLIENT_ID \
    --containerized=yes \
    --s3-bucket-name=$AWS_S3_BUCKET \
    --s3-username=$AWS_S3_USERNAME \
    --openshift-metrics-deploy=true \
    --openshift-logging-deploy=true \
    --openshift-metrics-storage-volume-size=10 \
    --openshift-logging-storage-volume-size=10 \
    -vvv

**Output of ansible run**:  

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/ec2-user/git/openshift-ansible-contrib/roles/prerequisites/tasks/main.yaml': line 26, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Determine if firewalld is installed
    ^ here

The error appears to have been in '/home/ec2-user/git/openshift-ansible-contrib/roles/prerequisites/tasks/main.yaml': line 26, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Determine if firewalld is installed
    ^ here

**Bug**
It appears that there is some parsing error.  Perhaps I'm not using the correct version of ansible?  I have tried 2.3 and 2.4.  I have not modifed the prerequisites role

**Comment by marthenlt** [comment]
Had this issue as well for GCP.
We are trying to to run ./ocp-on-gcp.sh --soft-redeploy

`
2018-05-17 09:06:44,115 p=18604 u=myname |  [DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead. This feature will be removed in version 2.8. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
2018-05-17 09:06:44,393 p=18604 u=myname |  ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/myname/openshift-ansible-contrib/roles/prerequisites/tasks/main.yaml': line 26, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: Determine if firewalld is installed
    ^ here


The error appears to have been in '/home/myname/openshift-ansible-contrib/roles/prerequisites/tasks/main.yaml': line 26, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: Determine if firewalld is installed
    ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/myname/openshift-ansible-contrib/roles/prerequisites/tasks/main.yaml': line 26, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Determine if firewalld is installed
    ^ here
`

Any thing that we missed out?

**Comment by zvikaga** [comment]
I'm facing the exact same issue when changing to openshift_major_version=9

**Comment by e-minguez** [comment]
I'm afraid this is not going to be updated for new releases. There is a deprecation notice:

NOTE: This repository contains deprecated scripts and ansible playbooks. Refer to the official documentation [Deploying and Managing OpenShift 3.9 on Google Cloud Platform](https://access.redhat.com/documentation/en-us/reference_architectures/2018/html-single/deploying_and_managing_openshift_3.9_on_google_cloud_platform/)
